/**
 * Curated Christmas traditions catalogue — reference content only.
 * Nothing here is stored per user. When someone taps "Add to our Christmas"
 * we create an ordinary row in the `traditions` table from these fields.
 *
 * No AI, no external API: every idea below is written and tagged by hand.
 */

export type Audience =
  | "young_children"
  | "teenagers"
  | "young_adults"
  | "couple"
  | "adults_no_children"
  | "alone"
  | "extended"
  | "mixed_ages";

export type Mood =
  | "magical"
  | "traditional"
  | "cosy"
  | "fun"
  | "sentimental"
  | "romantic"
  | "relaxing"
  | "active"
  | "creative"
  | "meaningful";

export type Cost = "free" | "low" | "treat";
export type Place = "home" | "out" | "either";

export interface TraditionIdea {
  key: string;
  name: string;
  /** One warm line explaining the tradition. */
  blurb: string;
  /** One practical line — how to actually do it. */
  how: string;
  category: string;
  timing: string;
  audiences: Audience[];
  moods: Mood[];
  cost: Cost;
  place: Place;
  tags: string[];
}

const ALL: Audience[] = [
  "young_children",
  "teenagers",
  "young_adults",
  "couple",
  "adults_no_children",
  "alone",
  "extended",
  "mixed_ages",
];

export const TRADITION_IDEAS: TraditionIdea[] = [
  // ---- Little ones ---------------------------------------------------------
  {
    key: "christmas_eve_box",
    name: "A Christmas Eve box",
    blurb: "One little box opened on Christmas Eve to start the magic early.",
    how: "New pyjamas, a book, hot chocolate and a film — put it together in November.",
    category: "christmas_eve",
    timing: "christmas_eve",
    audiences: ["young_children", "mixed_ages", "extended"],
    moods: ["magical", "cosy"],
    cost: "low",
    place: "home",
    tags: ["Christmas Eve", "Children"],
  },
  {
    key: "santa_footprints",
    name: "Father Christmas footprints",
    blurb: "Snowy boot prints from the fireplace to the tree on Christmas morning.",
    how: "A little flour and a boot-shaped card, laid out after bedtime.",
    category: "christmas_morning",
    timing: "christmas_morning",
    audiences: ["young_children"],
    moods: ["magical", "fun"],
    cost: "free",
    place: "home",
    tags: ["Magical", "Free"],
  },
  {
    key: "new_decoration",
    name: "One new decoration each year",
    blurb: "Everyone chooses a decoration that says something about their year.",
    how: "Write the year on the back — in time the tree tells your family story.",
    category: "decorating",
    timing: "december",
    audiences: ALL,
    moods: ["sentimental", "traditional"],
    cost: "low",
    place: "either",
    tags: ["Keepsake", "Everyone"],
  },
  {
    key: "light_walk",
    name: "The Christmas-light walk",
    blurb: "An evening wander to see whose street has gone all out.",
    how: "Wrap up warm, take a flask, and walk the same route every year.",
    category: "going_out",
    timing: "december",
    audiences: ALL,
    moods: ["cosy", "active"],
    cost: "free",
    place: "out",
    tags: ["Free", "Outdoors"],
  },
  {
    key: "festive_baking",
    name: "A Christmas baking afternoon",
    blurb: "Flour everywhere, icing on the ceiling, biscuits for the neighbours.",
    how: "Pick one recipe, put the music on, and don't aim for perfect.",
    category: "food",
    timing: "december",
    audiences: ["young_children", "teenagers", "mixed_ages", "extended", "couple"],
    moods: ["creative", "fun", "cosy"],
    cost: "low",
    place: "home",
    tags: ["Baking", "Together"],
  },
  {
    key: "bedtime_story",
    name: "The Christmas bedtime story",
    blurb: "The same story, the same voice, every Christmas Eve.",
    how: "Choose one book and keep it wrapped away with the decorations.",
    category: "children",
    timing: "christmas_eve",
    audiences: ["young_children"],
    moods: ["cosy", "sentimental"],
    cost: "free",
    place: "home",
    tags: ["Christmas Eve", "Free"],
  },
  {
    key: "leave_for_santa",
    name: "Something out for Father Christmas",
    blurb: "A mince pie, a drink and a carrot left by the fire.",
    how: "Let the children choose the plate — it becomes the Christmas Eve plate.",
    category: "christmas_eve",
    timing: "christmas_eve",
    audiences: ["young_children", "mixed_ages"],
    moods: ["magical", "traditional"],
    cost: "free",
    place: "home",
    tags: ["Magical", "Free"],
  },
  {
    key: "annual_photo",
    name: "The annual Christmas photograph",
    blurb: "The same spot, the same pose, everyone a year older.",
    how: "Take it at the same moment each year — by the tree before the presents.",
    category: "family",
    timing: "christmas_day",
    audiences: ALL,
    moods: ["sentimental", "meaningful"],
    cost: "free",
    place: "home",
    tags: ["Keepsake", "Free"],
  },
  {
    key: "grotto_visit",
    name: "A visit to see Father Christmas",
    blurb: "The queue, the nerves, the little gift on the way out.",
    how: "Book early — the good grottos go by October.",
    category: "going_out",
    timing: "december",
    audiences: ["young_children"],
    moods: ["magical"],
    cost: "treat",
    place: "out",
    tags: ["Day out", "Children"],
  },
  {
    key: "advent_ritual",
    name: "Our own advent countdown",
    blurb: "A small thing to do together behind each December door.",
    how: "Write 24 tiny activities on paper slips — a film, a walk, a hot chocolate.",
    category: "children",
    timing: "december",
    audiences: ["young_children", "teenagers", "mixed_ages", "couple"],
    moods: ["magical", "creative"],
    cost: "free",
    place: "home",
    tags: ["December", "Free"],
  },
  {
    key: "reindeer_food",
    name: "Sprinkling reindeer food",
    blurb: "Out on the lawn before bed on Christmas Eve.",
    how: "Oats and a little edible glitter — safe for birds too.",
    category: "children",
    timing: "christmas_eve",
    audiences: ["young_children"],
    moods: ["magical", "fun"],
    cost: "free",
    place: "home",
    tags: ["Christmas Eve", "Free"],
  },
  {
    key: "nativity_or_carols",
    name: "The school play or carol service",
    blurb: "The one where you cry in the third row.",
    how: "Put the date in as soon as it's announced and go every single year.",
    category: "faith",
    timing: "december",
    audiences: ["young_children", "teenagers", "extended", "mixed_ages"],
    moods: ["sentimental", "traditional"],
    cost: "free",
    place: "out",
    tags: ["December", "Free"],
  },

  // ---- Older children and teenagers ---------------------------------------
  {
    key: "film_night",
    name: "The Christmas film night",
    blurb: "Duvets down, lights off, the same film every year.",
    how: "One night in December that nobody is allowed to book over.",
    category: "films_music",
    timing: "december",
    audiences: ALL,
    moods: ["cosy", "relaxing"],
    cost: "free",
    place: "home",
    tags: ["Cosy", "Free"],
  },
  {
    key: "everyone_picks_film",
    name: "Everyone picks one Christmas film",
    blurb: "One film each, no arguments, however questionable the choice.",
    how: "Draw the order out of a hat and work through December.",
    category: "films_music",
    timing: "december",
    audiences: ["teenagers", "young_adults", "mixed_ages", "couple", "adults_no_children"],
    moods: ["fun", "cosy"],
    cost: "free",
    place: "home",
    tags: ["Everyone", "Free"],
  },
  {
    key: "bake_off",
    name: "The family bake-off",
    blurb: "Two teams, one kitchen, an entirely unfair judging panel.",
    how: "Set a theme, an hour on the clock, and a silly trophy.",
    category: "games",
    timing: "december",
    audiences: ["teenagers", "young_adults", "mixed_ages", "extended"],
    moods: ["fun", "creative"],
    cost: "low",
    place: "home",
    tags: ["Fun", "Baking"],
  },
  {
    key: "games_tournament",
    name: "The Christmas games tournament",
    blurb: "A proper bracket, a trophy, and a year of bragging rights.",
    how: "Three quick games, knockout rounds, winner's name on something.",
    category: "games",
    timing: "christmas_day",
    audiences: ["teenagers", "young_adults", "mixed_ages", "extended", "adults_no_children"],
    moods: ["fun", "active"],
    cost: "free",
    place: "home",
    tags: ["Games", "Free"],
  },
  {
    key: "christmas_quiz",
    name: "The homemade Christmas quiz",
    blurb: "Someone different writes it each year — and it always goes too long.",
    how: "Twenty questions, half about the family, prizes from the pound shop.",
    category: "games",
    timing: "christmas_day",
    audiences: ["teenagers", "young_adults", "mixed_ages", "extended", "adults_no_children"],
    moods: ["fun"],
    cost: "free",
    place: "home",
    tags: ["Games", "Free"],
  },
  {
    key: "shopping_day",
    name: "The Christmas shopping day",
    blurb: "One day in town together — lunch included, phones mostly away.",
    how: "Set a budget each, meet for lunch, no peeking in bags.",
    category: "going_out",
    timing: "december",
    audiences: ["teenagers", "young_adults", "couple", "adults_no_children", "mixed_ages"],
    moods: ["fun", "active"],
    cost: "treat",
    place: "out",
    tags: ["Day out"],
  },
  {
    key: "decorate_together",
    name: "Decorating the tree together",
    blurb: "Everyone home, music on, nobody allowed to start without the others.",
    how: "Pick the date in November so it's in everyone's diary.",
    category: "decorating",
    timing: "december",
    audiences: ALL,
    moods: ["traditional", "cosy"],
    cost: "free",
    place: "home",
    tags: ["Decorating", "Free"],
  },
  {
    key: "christmas_jumper_day",
    name: "Our Christmas jumper day",
    blurb: "The worse the jumper, the better the year.",
    how: "One agreed day — photograph the results for the family album.",
    category: "family",
    timing: "december",
    audiences: ["young_children", "teenagers", "young_adults", "mixed_ages", "extended"],
    moods: ["fun"],
    cost: "low",
    place: "either",
    tags: ["Fun"],
  },
  {
    key: "wrapping_evening",
    name: "The wrapping evening",
    blurb: "All the presents, one long evening, a film in the background.",
    how: "Paper, tags, scissors, a drink — get it all done in one go.",
    category: "giving",
    timing: "december",
    audiences: ["teenagers", "young_adults", "couple", "adults_no_children", "alone", "mixed_ages"],
    moods: ["cosy", "relaxing"],
    cost: "free",
    place: "home",
    tags: ["December", "Free"],
  },

  // ---- Adult children, friends, grown-up Christmases -----------------------
  {
    key: "cocktail_evening",
    name: "The Christmas cocktail evening",
    blurb: "One festive drink each, made properly, mocktails just as welcome.",
    how: "Everyone brings a recipe — best one becomes next year's house drink.",
    category: "food",
    timing: "december",
    audiences: ["young_adults", "couple", "adults_no_children", "extended"],
    moods: ["fun", "cosy"],
    cost: "low",
    place: "home",
    tags: ["Grown-up"],
  },
  {
    key: "festive_meal_out",
    name: "The festive meal out",
    blurb: "The same restaurant, the same table, every December.",
    how: "Book in October — good tables go early.",
    category: "going_out",
    timing: "december",
    audiences: ["young_adults", "couple", "adults_no_children", "extended", "mixed_ages"],
    moods: ["traditional", "relaxing"],
    cost: "treat",
    place: "out",
    tags: ["Special"],
  },
  {
    key: "market_trip",
    name: "The Christmas market trip",
    blurb: "Mulled wine, terrible souvenirs, absolutely worth it.",
    how: "Pick one market and make it yours — go the same weekend each year.",
    category: "going_out",
    timing: "december",
    audiences: ALL,
    moods: ["cosy", "active"],
    cost: "low",
    place: "out",
    tags: ["Day out"],
  },
  {
    key: "secret_santa",
    name: "Secret Santa",
    blurb: "One gift each, a sensible limit, far more laughing.",
    how: "Draw names in November and agree the budget up front.",
    category: "giving",
    timing: "christmas_day",
    audiences: ["teenagers", "young_adults", "adults_no_children", "extended", "mixed_ages"],
    moods: ["fun"],
    cost: "low",
    place: "either",
    tags: ["Giving"],
  },
  {
    key: "games_night",
    name: "The annual games night",
    blurb: "Same night every year, snacks on the table, one long game.",
    how: "Rotate who hosts and who chooses the game.",
    category: "games",
    timing: "december",
    audiences: ["young_adults", "adults_no_children", "couple", "extended", "mixed_ages"],
    moods: ["fun", "cosy"],
    cost: "free",
    place: "home",
    tags: ["Games", "Free"],
  },
  {
    key: "cook_together",
    name: "Cook something together",
    blurb: "One dish nobody makes alone — always made side by side.",
    how: "Choose the recipe together and shop for it as part of the day.",
    category: "food",
    timing: "december",
    audiences: ["young_adults", "couple", "adults_no_children", "extended", "mixed_ages"],
    moods: ["creative", "cosy"],
    cost: "low",
    place: "home",
    tags: ["Food"],
  },
  {
    key: "pub_walk",
    name: "The Christmas walk and a pub",
    blurb: "A proper walk, muddy boots, then somewhere warm with a fire.",
    how: "Same route, same pub, whoever is home that year.",
    category: "going_out",
    timing: "boxing_day",
    audiences: ["young_adults", "couple", "adults_no_children", "extended", "mixed_ages", "teenagers"],
    moods: ["active", "traditional"],
    cost: "low",
    place: "out",
    tags: ["Outdoors"],
  },
  {
    key: "wreath_making",
    name: "A wreath-making evening",
    blurb: "Foliage on the kitchen table and something to hang on the door.",
    how: "Buy a couple of bases, forage the greenery, share the wire.",
    category: "decorating",
    timing: "december",
    audiences: ["young_adults", "couple", "adults_no_children", "alone", "extended"],
    moods: ["creative", "cosy"],
    cost: "low",
    place: "home",
    tags: ["Creative"],
  },
  {
    key: "friends_gathering",
    name: "The annual friends' gathering",
    blurb: "The one December night everybody keeps free.",
    how: "Fix the date in September — it only survives if it's booked early.",
    category: "friends",
    timing: "december",
    audiences: ["young_adults", "adults_no_children", "couple", "alone"],
    moods: ["fun", "meaningful"],
    cost: "low",
    place: "either",
    tags: ["Friends"],
  },
  {
    key: "christmas_drinks",
    name: "Christmas drinks at ours",
    blurb: "Doors open, mince pies out, people drop in through the afternoon.",
    how: "Two hours, no seating plan, everyone brings something.",
    category: "friends",
    timing: "december",
    audiences: ["adults_no_children", "couple", "young_adults", "extended"],
    moods: ["fun", "relaxing"],
    cost: "low",
    place: "home",
    tags: ["Friends"],
  },

  // ---- Couples -------------------------------------------------------------
  {
    key: "date_night",
    name: "Our Christmas date night",
    blurb: "One evening in December that belongs to just the two of you.",
    how: "Book it before the diary fills — dinner, lights, or simply nowhere to be.",
    category: "going_out",
    timing: "december",
    audiences: ["couple"],
    moods: ["romantic", "relaxing"],
    cost: "treat",
    place: "either",
    tags: ["Just us"],
  },
  {
    key: "ornament_together",
    name: "Choose an ornament together",
    blurb: "One decoration a year that marks where you were.",
    how: "Buy it wherever you happen to be — write the year on the back.",
    category: "decorating",
    timing: "december",
    audiences: ["couple"],
    moods: ["romantic", "sentimental"],
    cost: "low",
    place: "either",
    tags: ["Keepsake"],
  },
  {
    key: "eve_gift",
    name: "One gift on Christmas Eve",
    blurb: "A single present each, opened by the tree the night before.",
    how: "Keep it small and personal — the tradition matters more than the gift.",
    category: "christmas_eve",
    timing: "christmas_eve",
    audiences: ["couple", "young_adults", "mixed_ages"],
    moods: ["romantic", "cosy"],
    cost: "low",
    place: "home",
    tags: ["Christmas Eve"],
  },
  {
    key: "special_meal_home",
    name: "A special meal, just at home",
    blurb: "Better than a restaurant, and nobody has to drive.",
    how: "One showstopper dish, good candles, phones in the drawer.",
    category: "food",
    timing: "december",
    audiences: ["couple", "adults_no_children", "alone"],
    moods: ["romantic", "cosy", "relaxing"],
    cost: "low",
    place: "home",
    tags: ["Food"],
  },
  {
    key: "winter_walk",
    name: "The winter walk",
    blurb: "Cold air, big coats, and a proper look at the year gone by.",
    how: "Same walk each year — somewhere that always looks good in December.",
    category: "going_out",
    timing: "flexible",
    audiences: ALL,
    moods: ["active", "relaxing", "meaningful"],
    cost: "free",
    place: "out",
    tags: ["Outdoors", "Free"],
  },

  // ---- Multi-generational and extended family ------------------------------
  {
    key: "family_recipe",
    name: "The inherited family recipe",
    blurb: "The one somebody's grandmother made, still made the same way.",
    how: "Write the recipe out properly this year and cook it with someone younger.",
    category: "remembering",
    timing: "december",
    audiences: ["extended", "mixed_ages", "young_adults", "adults_no_children"],
    moods: ["sentimental", "traditional", "meaningful"],
    cost: "low",
    place: "home",
    tags: ["Keepsake", "Food"],
  },
  {
    key: "memory_decorations",
    name: "Memory decorations",
    blurb: "A decoration on the tree for each person we're missing.",
    how: "Hang them together and say a little about each one.",
    category: "remembering",
    timing: "december",
    audiences: ["extended", "mixed_ages", "adults_no_children", "alone", "couple"],
    moods: ["sentimental", "meaningful"],
    cost: "low",
    place: "home",
    tags: ["Remembering"],
  },
  {
    key: "storytelling",
    name: "Christmas storytelling",
    blurb: "Everyone shares one Christmas they still remember.",
    how: "After dinner, one story each — record them if you can.",
    category: "remembering",
    timing: "christmas_day",
    audiences: ["extended", "mixed_ages", "young_adults"],
    moods: ["sentimental", "meaningful"],
    cost: "free",
    place: "home",
    tags: ["Free", "Together"],
  },
  {
    key: "visit_relatives",
    name: "The Christmas visit",
    blurb: "The relatives who don't travel — we go to them.",
    how: "Pick the day in November and take something homemade.",
    category: "family",
    timing: "december",
    audiences: ["extended", "mixed_ages", "young_adults", "couple"],
    moods: ["meaningful", "traditional"],
    cost: "free",
    place: "out",
    tags: ["Family", "Free"],
  },
  {
    key: "eve_gathering",
    name: "The Christmas Eve gathering",
    blurb: "Everybody in one room the night before it all begins.",
    how: "Buffet, not a sit-down — nobody should be cooking twice.",
    category: "christmas_eve",
    timing: "christmas_eve",
    audiences: ["extended", "mixed_ages"],
    moods: ["traditional", "cosy"],
    cost: "low",
    place: "home",
    tags: ["Christmas Eve"],
  },
  {
    key: "everyone_a_dish",
    name: "Everyone brings a dish",
    blurb: "No one person cooking for fourteen people.",
    how: "Agree who brings what in November so nobody doubles up.",
    category: "food",
    timing: "christmas_day",
    audiences: ["extended", "mixed_ages"],
    moods: ["relaxing", "traditional"],
    cost: "low",
    place: "home",
    tags: ["Hosting"],
  },
  {
    key: "family_walk",
    name: "The Boxing Day family walk",
    blurb: "Everybody out of the house, whatever the weather.",
    how: "Same time, same place — latecomers catch up.",
    category: "family",
    timing: "boxing_day",
    audiences: ["extended", "mixed_ages", "young_children", "teenagers"],
    moods: ["active", "traditional"],
    cost: "free",
    place: "out",
    tags: ["Outdoors", "Free"],
  },
  {
    key: "grandparents_call",
    name: "The Christmas morning call",
    blurb: "The people we can't be with, first thing, before anything else.",
    how: "Agree a time in advance so it never gets forgotten.",
    category: "family",
    timing: "christmas_morning",
    audiences: ALL,
    moods: ["meaningful", "sentimental"],
    cost: "free",
    place: "home",
    tags: ["Free"],
  },

  // ---- Christmas alone -----------------------------------------------------
  {
    key: "favourite_breakfast",
    name: "My favourite Christmas breakfast",
    blurb: "Exactly what you like, eaten slowly, with the good coffee.",
    how: "Buy the ingredients specially — it isn't Christmas if it's the usual.",
    category: "food",
    timing: "christmas_morning",
    audiences: ["alone", "couple", "adults_no_children"],
    moods: ["cosy", "relaxing"],
    cost: "low",
    place: "home",
    tags: ["Just for me"],
  },
  {
    key: "my_film",
    name: "The film I always watch",
    blurb: "One film, no compromise, nobody talking over it.",
    how: "Put the day and time in the diary like a proper appointment.",
    category: "films_music",
    timing: "christmas_day",
    audiences: ["alone", "couple", "adults_no_children"],
    moods: ["cosy", "relaxing"],
    cost: "free",
    place: "home",
    tags: ["Free", "Just for me"],
  },
  {
    key: "order_favourite",
    name: "Cook or order exactly what I fancy",
    blurb: "No turkey unless you want turkey.",
    how: "Decide in advance and order early — plenty of places take Christmas bookings.",
    category: "food",
    timing: "christmas_day",
    audiences: ["alone", "couple", "adults_no_children"],
    moods: ["relaxing"],
    cost: "treat",
    place: "home",
    tags: ["Just for me"],
  },
  {
    key: "christmas_playlist",
    name: "My Christmas playlist",
    blurb: "Built up over years, played from the first of December.",
    how: "Add one new song each year and keep the old ones.",
    category: "films_music",
    timing: "december",
    audiences: ALL,
    moods: ["cosy", "sentimental"],
    cost: "free",
    place: "either",
    tags: ["Free", "Music"],
  },
  {
    key: "call_someone",
    name: "Call someone who'd love to hear from you",
    blurb: "One call a year that means far more than it costs.",
    how: "Pick the person now and put the time in your diary.",
    category: "kindness",
    timing: "christmas_day",
    audiences: ALL,
    moods: ["meaningful"],
    cost: "free",
    place: "home",
    tags: ["Kindness", "Free"],
  },
  {
    key: "yearly_reflection",
    name: "My yearly reflection",
    blurb: "An hour to look back honestly and look forward kindly.",
    how: "A notebook, a warm drink, three things you're glad about.",
    category: "faith",
    timing: "new_year",
    audiences: ["alone", "adults_no_children", "couple", "young_adults"],
    moods: ["meaningful", "relaxing"],
    cost: "free",
    place: "home",
    tags: ["Free", "Reflection"],
  },
  {
    key: "treat_yourself",
    name: "The treat-yourself tradition",
    blurb: "One lovely thing bought for you, by you, every year.",
    how: "Set the budget in November so it feels planned rather than guilty.",
    category: "giving",
    timing: "december",
    audiences: ["alone", "adults_no_children", "young_adults", "couple"],
    moods: ["relaxing"],
    cost: "treat",
    place: "either",
    tags: ["Just for me"],
  },
  {
    key: "solo_day_out",
    name: "A Christmas day out on my own terms",
    blurb: "A gallery, a cathedral, a coast walk — somewhere that lifts you.",
    how: "Choose the place in November and treat it as unmissable.",
    category: "going_out",
    timing: "december",
    audiences: ["alone", "adults_no_children", "couple"],
    moods: ["active", "meaningful"],
    cost: "low",
    place: "out",
    tags: ["Day out"],
  },

  // ---- Kindness, faith, giving --------------------------------------------
  {
    key: "charity_gift",
    name: "One gift for someone we'll never meet",
    blurb: "A present bought for a local giving tree or food bank.",
    how: "Let each person choose their own — take them shopping for it.",
    category: "kindness",
    timing: "december",
    audiences: ALL,
    moods: ["meaningful"],
    cost: "low",
    place: "either",
    tags: ["Kindness"],
  },
  {
    key: "neighbour_treats",
    name: "Something on the neighbours' doorsteps",
    blurb: "Biscuits, a card, a small jar of something homemade.",
    how: "Bake a double batch and deliver them the weekend before Christmas.",
    category: "kindness",
    timing: "december",
    audiences: ALL,
    moods: ["meaningful", "creative"],
    cost: "low",
    place: "either",
    tags: ["Kindness"],
  },
  {
    key: "carol_service",
    name: "The carol service by candlelight",
    blurb: "Cold church, warm singing, the proper start to Christmas.",
    how: "Check the time in early December — the good ones fill up.",
    category: "faith",
    timing: "christmas_eve",
    audiences: ALL,
    moods: ["traditional", "meaningful"],
    cost: "free",
    place: "out",
    tags: ["Free", "Christmas Eve"],
  },
  {
    key: "toast_the_absent",
    name: "A toast to the people not here",
    blurb: "A moment before the meal for everyone we're missing.",
    how: "Whoever carves says the words — it takes thirty seconds and lasts all year.",
    category: "remembering",
    timing: "christmas_day",
    audiences: ALL,
    moods: ["sentimental", "meaningful"],
    cost: "free",
    place: "home",
    tags: ["Free", "Remembering"],
  },
  {
    key: "gratitude_round",
    name: "One good thing each",
    blurb: "Around the table, everybody names one good thing about their year.",
    how: "Start with the youngest — it works far better than you'd expect.",
    category: "family",
    timing: "christmas_day",
    audiences: ALL,
    moods: ["meaningful", "sentimental"],
    cost: "free",
    place: "home",
    tags: ["Free"],
  },

  // ---- Christmas Day and New Year rhythm -----------------------------------
  {
    key: "stocking_first",
    name: "Stockings on the bed first",
    blurb: "Everything else waits until stockings are done.",
    how: "Agree the earliest allowed hour — and stick to it.",
    category: "christmas_morning",
    timing: "christmas_morning",
    audiences: ["young_children", "teenagers", "mixed_ages", "extended", "couple"],
    moods: ["traditional", "fun"],
    cost: "free",
    place: "home",
    tags: ["Christmas morning", "Free"],
  },
  {
    key: "one_present_slowly",
    name: "One present at a time",
    blurb: "Everybody watches, everybody says thank you — it takes all morning.",
    how: "Somebody plays elf and hands them out one by one.",
    category: "christmas_day",
    timing: "christmas_morning",
    audiences: ALL,
    moods: ["traditional", "sentimental"],
    cost: "free",
    place: "home",
    tags: ["Free"],
  },
  {
    key: "pyjamas_all_day",
    name: "Pyjamas until teatime",
    blurb: "No getting dressed, no going anywhere, nobody minds.",
    how: "New pyjamas on Christmas Eve makes this one easy.",
    category: "christmas_day",
    timing: "christmas_day",
    audiences: ["young_children", "teenagers", "couple", "alone", "mixed_ages"],
    moods: ["cosy", "relaxing"],
    cost: "free",
    place: "home",
    tags: ["Cosy", "Free"],
  },
  {
    key: "boxing_day_buffet",
    name: "The Boxing Day buffet",
    blurb: "Cold cuts, pickles, leftovers — the best meal of the lot.",
    how: "Lay it out at midday and let people graze all afternoon.",
    category: "food",
    timing: "boxing_day",
    audiences: ["extended", "mixed_ages", "couple", "adults_no_children"],
    moods: ["relaxing", "traditional"],
    cost: "free",
    place: "home",
    tags: ["Boxing Day", "Free"],
  },
  {
    key: "twixmas_day_out",
    name: "A day out between Christmas and New Year",
    blurb: "One outing in the strange quiet week when nobody knows the date.",
    how: "Pick it on Boxing Day so the week doesn't disappear.",
    category: "going_out",
    timing: "flexible",
    audiences: ALL,
    moods: ["active", "relaxing"],
    cost: "low",
    place: "out",
    tags: ["Day out"],
  },
  {
    key: "new_year_hopes",
    name: "Writing next year's hopes",
    blurb: "Not resolutions — three things you'd like the year to hold.",
    how: "Seal them in an envelope and open it next Christmas.",
    category: "new_year",
    timing: "new_year",
    audiences: ALL,
    moods: ["meaningful", "creative"],
    cost: "free",
    place: "home",
    tags: ["New Year", "Free"],
  },
  {
    key: "take_down_together",
    name: "Taking the decorations down together",
    blurb: "Twelfth Night, everybody helping, one last mince pie.",
    how: "Put the music back on — it makes the melancholy job much nicer.",
    category: "decorating",
    timing: "new_year",
    audiences: ALL,
    moods: ["traditional", "cosy"],
    cost: "free",
    place: "home",
    tags: ["Free"],
  },
  {
    key: "christmas_card_photo",
    name: "The Christmas card photograph",
    blurb: "One photo, printed on the card, sent to everybody.",
    how: "Take it in November — you'll need longer than you think.",
    category: "giving",
    timing: "december",
    audiences: ["young_children", "teenagers", "couple", "extended", "mixed_ages"],
    moods: ["creative", "sentimental"],
    cost: "low",
    place: "either",
    tags: ["Cards"],
  },
  {
    key: "first_snow_hot_chocolate",
    name: "The first proper cold night",
    blurb: "Hot chocolate, blankets, the tree lights on and nothing else.",
    how: "Keep the good cocoa in the cupboard from December first.",
    category: "family",
    timing: "december",
    audiences: ALL,
    moods: ["cosy", "relaxing"],
    cost: "free",
    place: "home",
    tags: ["Cosy", "Free"],
  },
  {
    key: "posting_letters",
    name: "Posting the letters to Father Christmas",
    blurb: "Written, decorated, walked to the postbox together.",
    how: "Do it early in December so there's time for a reply.",
    category: "children",
    timing: "december",
    audiences: ["young_children"],
    moods: ["magical", "creative"],
    cost: "free",
    place: "out",
    tags: ["Children", "Free"],
  },
  {
    key: "panto",
    name: "The pantomime",
    blurb: "Oh yes it is. Every single year.",
    how: "Book in September for a weekend matinee.",
    category: "going_out",
    timing: "december",
    audiences: ["young_children", "teenagers", "extended", "mixed_ages"],
    moods: ["fun", "traditional"],
    cost: "treat",
    place: "out",
    tags: ["Day out"],
  },
  {
    key: "ice_skating",
    name: "The Christmas skate",
    blurb: "An hour on the ice and considerably more time in the café after.",
    how: "Book the earliest slot — it's quieter and cheaper.",
    category: "going_out",
    timing: "december",
    audiences: ["young_children", "teenagers", "young_adults", "couple", "mixed_ages"],
    moods: ["active", "fun"],
    cost: "treat",
    place: "out",
    tags: ["Active", "Day out"],
  },
  {
    key: "christmas_book",
    name: "A Christmas book each",
    blurb: "One book given on Christmas Eve, read before the year is out.",
    how: "Wrap them together and open them at the same moment.",
    category: "giving",
    timing: "christmas_eve",
    audiences: ALL,
    moods: ["cosy", "sentimental"],
    cost: "low",
    place: "home",
    tags: ["Christmas Eve"],
  },
  {
    key: "decorate_gingerbread",
    name: "The gingerbread house",
    blurb: "Structurally unsound, generously iced, eaten within a week.",
    how: "A kit is absolutely allowed — the fun is in the sweets.",
    category: "food",
    timing: "december",
    audiences: ["young_children", "teenagers", "mixed_ages", "extended"],
    moods: ["creative", "fun"],
    cost: "low",
    place: "home",
    tags: ["Baking", "Children"],
  },
];

export function ideaByKey(key: string): TraditionIdea | undefined {
  return TRADITION_IDEAS.find((i) => i.key === key);
}
