/**
 * Human-curated Christmas viewing catalogue — reference content only.
 *
 * ONE MASTER TITLE = ONE RECORD. A title never appears twice; crossovers are
 * extra keys inside `strength`.
 *
 * Nothing here is stored per user. "Add to my watchlist" creates an ordinary
 * row in the `watchlist_items` table from these fields.
 *
 * No AI, no external API, no copyrighted summaries or artwork: every blurb is
 * a short original line written for A Complete Christmas.
 *
 * `ukCertificate` and `posterUrl` are deliberately unset everywhere: they are
 * populated only from verified UK classification data and licensed artwork
 * during human curation.
 */

import type {
  AgeBand,
  ChristmasRelevance,
  ContextKey,
  MoodKey,
  Strength,
  UkCertificate,
} from "./vocabulary";

export type ContentType = "film" | "tv_special" | "episode" | "series" | "other";

export type { AgeBand, ChristmasRelevance, ContextKey, Strength };

export interface CatalogueTitle {
  /** Stable, never reused. Also the `suggestion_key` on saved rows. */
  key: string;
  title: string;
  year?: number;
  type: ContentType;
  /** One short, original sentence describing what makes it Christmassy. */
  blurb: string;
  minutes?: number;

  /**
   * Official UK certificate (BBFC classification). Display metadata only —
   * never used by the internal suitability/recommendation engine. Populated
   * only from verified UK classification data; currently unset on all titles.
   */
  ukCertificate?: UkCertificate;

  /** Film artwork URL. Unset until poster artwork is added; cards show a placeholder meanwhile. */
  posterUrl?: string;

  /** How fundamentally the title relates to Christmas. */
  christmas: ChristmasRelevance;

  /**
   * INTERNAL A Complete Christmas viewing guidance only — never shown as an
   * official age rating and never implying any certification body.
   */
  suitability: AgeBand;

  /** The whole of human curation. Absent key = not recommended for that context. */
  strength: Partial<Record<ContextKey, Strength>>;

  /** Occasions this suits (shared timing vocabulary). */
  timings?: string[];

  /** Optional human "why" line, overriding the generated one. */
  note?: string;
}

/** Back-compat alias for existing importers. */
export type WatchlistIdea = CatalogueTitle;

/** Shorthand: every context an adult-only title must be blocked from. */
const ADULT_BLOCK: Partial<Record<ContextKey, Strength>> = {
  young_children: "unsuitable",
  older_children: "unsuitable",
  teenagers: "unsuitable",
  family: "unsuitable",
  mixed_ages: "unsuitable",
  multigenerational: "unsuitable",
};

/** Shorthand: blocked for children, fine with teenagers upwards. */
const TEEN_BLOCK: Partial<Record<ContextKey, Strength>> = {
  young_children: "unsuitable",
  older_children: "unsuitable",
};

export const WATCHLIST_IDEAS: CatalogueTitle[] = [
  /* ============================================================ romance */
  {
    key: "the_holiday",
    title: "The Holiday",
    year: 2006,
    type: "film",
    minutes: 136,
    blurb: "Two women swap homes for Christmas and quietly rebuild their lives.",
    christmas: "core",
    suitability: "12+",
    timings: ["december", "christmas_eve", "weekend"],
    note: "The definitive Christmas romance — cottage, snow, and a very good cry.",
    strength: {
      romance: "essential",
      christmas_romance: "essential",
      cosy: "essential",
      couple: "essential",
      cosy_night: "essential",
      adults: "strong",
      adult_children: "strong",
      teenagers: "strong",
      alone: "strong",
      modern_classic: "strong",
      christmas_classics: "strong",
      kids_in_bed: "strong",
      feel_good: "strong",
      comedy: "extra",
      young_children: "unsuitable",
    },
  },
  {
    key: "love_actually",
    title: "Love Actually",
    year: 2003,
    type: "film",
    minutes: 135,
    blurb: "Nine London love stories collide in the weeks before Christmas.",
    christmas: "core",
    suitability: "adult",
    timings: ["december", "christmas_eve"],
    strength: {
      romance: "essential",
      christmas_romance: "essential",
      british: "essential",
      classic: "strong",
      christmas_classics: "strong",
      comedy: "strong",
      couple: "essential",
      adults: "strong",
      adult_children: "strong",
      adults_no_children: "strong",
      emotional: "strong",
      modern_classic: "strong",
      kids_in_bed: "strong",
      cosy_night: "strong",
      with_grown_up_children: "strong",
      young_children: "unsuitable",
      older_children: "unsuitable",
    },
  },
  {
    key: "last_christmas",
    title: "Last Christmas",
    year: 2019,
    type: "film",
    minutes: 103,
    blurb: "A London shop elf stumbles her way towards a better year.",
    christmas: "core",
    suitability: "12+",
    timings: ["december", "weekend"],
    strength: {
      romance: "essential",
      christmas_romance: "essential",
      british: "strong",
      couple: "essential",
      cosy: "strong",
      modern: "strong",
      adults: "strong",
      teenagers: "strong",
      emotional: "strong",
      cosy_night: "strong",
      young_children: "unsuitable",
    },
  },
  {
    key: "love_hard",
    title: "Love Hard",
    year: 2021,
    type: "film",
    minutes: 104,
    blurb: "A catfished dating-app romance turns into a full Christmas fortnight.",
    christmas: "core",
    suitability: "12+",
    timings: ["december", "weekend"],
    strength: {
      romance: "essential",
      christmas_romance: "strong",
      comedy: "strong",
      modern: "strong",
      couple: "essential",
      adults: "strong",
      young_adults: "strong",
      cosy_night: "strong",
      young_children: "unsuitable",
    },
  },
  {
    key: "the_family_stone",
    title: "The Family Stone",
    year: 2005,
    type: "film",
    minutes: 103,
    blurb: "A tense family Christmas where nobody behaves and everybody means well.",
    christmas: "core",
    suitability: "12+",
    timings: ["december", "christmas_day"],
    strength: {
      romance: "essential",
      christmas_romance: "strong",
      emotional: "essential",
      cosy: "strong",
      adults: "strong",
      adult_children: "strong",
      teenagers: "strong",
      couple: "strong",
      with_grown_up_children: "strong",
      kids_in_bed: "strong",
      young_children: "unsuitable",
      older_children: "unsuitable",
    },
  },
  {
    key: "happiest_season",
    title: "Happiest Season",
    year: 2020,
    type: "film",
    minutes: 102,
    blurb: "Meeting the parents at Christmas, with one enormous secret in the way.",
    christmas: "core",
    suitability: "12+",
    timings: ["december"],
    strength: {
      romance: "strong",
      christmas_romance: "strong",
      comedy: "strong",
      modern: "strong",
      couple: "strong",
      adults: "strong",
      young_adults: "strong",
      teenagers: "extra",
      cosy_night: "strong",
      young_children: "unsuitable",
    },
  },
  {
    key: "single_all_the_way",
    title: "Single All the Way",
    year: 2021,
    type: "film",
    minutes: 99,
    blurb: "A fake-boyfriend plan unravels fast in a very loud family home.",
    christmas: "core",
    suitability: "12+",
    timings: ["december"],
    strength: {
      romance: "strong",
      christmas_romance: "strong",
      comedy: "strong",
      modern: "strong",
      couple: "strong",
      adults: "strong",
      young_adults: "strong",
      cosy_night: "strong",
      young_children: "unsuitable",
    },
  },
  {
    key: "something_from_tiffanys",
    title: "Something from Tiffany's",
    year: 2022,
    type: "film",
    minutes: 87,
    blurb: "Two swapped gift boxes send four lives in the wrong lovely direction.",
    christmas: "core",
    suitability: "12+",
    timings: ["december"],
    strength: {
      romance: "strong",
      christmas_romance: "strong",
      modern: "strong",
      couple: "strong",
      adults: "strong",
      cosy_night: "strong",
      young_children: "unsuitable",
    },
  },
  {
    key: "four_christmases",
    title: "Four Christmases",
    year: 2008,
    type: "film",
    minutes: 88,
    blurb: "A couple face four family Christmases in a single exhausting day.",
    christmas: "core",
    suitability: "adult",
    timings: ["december", "christmas_day"],
    strength: {
      ...ADULT_BLOCK,
      comedy: "essential",
      adult_christmas: "strong",
      romance: "strong",
      couple: "strong",
      adults: "strong",
      adults_no_children: "strong",
      kids_in_bed: "strong",
    },
  },
  {
    key: "just_friends",
    title: "Just Friends",
    year: 2005,
    type: "film",
    minutes: 96,
    blurb: "Going home for Christmas as the one who finally glowed up.",
    christmas: "core",
    suitability: "12+",
    timings: ["december"],
    strength: {
      romance: "strong",
      comedy: "strong",
      nostalgic: "strong",
      adults: "strong",
      young_adults: "strong",
      kids_in_bed: "strong",
      young_children: "unsuitable",
      older_children: "unsuitable",
    },
  },
  {
    key: "serendipity",
    title: "Serendipity",
    year: 2001,
    type: "film",
    minutes: 90,
    blurb: "One snowy New York shopping trip and years of near misses.",
    christmas: "christmas_adjacent",
    suitability: "12+",
    timings: ["december", "any_time"],
    strength: {
      romance: "strong",
      secret_christmas: "extra",
      cosy: "strong",
      nostalgic: "strong",
      couple: "strong",
      adults: "strong",
      cosy_night: "strong",
      young_children: "unsuitable",
    },
  },
  {
    key: "the_noel_diary",
    title: "The Noel Diary",
    year: 2022,
    type: "film",
    minutes: 100,
    blurb: "Clearing out a family house at Christmas turns up a stranger's diary.",
    christmas: "core",
    suitability: "12+",
    timings: ["december"],
    strength: {
      romance: "strong",
      christmas_romance: "strong",
      emotional: "strong",
      cosy: "strong",
      adults: "strong",
      couple: "strong",
      cosy_night: "strong",
      young_children: "unsuitable",
    },
  },
  {
    key: "a_castle_for_christmas",
    title: "A Castle for Christmas",
    year: 2021,
    type: "film",
    minutes: 98,
    blurb: "A bruised novelist tries to buy a Scottish castle from its grumpy duke.",
    christmas: "core",
    suitability: "8+",
    timings: ["december"],
    strength: {
      romance: "strong",
      christmas_romance: "strong",
      cosy: "strong",
      british: "extra",
      adults: "strong",
      couple: "strong",
      cosy_night: "strong",
    },
  },
  {
    key: "falling_for_christmas",
    title: "Falling for Christmas",
    year: 2022,
    type: "film",
    minutes: 93,
    blurb: "An heiress loses her memory on a ski slope and gains a lodge full of chaos.",
    christmas: "core",
    suitability: "8+",
    timings: ["december"],
    strength: {
      romance: "strong",
      christmas_romance: "strong",
      comedy: "strong",
      modern: "strong",
      adults: "strong",
      couple: "strong",
      teenagers: "extra",
      cosy_night: "strong",
    },
  },
  {
    key: "a_christmas_prince",
    title: "A Christmas Prince",
    year: 2017,
    type: "film",
    minutes: 92,
    blurb: "An undercover journalist, a small European kingdom and a very tidy romance.",
    christmas: "core",
    suitability: "8+",
    timings: ["december"],
    strength: {
      romance: "strong",
      christmas_romance: "strong",
      cosy: "strong",
      adults: "strong",
      teenagers: "extra",
      cosy_night: "strong",
    },
  },
  {
    key: "the_princess_switch",
    title: "The Princess Switch",
    year: 2018,
    type: "film",
    minutes: 101,
    blurb: "A baker and a duchess swap lives for one royal Christmas week.",
    christmas: "core",
    suitability: "all",
    timings: ["december"],
    strength: {
      romance: "strong",
      christmas_romance: "strong",
      cosy: "strong",
      family: "extra",
      teenagers: "strong",
      adults: "strong",
      cosy_night: "strong",
    },
  },
  {
    key: "the_knight_before_christmas",
    title: "The Knight Before Christmas",
    year: 2019,
    type: "film",
    minutes: 92,
    blurb: "A medieval knight lands in modern Ohio and takes Christmas very seriously.",
    christmas: "core",
    suitability: "8+",
    timings: ["december"],
    strength: {
      romance: "strong",
      christmas_romance: "strong",
      comedy: "extra",
      cosy: "strong",
      teenagers: "extra",
      adults: "strong",
      cosy_night: "strong",
    },
  },
  {
    key: "the_holiday_calendar",
    title: "The Holiday Calendar",
    year: 2018,
    type: "film",
    minutes: 95,
    blurb: "An antique advent calendar starts predicting a photographer's love life.",
    christmas: "core",
    suitability: "8+",
    timings: ["december"],
    strength: {
      romance: "strong",
      christmas_romance: "strong",
      magical: "extra",
      adults: "strong",
      cosy_night: "strong",
    },
  },
  {
    key: "operation_christmas_drop",
    title: "Operation Christmas Drop",
    year: 2020,
    type: "film",
    minutes: 95,
    blurb: "Sunshine, an air base and a Christmas tradition worth saving.",
    christmas: "core",
    suitability: "8+",
    timings: ["december"],
    strength: {
      romance: "strong",
      christmas_romance: "strong",
      feel_good: "strong",
      adults: "strong",
      cosy_night: "strong",
    },
  },
  {
    key: "a_california_christmas",
    title: "A California Christmas",
    year: 2020,
    type: "film",
    minutes: 106,
    blurb: "A city charmer pretends to be a ranch hand on a Californian dairy farm.",
    christmas: "core",
    suitability: "12+",
    timings: ["december"],
    strength: {
      romance: "strong",
      christmas_romance: "strong",
      modern: "strong",
      adults: "strong",
      cosy_night: "strong",
      young_children: "unsuitable",
    },
  },
  {
    key: "christmas_with_you",
    title: "Christmas with You",
    year: 2022,
    type: "film",
    minutes: 90,
    blurb: "A burnt-out pop star grants a fan's wish and finds a quieter life.",
    christmas: "core",
    suitability: "8+",
    timings: ["december"],
    strength: {
      romance: "strong",
      christmas_romance: "strong",
      musical: "extra",
      adults: "strong",
      teenagers: "extra",
      cosy_night: "strong",
    },
  },
  {
    key: "hot_frosty",
    title: "Hot Frosty",
    year: 2024,
    type: "film",
    minutes: 90,
    blurb: "A snowman comes to life in a small town, exactly as silly as it sounds.",
    christmas: "core",
    suitability: "12+",
    timings: ["december"],
    strength: {
      romance: "strong",
      christmas_romance: "strong",
      comedy: "strong",
      modern: "strong",
      adults: "strong",
      cosy_night: "strong",
      young_children: "unsuitable",
    },
  },
  {
    key: "meet_me_next_christmas",
    title: "Meet Me Next Christmas",
    year: 2024,
    type: "film",
    minutes: 96,
    blurb: "A year-old promise sends one woman chasing an impossible concert ticket.",
    christmas: "core",
    suitability: "8+",
    timings: ["december"],
    strength: {
      romance: "strong",
      christmas_romance: "strong",
      modern: "strong",
      adults: "strong",
      cosy_night: "strong",
    },
  },
  {
    key: "our_little_secret",
    title: "Our Little Secret",
    year: 2024,
    type: "film",
    minutes: 100,
    blurb: "Two exes discover their new partners are siblings — at Christmas.",
    christmas: "core",
    suitability: "12+",
    timings: ["december"],
    strength: {
      romance: "strong",
      christmas_romance: "strong",
      comedy: "strong",
      modern: "strong",
      adults: "strong",
      cosy_night: "strong",
      young_children: "unsuitable",
    },
  },
  {
    key: "the_merry_gentlemen",
    title: "The Merry Gentlemen",
    year: 2024,
    type: "film",
    minutes: 90,
    blurb: "A dancer saves her parents' venue with a festive all-male revue.",
    christmas: "core",
    suitability: "adult",
    timings: ["december"],
    strength: {
      ...ADULT_BLOCK,
      romance: "strong",
      christmas_romance: "extra",
      adults: "strong",
      adults_no_children: "strong",
      kids_in_bed: "strong",
    },
  },
  {
    key: "holidate",
    title: "Holidate",
    year: 2020,
    type: "film",
    minutes: 104,
    blurb: "Two cynics agree to be each other's plus-one for every holiday going.",
    christmas: "christmas_adjacent",
    suitability: "adult",
    timings: ["december", "any_time"],
    strength: {
      ...ADULT_BLOCK,
      romance: "strong",
      comedy: "strong",
      modern: "strong",
      adults: "strong",
      adults_no_children: "strong",
      kids_in_bed: "strong",
    },
  },
  {
    key: "feast_of_the_seven_fishes",
    title: "Feast of the Seven Fishes",
    year: 2019,
    type: "film",
    minutes: 99,
    blurb: "An Italian-American family cooks its way through Christmas Eve in 1983.",
    christmas: "strong_setting",
    suitability: "adult",
    timings: ["christmas_eve", "december"],
    strength: {
      ...ADULT_BLOCK,
      romance: "strong",
      cosy: "strong",
      nostalgic: "strong",
      adults: "strong",
      kids_in_bed: "strong",
      cosy_night: "strong",
    },
  },

  /* ================================================== secret Christmas */
  {
    key: "bridget_jones_diary",
    title: "Bridget Jones's Diary",
    year: 2001,
    type: "film",
    minutes: 97,
    blurb: "Opens and closes at Christmas, reindeer jumper and all.",
    christmas: "christmas_adjacent",
    suitability: "adult",
    timings: ["december", "any_time"],
    note: "A secret Christmas film — it starts and ends with a Christmas party.",
    strength: {
      ...ADULT_BLOCK,
      secret_christmas: "essential",
      romance: "strong",
      comedy: "strong",
      british: "strong",
      adults: "strong",
      adults_no_children: "strong",
      kids_in_bed: "strong",
      nostalgic: "extra",
    },
  },
  {
    key: "while_you_were_sleeping",
    title: "While You Were Sleeping",
    year: 1995,
    type: "film",
    minutes: 103,
    blurb: "A lonely token collector is mistaken for a fiancée over the holidays.",
    christmas: "strong_setting",
    suitability: "8+",
    timings: ["december", "boxing_day"],
    strength: {
      secret_christmas: "essential",
      romance: "essential",
      christmas_romance: "strong",
      cosy: "essential",
      nostalgic: "strong",
      feel_good: "strong",
      adults: "strong",
      couple: "strong",
      alone: "strong",
      cosy_night: "strong",
    },
  },
  {
    key: "when_harry_met_sally",
    title: "When Harry Met Sally…",
    year: 1989,
    type: "film",
    minutes: 96,
    blurb: "Years of New Year's Eves and Christmas tree runs across New York.",
    christmas: "christmas_adjacent",
    suitability: "adult",
    timings: ["december", "any_time"],
    strength: {
      ...ADULT_BLOCK,
      secret_christmas: "essential",
      romance: "strong",
      comedy: "strong",
      classic: "strong",
      nostalgic: "strong",
      adults: "strong",
      adults_no_children: "strong",
      couple: "strong",
      kids_in_bed: "strong",
    },
  },
  {
    key: "trading_places",
    title: "Trading Places",
    year: 1983,
    type: "film",
    minutes: 116,
    blurb: "A cruel bet plays out over a very eighties New York Christmas.",
    christmas: "strong_setting",
    suitability: "adult",
    timings: ["december", "boxing_day"],
    strength: {
      ...ADULT_BLOCK,
      secret_christmas: "essential",
      comedy: "strong",
      classic: "strong",
      nostalgic: "strong",
      adults: "strong",
      adults_no_children: "strong",
      kids_in_bed: "strong",
    },
  },
  {
    key: "edward_scissorhands",
    title: "Edward Scissorhands",
    year: 1990,
    type: "film",
    minutes: 105,
    blurb: "Ice sculpture, snowfall and a fairy tale told at Christmas.",
    christmas: "christmas_adjacent",
    suitability: "12+",
    timings: ["december", "any_time"],
    strength: {
      ...TEEN_BLOCK,
      secret_christmas: "extra",
      alternative: "strong",
      emotional: "strong",
      nostalgic: "strong",
      teenagers: "strong",
      adults: "strong",
      kids_in_bed: "strong",
    },
  },
  {
    key: "bernard_and_the_genie",
    title: "Bernard and the Genie",
    year: 1991,
    type: "tv_special",
    minutes: 70,
    blurb: "A sacked art dealer, a bewildered genie and a gloriously silly London Christmas.",
    christmas: "strong_setting",
    suitability: "8+",
    timings: ["december", "christmas_eve"],
    strength: {
      secret_christmas: "essential",
      british: "essential",
      comedy: "strong",
      nostalgic: "strong",
      family: "strong",
      older_children: "strong",
      teenagers: "strong",
      adults: "strong",
      mixed_ages: "strong",
    },
  },

  /* ==================================================== family comedy */
  {
    key: "elf",
    title: "Elf",
    year: 2003,
    type: "film",
    minutes: 97,
    blurb: "A human raised at the North Pole arrives in New York at full volume.",
    christmas: "core",
    suitability: "all",
    timings: ["december", "christmas_eve", "weekend"],
    note: "The safest bet in the house — genuinely funny for every age.",
    strength: {
      comedy: "essential",
      family: "essential",
      everyone_agrees: "essential",
      mixed_ages: "essential",
      multigenerational: "essential",
      feel_good: "essential",
      classic: "essential",
      christmas_classics: "strong",
      magical: "strong",
      young_children: "strong",
      older_children: "strong",
      teenagers: "essential",
      modern_classic: "strong",
      christmas_day_afternoon: "strong",
    },
  },
  {
    key: "home_alone",
    title: "Home Alone",
    year: 1990,
    type: "film",
    minutes: 103,
    blurb: "A boy left behind defends the house with paint tins and ingenuity.",
    christmas: "core",
    suitability: "8+",
    timings: ["december", "christmas_eve", "christmas_day"],
    strength: {
      comedy: "essential",
      family: "essential",
      everyone_agrees: "essential",
      mixed_ages: "essential",
      multigenerational: "strong",
      christmas_classics: "essential",
      classic: "essential",
      nostalgic: "strong",
      older_children: "essential",
      teenagers: "essential",
      christmas_day_afternoon: "strong",
    },
  },
  {
    key: "home_alone_2",
    title: "Home Alone 2: Lost in New York",
    year: 1992,
    type: "film",
    minutes: 120,
    blurb: "Same boy, same burglars, bigger city and a very expensive hotel bill.",
    christmas: "core",
    suitability: "8+",
    timings: ["december", "christmas_eve", "boxing_day"],
    strength: {
      comedy: "essential",
      family: "essential",
      everyone_agrees: "strong",
      mixed_ages: "essential",
      multigenerational: "strong",
      christmas_classics: "essential",
      classic: "strong",
      nostalgic: "strong",
      older_children: "essential",
      teenagers: "essential",
      christmas_day_afternoon: "strong",
    },
  },
  {
    key: "daddys_home_2",
    title: "Daddy's Home 2",
    year: 2017,
    type: "film",
    minutes: 100,
    blurb: "Two dads and two grandads share one very crowded Christmas.",
    christmas: "core",
    suitability: "12+",
    timings: ["december", "boxing_day"],
    strength: {
      comedy: "essential",
      family: "strong",
      teenagers: "essential",
      adult_children: "essential",
      multigenerational: "strong",
      with_teenagers: "strong",
      with_grown_up_children: "strong",
      modern: "strong",
      young_children: "unsuitable",
    },
  },
  {
    key: "spirited",
    title: "Spirited",
    year: 2022,
    type: "film",
    minutes: 127,
    blurb: "A big musical retelling of A Christmas Carol from the ghosts' side.",
    christmas: "core",
    suitability: "12+",
    timings: ["december", "weekend"],
    strength: {
      musical: "essential",
      comedy: "strong",
      modern: "strong",
      adult_children: "essential",
      teenagers: "strong",
      with_grown_up_children: "strong",
      feel_good: "strong",
      family: "extra",
    },
  },
  {
    key: "christmas_with_the_kranks",
    title: "Christmas with the Kranks",
    year: 2004,
    type: "film",
    minutes: 99,
    blurb: "One couple try to skip Christmas and the whole street objects.",
    christmas: "core",
    suitability: "8+",
    timings: ["december"],
    strength: {
      comedy: "strong",
      family: "strong",
      mixed_ages: "strong",
      older_children: "strong",
      teenagers: "strong",
      adults: "strong",
      nostalgic: "extra",
    },
  },
  {
    key: "deck_the_halls",
    title: "Deck the Halls",
    year: 2006,
    type: "film",
    minutes: 93,
    blurb: "Two neighbours wage war over the most illuminated house in town.",
    christmas: "core",
    suitability: "8+",
    timings: ["december"],
    strength: {
      comedy: "strong",
      family: "strong",
      older_children: "strong",
      teenagers: "extra",
      mixed_ages: "extra",
    },
  },
  {
    key: "fred_claus",
    title: "Fred Claus",
    year: 2007,
    type: "film",
    minutes: 116,
    blurb: "Santa's resentful older brother turns up at the North Pole for work.",
    christmas: "core",
    suitability: "8+",
    timings: ["december"],
    strength: {
      comedy: "strong",
      family: "strong",
      magical: "strong",
      older_children: "strong",
      mixed_ages: "strong",
      teenagers: "extra",
    },
  },
  {
    key: "jingle_all_the_way",
    title: "Jingle All the Way",
    year: 1996,
    type: "film",
    minutes: 89,
    blurb: "A last-minute hunt for the one toy every child in America wants.",
    christmas: "core",
    suitability: "all",
    timings: ["december", "christmas_eve"],
    strength: {
      comedy: "strong",
      family: "strong",
      nostalgic: "strong",
      mixed_ages: "strong",
      older_children: "strong",
      young_children: "extra",
      christmas_classics: "strong",
    },
  },
  {
    key: "candy_cane_lane",
    title: "Candy Cane Lane",
    year: 2023,
    type: "film",
    minutes: 117,
    blurb: "A decorating contest goes badly wrong when an elf's deal kicks in.",
    christmas: "core",
    suitability: "8+",
    timings: ["december"],
    strength: {
      comedy: "strong",
      family: "strong",
      magical: "strong",
      modern: "strong",
      older_children: "strong",
      mixed_ages: "strong",
    },
  },
  {
    key: "surviving_christmas",
    title: "Surviving Christmas",
    year: 2004,
    type: "film",
    minutes: 91,
    blurb: "A lonely millionaire pays a family to let him have their Christmas.",
    christmas: "core",
    suitability: "12+",
    timings: ["december"],
    strength: {
      ...TEEN_BLOCK,
      comedy: "strong",
      adults: "strong",
      teenagers: "extra",
      kids_in_bed: "strong",
    },
  },
  {
    key: "ernest_saves_christmas",
    title: "Ernest Saves Christmas",
    year: 1988,
    type: "film",
    minutes: 91,
    blurb: "A daft cab driver helps Santa find his replacement in Florida.",
    christmas: "core",
    suitability: "all",
    timings: ["december"],
    strength: {
      comedy: "strong",
      family: "strong",
      nostalgic: "strong",
      young_children: "strong",
      older_children: "strong",
      mixed_ages: "extra",
    },
  },
  {
    key: "eight_bit_christmas",
    title: "8-Bit Christmas",
    year: 2021,
    type: "film",
    minutes: 97,
    blurb: "A dad explains the year he would have done anything for a games console.",
    christmas: "core",
    suitability: "8+",
    timings: ["december"],
    strength: {
      comedy: "strong",
      nostalgic: "essential",
      family: "strong",
      older_children: "strong",
      teenagers: "strong",
      mixed_ages: "strong",
      with_teenagers: "strong",
    },
  },
  {
    key: "a_christmas_story",
    title: "A Christmas Story",
    year: 1983,
    type: "film",
    minutes: 94,
    blurb: "One boy, one air rifle and the longest wait of his childhood.",
    christmas: "core",
    suitability: "8+",
    timings: ["december", "christmas_eve"],
    strength: {
      comedy: "strong",
      nostalgic: "essential",
      classic: "strong",
      christmas_classics: "strong",
      family: "strong",
      older_children: "strong",
      mixed_ages: "strong",
    },
  },
  {
    key: "a_christmas_story_christmas",
    title: "A Christmas Story Christmas",
    year: 2022,
    type: "film",
    minutes: 98,
    blurb: "Ralphie, grown up, tries to give his own children the perfect Christmas.",
    christmas: "core",
    suitability: "8+",
    timings: ["december"],
    strength: {
      comedy: "strong",
      nostalgic: "strong",
      emotional: "strong",
      family: "strong",
      older_children: "strong",
      mixed_ages: "strong",
    },
  },
  {
    key: "love_the_coopers",
    title: "Love the Coopers",
    year: 2015,
    type: "film",
    minutes: 107,
    blurb: "Four generations bring their own quiet crises to Christmas dinner.",
    christmas: "core",
    suitability: "12+",
    timings: ["december", "christmas_day"],
    strength: {
      ...TEEN_BLOCK,
      emotional: "strong",
      comedy: "strong",
      family: "strong",
      adults: "strong",
      adult_children: "strong",
      with_grown_up_children: "strong",
    },
  },
  {
    key: "dashing_through_the_snow",
    title: "Dashing Through the Snow",
    year: 2023,
    type: "film",
    minutes: 92,
    blurb: "A sceptical social worker spends Christmas Eve driving Santa around.",
    christmas: "core",
    suitability: "all",
    timings: ["christmas_eve", "december"],
    strength: {
      comedy: "strong",
      family: "strong",
      magical: "strong",
      young_children: "strong",
      older_children: "strong",
      mixed_ages: "strong",
      christmas_eve_favourites: "strong",
    },
  },
  {
    key: "noelle",
    title: "Noelle",
    year: 2019,
    type: "film",
    minutes: 100,
    blurb: "Santa's daughter goes looking for her runaway brother — and the job.",
    christmas: "core",
    suitability: "all",
    timings: ["december"],
    strength: {
      comedy: "strong",
      family: "strong",
      magical: "strong",
      feel_good: "strong",
      young_children: "strong",
      older_children: "strong",
      mixed_ages: "strong",
    },
  },
  {
    key: "nativity",
    title: "Nativity!",
    year: 2009,
    type: "film",
    minutes: 105,
    blurb: "A Coventry primary school promises Hollywood is coming to its nativity play.",
    christmas: "core",
    suitability: "all",
    timings: ["december"],
    strength: {
      british: "essential",
      family: "essential",
      comedy: "strong",
      feel_good: "essential",
      young_children: "strong",
      older_children: "essential",
      teenagers: "strong",
      mixed_ages: "essential",
      everyone_agrees: "strong",
      multigenerational: "strong",
    },
  },
  {
    key: "why_him",
    title: "Why Him?",
    year: 2016,
    type: "film",
    minutes: 111,
    blurb: "A dad spends Christmas at the house of his daughter's appalling boyfriend.",
    christmas: "strong_setting",
    suitability: "adult",
    timings: ["december"],
    strength: {
      ...ADULT_BLOCK,
      comedy: "strong",
      adult_christmas: "strong",
      adults: "strong",
      adults_no_children: "strong",
      kids_in_bed: "strong",
    },
  },

  /* ================================================ grown-up comedy */
  {
    key: "christmas_vacation",
    title: "National Lampoon's Christmas Vacation",
    year: 1989,
    type: "film",
    minutes: 97,
    blurb: "The Griswolds host Christmas and every single thing goes wrong.",
    christmas: "core",
    suitability: "12+",
    timings: ["december", "christmas_eve"],
    strength: {
      ...TEEN_BLOCK,
      comedy: "essential",
      classic: "essential",
      christmas_classics: "essential",
      nostalgic: "strong",
      adult_christmas: "strong",
      adults: "strong",
      adult_children: "strong",
      teenagers: "strong",
      with_grown_up_children: "strong",
      kids_in_bed: "strong",
    },
  },
  {
    key: "scrooged",
    title: "Scrooged",
    year: 1988,
    type: "film",
    minutes: 101,
    blurb: "A vicious TV executive gets the Dickens treatment, eighties style.",
    christmas: "core",
    suitability: "12+",
    timings: ["december"],
    strength: {
      ...TEEN_BLOCK,
      comedy: "essential",
      dark_comedy: "strong",
      adult_christmas: "strong",
      nostalgic: "strong",
      classic: "strong",
      adults: "strong",
      teenagers: "strong",
      kids_in_bed: "strong",
    },
  },
  {
    key: "the_night_before",
    title: "The Night Before",
    year: 2015,
    type: "film",
    minutes: 101,
    blurb: "Three friends chase one last riotous Christmas Eve around New York.",
    christmas: "core",
    suitability: "adult",
    timings: ["christmas_eve", "december"],
    strength: {
      ...ADULT_BLOCK,
      comedy: "essential",
      adult_christmas: "essential",
      modern: "strong",
      adults: "strong",
      adults_no_children: "strong",
      young_adults: "strong",
      kids_in_bed: "strong",
    },
  },
  {
    key: "office_christmas_party",
    title: "Office Christmas Party",
    year: 2016,
    type: "film",
    minutes: 105,
    blurb: "One branch throws the party that will definitely end the company.",
    christmas: "core",
    suitability: "adult",
    timings: ["december"],
    strength: {
      ...ADULT_BLOCK,
      comedy: "essential",
      adult_christmas: "essential",
      modern: "strong",
      adults: "strong",
      adults_no_children: "strong",
      kids_in_bed: "strong",
    },
  },
  {
    key: "bad_moms_christmas",
    title: "A Bad Moms Christmas",
    year: 2017,
    type: "film",
    minutes: 104,
    blurb: "Three mothers rebel against Christmas, then their own mothers arrive.",
    christmas: "core",
    suitability: "adult",
    timings: ["december"],
    strength: {
      ...ADULT_BLOCK,
      comedy: "essential",
      adult_christmas: "essential",
      adults: "strong",
      adults_no_children: "strong",
      kids_in_bed: "strong",
    },
  },
  {
    key: "the_ref",
    title: "The Ref",
    year: 1994,
    type: "film",
    minutes: 97,
    blurb: "A burglar takes a bickering couple hostage on Christmas Eve and regrets it.",
    christmas: "core",
    suitability: "adult",
    timings: ["christmas_eve", "december"],
    strength: {
      ...ADULT_BLOCK,
      dark_comedy: "essential",
      adult_christmas: "strong",
      alternative: "strong",
      adults: "strong",
      adults_no_children: "strong",
      kids_in_bed: "strong",
    },
  },

  /* ============================================ magical & children's */
  {
    key: "arthur_christmas",
    title: "Arthur Christmas",
    year: 2011,
    type: "film",
    minutes: 97,
    blurb: "The Santa family runs a high-tech operation — and one child is missed.",
    christmas: "core",
    suitability: "all",
    timings: ["december", "christmas_eve"],
    strength: {
      magical: "essential",
      animation: "essential",
      family: "essential",
      young_children: "essential",
      british: "strong",
      older_children: "essential",
      mixed_ages: "essential",
      everyone_agrees: "strong",
      feel_good: "strong",
      christmas_eve_favourites: "strong",
    },
  },
  {
    key: "polar_express",
    title: "The Polar Express",
    year: 2004,
    type: "film",
    minutes: 100,
    blurb: "A midnight train carries doubting children to the North Pole.",
    christmas: "core",
    suitability: "all",
    timings: ["christmas_eve", "december"],
    strength: {
      magical: "essential",
      young_children: "essential",
      christmas_eve_favourites: "essential",
      animation: "strong",
      family: "essential",
      cosy: "strong",
      older_children: "strong",
      mixed_ages: "strong",
    },
  },
  {
    key: "klaus",
    title: "Klaus",
    year: 2019,
    type: "film",
    minutes: 96,
    blurb: "A hopeless postman and a reclusive toymaker invent a whole tradition.",
    christmas: "core",
    suitability: "all",
    timings: ["december", "christmas_eve"],
    strength: {
      animation: "essential",
      family: "essential",
      magical: "essential",
      emotional: "strong",
      feel_good: "essential",
      young_children: "essential",
      older_children: "essential",
      teenagers: "strong",
      mixed_ages: "essential",
      everyone_agrees: "strong",
      modern_classic: "strong",
    },
  },
  {
    key: "the_muppet_christmas_carol",
    title: "The Muppet Christmas Carol",
    year: 1992,
    type: "film",
    minutes: 85,
    blurb: "Dickens, with Gonzo narrating and songs you will hum until January.",
    christmas: "core",
    suitability: "all",
    timings: ["december", "christmas_eve"],
    strength: {
      family: "essential",
      musical: "essential",
      classic: "essential",
      christmas_classics: "essential",
      comedy: "strong",
      young_children: "essential",
      older_children: "essential",
      teenagers: "strong",
      mixed_ages: "essential",
      multigenerational: "essential",
      everyone_agrees: "essential",
      nostalgic: "strong",
    },
  },
  {
    key: "the_santa_clause",
    title: "The Santa Clause",
    year: 1994,
    type: "film",
    minutes: 97,
    blurb: "A man accidentally becomes Santa and slowly, alarmingly, looks the part.",
    christmas: "core",
    suitability: "all",
    timings: ["december", "christmas_eve"],
    strength: {
      family: "essential",
      classic: "essential",
      christmas_classics: "essential",
      magical: "strong",
      comedy: "strong",
      nostalgic: "strong",
      young_children: "strong",
      older_children: "essential",
      teenagers: "strong",
      mixed_ages: "essential",
    },
  },
  {
    key: "the_santa_clause_2",
    title: "The Santa Clause 2",
    year: 2002,
    type: "film",
    minutes: 104,
    blurb: "Santa must find a wife before Christmas Eve, and a toy double covers for him.",
    christmas: "core",
    suitability: "all",
    timings: ["december"],
    strength: {
      family: "strong",
      magical: "strong",
      comedy: "strong",
      young_children: "strong",
      older_children: "strong",
      mixed_ages: "strong",
    },
  },
  {
    key: "the_christmas_chronicles",
    title: "The Christmas Chronicles",
    year: 2018,
    type: "film",
    minutes: 104,
    blurb: "Two children stow away in Santa's sleigh and crash the whole night.",
    christmas: "core",
    suitability: "8+",
    timings: ["christmas_eve", "december"],
    strength: {
      family: "essential",
      magical: "essential",
      adventure: "strong",
      older_children: "essential",
      teenagers: "strong",
      mixed_ages: "essential",
      christmas_eve_favourites: "strong",
      modern_classic: "strong",
    },
  },
  {
    key: "the_christmas_chronicles_2",
    title: "The Christmas Chronicles 2",
    year: 2020,
    type: "film",
    minutes: 112,
    blurb: "A bitter former elf tries to cancel Christmas at the North Pole.",
    christmas: "core",
    suitability: "8+",
    timings: ["december"],
    strength: {
      family: "strong",
      magical: "strong",
      older_children: "strong",
      teenagers: "strong",
      mixed_ages: "strong",
    },
  },
  {
    key: "a_boy_called_christmas",
    title: "A Boy Called Christmas",
    year: 2021,
    type: "film",
    minutes: 106,
    blurb: "A boy walks north with a mouse and a reindeer to find the elves.",
    christmas: "core",
    suitability: "8+",
    timings: ["december"],
    strength: {
      magical: "strong",
      family: "strong",
      british: "strong",
      adventure: "strong",
      older_children: "strong",
      mixed_ages: "strong",
    },
  },
  {
    key: "santa_claus_the_movie",
    title: "Santa Claus: The Movie",
    year: 1985,
    type: "film",
    minutes: 107,
    blurb: "The origin story of Father Christmas, complete with an eighties villain.",
    christmas: "core",
    suitability: "all",
    timings: ["december"],
    strength: {
      magical: "strong",
      family: "strong",
      nostalgic: "essential",
      young_children: "strong",
      older_children: "strong",
      mixed_ages: "strong",
      christmas_classics: "strong",
    },
  },
  {
    key: "prancer",
    title: "Prancer",
    year: 1989,
    type: "film",
    minutes: 103,
    blurb: "A farm girl nurses an injured reindeer and refuses to stop believing.",
    christmas: "core",
    suitability: "all",
    timings: ["december"],
    strength: {
      magical: "strong",
      family: "strong",
      emotional: "strong",
      nostalgic: "strong",
      young_children: "strong",
      older_children: "strong",
    },
  },
  {
    key: "jack_frost",
    title: "Jack Frost",
    year: 1998,
    type: "film",
    minutes: 101,
    blurb: "A boy's father returns as a snowman for one more winter together.",
    christmas: "core",
    suitability: "8+",
    timings: ["december"],
    strength: {
      emotional: "strong",
      family: "strong",
      magical: "strong",
      older_children: "strong",
      mixed_ages: "extra",
    },
  },
  {
    key: "jingle_jangle",
    title: "Jingle Jangle: A Christmas Journey",
    year: 2020,
    type: "film",
    minutes: 122,
    blurb: "A heartbroken toymaker's granddaughter brings the invention back to life.",
    christmas: "core",
    suitability: "all",
    timings: ["december"],
    strength: {
      musical: "essential",
      magical: "strong",
      family: "essential",
      young_children: "strong",
      older_children: "essential",
      mixed_ages: "strong",
      feel_good: "strong",
    },
  },
  {
    key: "the_nutcracker_and_the_four_realms",
    title: "The Nutcracker and the Four Realms",
    year: 2018,
    type: "film",
    minutes: 99,
    blurb: "A Christmas Eve gift opens a door into four strange realms.",
    christmas: "core",
    suitability: "8+",
    timings: ["december", "christmas_eve"],
    strength: {
      magical: "strong",
      family: "strong",
      adventure: "strong",
      older_children: "strong",
      mixed_ages: "extra",
    },
  },
  {
    key: "the_star",
    title: "The Star",
    year: 2017,
    type: "film",
    minutes: 86,
    blurb: "The nativity told by the stable animals, gently and with jokes.",
    christmas: "core",
    suitability: "all",
    timings: ["december"],
    strength: {
      animation: "strong",
      family: "strong",
      young_children: "essential",
      older_children: "strong",
      mixed_ages: "strong",
    },
  },
  {
    key: "the_grinch_2018",
    title: "The Grinch",
    year: 2018,
    type: "film",
    minutes: 85,
    blurb: "A softer, brighter Grinch for the smallest members of the household.",
    christmas: "core",
    suitability: "all",
    timings: ["december"],
    strength: {
      animation: "essential",
      family: "essential",
      young_children: "essential",
      older_children: "strong",
      mixed_ages: "strong",
      comedy: "strong",
      feel_good: "strong",
    },
  },
  {
    key: "grinch_2000",
    title: "How the Grinch Stole Christmas",
    year: 2000,
    type: "film",
    minutes: 104,
    blurb: "Whoville at full throttle, with a green, gleefully rude Jim Carrey.",
    christmas: "core",
    suitability: "8+",
    timings: ["december"],
    strength: {
      family: "essential",
      comedy: "strong",
      classic: "essential",
      christmas_classics: "strong",
      nostalgic: "strong",
      older_children: "essential",
      teenagers: "strong",
      mixed_ages: "essential",
    },
  },
  {
    key: "grinch_1966",
    title: "How the Grinch Stole Christmas!",
    year: 1966,
    type: "tv_special",
    minutes: 26,
    blurb: "The original half-hour cartoon, still the sharpest version of the story.",
    christmas: "core",
    suitability: "all",
    timings: ["december", "christmas_eve"],
    strength: {
      animation: "essential",
      classic: "essential",
      christmas_classics: "strong",
      nostalgic: "strong",
      young_children: "essential",
      family: "strong",
      mixed_ages: "strong",
    },
  },
  {
    key: "mickeys_christmas_carol",
    title: "Mickey's Christmas Carol",
    year: 1983,
    type: "tv_special",
    minutes: 26,
    blurb: "Scrooge McDuck leads a perfect half-hour Dickens for small children.",
    christmas: "core",
    suitability: "all",
    timings: ["december"],
    strength: {
      animation: "essential",
      young_children: "essential",
      family: "strong",
      nostalgic: "strong",
      mixed_ages: "extra",
    },
  },
  {
    key: "mickeys_once_upon_a_christmas",
    title: "Mickey's Once Upon a Christmas",
    year: 1999,
    type: "film",
    minutes: 68,
    blurb: "Three short Christmas stories with the whole Disney gang.",
    christmas: "core",
    suitability: "all",
    timings: ["december"],
    strength: {
      animation: "strong",
      young_children: "essential",
      family: "strong",
    },
  },
  {
    key: "mickeys_twice_upon_a_christmas",
    title: "Mickey's Twice Upon a Christmas",
    year: 2004,
    type: "film",
    minutes: 68,
    blurb: "Five more festive shorts, easy viewing for the very youngest.",
    christmas: "core",
    suitability: "all",
    timings: ["december"],
    strength: {
      animation: "strong",
      young_children: "essential",
      family: "strong",
    },
  },
  {
    key: "olafs_frozen_adventure",
    title: "Olaf's Frozen Adventure",
    year: 2017,
    type: "tv_special",
    minutes: 21,
    blurb: "Olaf goes looking for a family tradition to bring home to Arendelle.",
    christmas: "core",
    suitability: "all",
    timings: ["december"],
    strength: {
      animation: "strong",
      musical: "strong",
      young_children: "essential",
      family: "strong",
    },
  },
  {
    key: "prep_and_landing",
    title: "Prep & Landing",
    year: 2009,
    type: "tv_special",
    minutes: 22,
    blurb: "Elite elves prepare houses on Christmas Eve like a covert operation.",
    christmas: "core",
    suitability: "all",
    timings: ["christmas_eve", "december"],
    strength: {
      animation: "strong",
      young_children: "essential",
      family: "strong",
      christmas_eve_favourites: "strong",
      comedy: "extra",
    },
  },
  {
    key: "alien_xmas",
    title: "Alien Xmas",
    year: 2020,
    type: "tv_special",
    minutes: 42,
    blurb: "A tiny alien sent to steal Earth's gravity discovers Christmas instead.",
    christmas: "core",
    suitability: "all",
    timings: ["december"],
    strength: {
      animation: "strong",
      young_children: "strong",
      family: "extra",
    },
  },
  {
    key: "angelas_christmas",
    title: "Angela's Christmas",
    year: 2017,
    type: "tv_special",
    minutes: 30,
    blurb: "A little girl in old Limerick decides the baby Jesus looks cold.",
    christmas: "core",
    suitability: "all",
    timings: ["december"],
    strength: {
      animation: "strong",
      young_children: "essential",
      family: "strong",
      emotional: "extra",
    },
  },
  {
    key: "angelas_christmas_wish",
    title: "Angela's Christmas Wish",
    year: 2020,
    type: "tv_special",
    blurb: "Angela sets out to bring her father home from Australia for Christmas.",
    christmas: "core",
    suitability: "all",
    timings: ["december"],
    strength: {
      animation: "strong",
      young_children: "essential",
      family: "strong",
      emotional: "extra",
    },
  },
  {
    key: "the_best_christmas_pageant_ever",
    title: "The Best Christmas Pageant Ever",
    year: 2024,
    type: "film",
    minutes: 99,
    blurb: "The worst-behaved children in town take over the church nativity.",
    christmas: "core",
    suitability: "all",
    timings: ["december"],
    strength: {
      family: "strong",
      emotional: "strong",
      feel_good: "strong",
      older_children: "strong",
      mixed_ages: "strong",
    },
  },
  {
    key: "that_christmas",
    title: "That Christmas",
    year: 2024,
    type: "film",
    minutes: 91,
    blurb: "A snowed-in English seaside town, several tangled families and one late Santa.",
    christmas: "core",
    suitability: "all",
    timings: ["december"],
    strength: {
      animation: "strong",
      british: "strong",
      family: "strong",
      young_children: "strong",
      older_children: "strong",
      mixed_ages: "strong",
      feel_good: "strong",
    },
  },

  /* ============================================= British animated shorts */
  {
    key: "the_snowman",
    title: "The Snowman",
    year: 1982,
    type: "tv_special",
    minutes: 26,
    blurb: "No dialogue, one flight over the sea, and the whole of childhood.",
    christmas: "core",
    suitability: "all",
    timings: ["december", "christmas_eve"],
    note: "Half an hour, no words, and still the most Christmassy thing on television.",
    strength: {
      british: "essential",
      animation: "essential",
      young_children: "essential",
      classic: "essential",
      christmas_classics: "essential",
      nostalgic: "essential",
      family: "essential",
      mixed_ages: "strong",
      multigenerational: "strong",
      emotional: "strong",
      christmas_eve_favourites: "strong",
    },
  },
  {
    key: "the_snowman_and_the_snowdog",
    title: "The Snowman and the Snowdog",
    year: 2012,
    type: "tv_special",
    minutes: 24,
    blurb: "A new boy, a new snowman and a small snow dog to go with him.",
    christmas: "core",
    suitability: "all",
    timings: ["december", "christmas_eve"],
    strength: {
      british: "essential",
      animation: "essential",
      young_children: "essential",
      family: "strong",
      emotional: "strong",
      mixed_ages: "extra",
    },
  },
  {
    key: "father_christmas",
    title: "Father Christmas",
    year: 1991,
    type: "tv_special",
    minutes: 26,
    blurb: "Raymond Briggs's Santa takes a summer holiday and grumbles beautifully.",
    christmas: "core",
    suitability: "all",
    timings: ["december"],
    strength: {
      british: "essential",
      animation: "essential",
      young_children: "essential",
      comedy: "strong",
      nostalgic: "strong",
      family: "strong",
    },
  },
  {
    key: "robin_robin",
    title: "Robin Robin",
    year: 2021,
    type: "tv_special",
    minutes: 32,
    blurb: "A robin raised by mice tries to work out what she actually is.",
    christmas: "core",
    suitability: "all",
    timings: ["december"],
    strength: {
      british: "strong",
      animation: "essential",
      young_children: "essential",
      musical: "extra",
      family: "strong",
    },
  },
  {
    key: "shaun_the_sheep_flight_before_christmas",
    title: "Shaun the Sheep: The Flight Before Christmas",
    year: 2021,
    type: "tv_special",
    minutes: 30,
    blurb: "A farmyard heist over a Christmas present, told entirely in bleats.",
    christmas: "core",
    suitability: "all",
    timings: ["december"],
    strength: {
      british: "strong",
      animation: "essential",
      young_children: "essential",
      comedy: "strong",
      family: "strong",
    },
  },
  {
    key: "stick_man",
    title: "Stick Man",
    year: 2015,
    type: "tv_special",
    minutes: 27,
    blurb: "A stick tries to get home to his family tree by Christmas.",
    christmas: "core",
    suitability: "all",
    timings: ["december"],
    strength: {
      british: "strong",
      animation: "essential",
      young_children: "essential",
      family: "strong",
    },
  },
  {
    key: "mogs_christmas",
    title: "Mog's Christmas",
    year: 2023,
    type: "tv_special",
    minutes: 23,
    blurb: "An anxious cat, a houseful of visitors and one very memorable tree.",
    christmas: "core",
    suitability: "all",
    timings: ["december"],
    strength: {
      british: "strong",
      animation: "essential",
      young_children: "essential",
      family: "strong",
      cosy: "strong",
    },
  },

  /* ================================================= classics & musicals */
  {
    key: "its_a_wonderful_life",
    title: "It's a Wonderful Life",
    year: 1946,
    type: "film",
    minutes: 130,
    blurb: "One man is shown what the town would be without him. Still unbeatable.",
    christmas: "core",
    suitability: "8+",
    timings: ["december", "christmas_eve"],
    strength: {
      classic: "essential",
      christmas_classics: "essential",
      emotional: "essential",
      nostalgic: "strong",
      feel_good: "strong",
      adults: "strong",
      adult_children: "strong",
      teenagers: "strong",
      multigenerational: "strong",
      cosy_night: "strong",
    },
  },
  {
    key: "miracle_34th_1947",
    title: "Miracle on 34th Street",
    year: 1947,
    type: "film",
    minutes: 96,
    blurb: "A department store Santa insists he is the real thing, and goes to court.",
    christmas: "core",
    suitability: "all",
    timings: ["december"],
    strength: {
      classic: "essential",
      christmas_classics: "essential",
      nostalgic: "essential",
      family: "strong",
      magical: "strong",
      multigenerational: "strong",
      mixed_ages: "strong",
    },
  },
  {
    key: "miracle_34th_1994",
    title: "Miracle on 34th Street",
    year: 1994,
    type: "film",
    minutes: 114,
    blurb: "The warmer remake, and the version most families grew up on.",
    christmas: "core",
    suitability: "all",
    timings: ["december"],
    strength: {
      classic: "essential",
      christmas_classics: "essential",
      family: "essential",
      magical: "strong",
      emotional: "strong",
      young_children: "strong",
      older_children: "essential",
      mixed_ages: "essential",
      multigenerational: "strong",
    },
  },
  {
    key: "white_christmas",
    title: "White Christmas",
    year: 1954,
    type: "film",
    minutes: 120,
    blurb: "Two entertainers save an old general's inn with one enormous show.",
    christmas: "core",
    suitability: "all",
    timings: ["december", "christmas_day"],
    strength: {
      musical: "essential",
      classic: "essential",
      christmas_classics: "essential",
      nostalgic: "essential",
      cosy: "strong",
      multigenerational: "essential",
      mixed_ages: "strong",
      adults: "strong",
      christmas_day_afternoon: "strong",
    },
  },
  {
    key: "holiday_inn",
    title: "Holiday Inn",
    year: 1942,
    type: "film",
    minutes: 100,
    blurb: "The inn that only opens on holidays — and where White Christmas began.",
    christmas: "strong_setting",
    suitability: "all",
    timings: ["december"],
    strength: {
      musical: "strong",
      classic: "strong",
      nostalgic: "strong",
      multigenerational: "strong",
      adults: "strong",
    },
  },
  {
    key: "meet_me_in_st_louis",
    title: "Meet Me in St. Louis",
    year: 1944,
    type: "film",
    minutes: 113,
    blurb: "A year in one family's life, and the first Have Yourself a Merry Little Christmas.",
    christmas: "christmas_adjacent",
    suitability: "all",
    timings: ["december", "any_time"],
    strength: {
      musical: "strong",
      classic: "strong",
      nostalgic: "strong",
      secret_christmas: "extra",
      multigenerational: "strong",
      adults: "strong",
    },
  },
  {
    key: "the_bishops_wife",
    title: "The Bishop's Wife",
    year: 1947,
    type: "film",
    minutes: 109,
    blurb: "An angel arrives to help a distracted bishop and charms everyone else.",
    christmas: "core",
    suitability: "all",
    timings: ["december"],
    strength: {
      classic: "strong",
      romance: "strong",
      nostalgic: "strong",
      cosy: "strong",
      adults: "strong",
      multigenerational: "extra",
    },
  },
  {
    key: "a_charlie_brown_christmas",
    title: "A Charlie Brown Christmas",
    year: 1965,
    type: "tv_special",
    minutes: 25,
    blurb: "A sad little tree, a jazz piano and the quietest Christmas half-hour there is.",
    christmas: "core",
    suitability: "all",
    timings: ["december"],
    strength: {
      animation: "essential",
      classic: "essential",
      nostalgic: "essential",
      young_children: "strong",
      family: "strong",
      cosy: "strong",
    },
  },
  {
    key: "scrooge_1951",
    title: "Scrooge",
    year: 1951,
    type: "film",
    minutes: 86,
    blurb: "Alastair Sim's Scrooge, still the definitive screen Dickens.",
    christmas: "core",
    suitability: "8+",
    timings: ["december", "christmas_eve"],
    strength: {
      classic: "essential",
      christmas_classics: "essential",
      british: "strong",
      nostalgic: "strong",
      adults: "strong",
      multigenerational: "strong",
    },
  },
  {
    key: "scrooge_1970",
    title: "Scrooge",
    year: 1970,
    type: "film",
    minutes: 113,
    blurb: "The full musical Carol, with Albert Finney singing his way to redemption.",
    christmas: "core",
    suitability: "all",
    timings: ["december"],
    strength: {
      musical: "essential",
      classic: "strong",
      british: "strong",
      nostalgic: "strong",
      family: "strong",
      multigenerational: "strong",
    },
  },
  {
    key: "christmas_carol_1984",
    title: "A Christmas Carol",
    year: 1984,
    type: "film",
    minutes: 100,
    blurb: "George C. Scott's sterner Scrooge, filmed in a properly cold Shrewsbury.",
    christmas: "core",
    suitability: "8+",
    timings: ["december"],
    strength: {
      classic: "strong",
      british: "extra",
      nostalgic: "strong",
      adults: "strong",
      older_children: "extra",
    },
  },
  {
    key: "scrooge_a_christmas_carol_2022",
    title: "Scrooge: A Christmas Carol",
    year: 2022,
    type: "film",
    minutes: 96,
    blurb: "An animated musical Carol for households with younger children.",
    christmas: "core",
    suitability: "all",
    timings: ["december"],
    strength: {
      animation: "strong",
      musical: "strong",
      family: "strong",
      young_children: "strong",
      older_children: "strong",
    },
  },
  {
    key: "the_man_who_invented_christmas",
    title: "The Man Who Invented Christmas",
    year: 2017,
    type: "film",
    minutes: 104,
    blurb: "Dickens, broke and desperate, writes A Christmas Carol in six weeks.",
    christmas: "core",
    suitability: "8+",
    timings: ["december"],
    strength: {
      british: "strong",
      classic: "extra",
      cosy: "strong",
      adults: "strong",
      teenagers: "extra",
      cosy_night: "strong",
    },
  },
  {
    key: "let_it_snow",
    title: "Let It Snow",
    year: 2019,
    type: "film",
    minutes: 92,
    blurb: "A snowstorm strands a group of teenagers together on Christmas Eve.",
    christmas: "core",
    suitability: "12+",
    timings: ["christmas_eve", "december"],
    strength: {
      ...TEEN_BLOCK,
      romance: "strong",
      teenagers: "essential",
      with_teenagers: "strong",
      modern: "strong",
      young_adults: "strong",
    },
  },

  /* ================================= not your usual Christmas / darker */
  {
    key: "die_hard",
    title: "Die Hard",
    year: 1988,
    type: "film",
    minutes: 132,
    blurb: "One office Christmas party, one tower, one very bad night.",
    christmas: "strong_setting",
    suitability: "adult",
    timings: ["december", "christmas_eve"],
    note: "The argument that never ends — and it is a Christmas film.",
    strength: {
      ...ADULT_BLOCK,
      action: "essential",
      not_your_usual_christmas: "essential",
      secret_christmas: "essential",
      classic: "strong",
      alternative: "strong",
      adults: "strong",
      adults_no_children: "strong",
      kids_in_bed: "strong",
    },
  },
  {
    key: "violent_night",
    title: "Violent Night",
    year: 2022,
    type: "film",
    minutes: 112,
    blurb: "Father Christmas takes on a siege at a very wealthy family's house.",
    christmas: "core",
    suitability: "adult",
    timings: ["december"],
    strength: {
      ...ADULT_BLOCK,
      action: "essential",
      adult_christmas: "essential",
      not_your_usual_christmas: "essential",
      dark_comedy: "strong",
      alternative: "strong",
      adults: "strong",
      adults_no_children: "strong",
      kids_in_bed: "strong",
      modern: "strong",
    },
  },
  {
    key: "bad_santa",
    title: "Bad Santa",
    year: 2003,
    type: "film",
    minutes: 91,
    blurb: "A hopeless mall Santa runs a Christmas Eve heist he barely survives.",
    christmas: "core",
    suitability: "adult",
    timings: ["december"],
    strength: {
      ...ADULT_BLOCK,
      dark_comedy: "essential",
      adult_christmas: "essential",
      not_your_usual_christmas: "essential",
      alternative: "strong",
      adults: "strong",
      adults_no_children: "strong",
      kids_in_bed: "strong",
      comedy: "strong",
    },
  },
  {
    key: "bad_santa_2",
    title: "Bad Santa 2",
    year: 2016,
    type: "film",
    minutes: 92,
    blurb: "The same appalling Santa, this time working with his mother.",
    christmas: "core",
    suitability: "adult",
    timings: ["december"],
    strength: {
      ...ADULT_BLOCK,
      dark_comedy: "strong",
      adult_christmas: "strong",
      not_your_usual_christmas: "extra",
      adults: "strong",
      adults_no_children: "strong",
      kids_in_bed: "strong",
    },
  },
  {
    key: "gremlins",
    title: "Gremlins",
    year: 1984,
    type: "film",
    minutes: 106,
    blurb: "A Christmas present with three rules, and a town that breaks all of them.",
    christmas: "strong_setting",
    suitability: "12+",
    timings: ["december"],
    strength: {
      ...TEEN_BLOCK,
      alternative: "essential",
      not_your_usual_christmas: "essential",
      dark_comedy: "strong",
      nostalgic: "strong",
      classic: "strong",
      teenagers: "essential",
      adult_children: "strong",
      with_teenagers: "strong",
      adults: "strong",
      kids_in_bed: "strong",
    },
  },
  {
    key: "the_nightmare_before_christmas",
    title: "The Nightmare Before Christmas",
    year: 1993,
    type: "film",
    minutes: 76,
    blurb: "Halloween Town hijacks Christmas, with songs nobody ever forgets.",
    christmas: "core",
    suitability: "8+",
    timings: ["december", "any_time"],
    strength: {
      musical: "essential",
      alternative: "essential",
      not_your_usual_christmas: "essential",
      animation: "strong",
      nostalgic: "strong",
      older_children: "strong",
      teenagers: "essential",
      with_teenagers: "strong",
      adults: "strong",
      modern_classic: "strong",
    },
  },
  {
    key: "krampus",
    title: "Krampus",
    year: 2015,
    type: "film",
    minutes: 98,
    blurb: "A family loses its Christmas spirit and something much older notices.",
    christmas: "core",
    suitability: "adult",
    timings: ["december"],
    strength: {
      ...ADULT_BLOCK,
      horror: "essential",
      not_your_usual_christmas: "essential",
      dark_comedy: "strong",
      alternative: "strong",
      adults: "strong",
      adults_no_children: "strong",
      kids_in_bed: "strong",
    },
  },
  {
    key: "anna_and_the_apocalypse",
    title: "Anna and the Apocalypse",
    year: 2017,
    type: "film",
    minutes: 93,
    blurb: "A Scottish school Christmas show, interrupted by zombies, sung throughout.",
    christmas: "core",
    suitability: "adult",
    timings: ["december"],
    strength: {
      ...ADULT_BLOCK,
      musical: "essential",
      not_your_usual_christmas: "essential",
      horror: "strong",
      alternative: "strong",
      british: "strong",
      adults: "strong",
      young_adults: "strong",
      kids_in_bed: "strong",
    },
  },
  {
    key: "rare_exports",
    title: "Rare Exports: A Christmas Tale",
    year: 2010,
    type: "film",
    minutes: 84,
    blurb: "Finnish miners dig up the original, far less friendly Father Christmas.",
    christmas: "core",
    suitability: "adult",
    timings: ["december"],
    strength: {
      ...ADULT_BLOCK,
      horror: "strong",
      alternative: "essential",
      not_your_usual_christmas: "essential",
      adults: "strong",
      adults_no_children: "strong",
      kids_in_bed: "strong",
    },
  },
  {
    key: "fatman",
    title: "Fatman",
    year: 2020,
    type: "film",
    minutes: 100,
    blurb: "A spoilt child hires a hitman to kill a very disillusioned Santa.",
    christmas: "core",
    suitability: "adult",
    timings: ["december"],
    strength: {
      ...ADULT_BLOCK,
      action: "strong",
      dark_comedy: "strong",
      alternative: "strong",
      adults: "strong",
      kids_in_bed: "strong",
    },
  },
  {
    key: "better_watch_out",
    title: "Better Watch Out",
    year: 2016,
    type: "film",
    minutes: 89,
    blurb: "A babysitting job on a snowy night turns very nasty indeed.",
    christmas: "core",
    suitability: "adult",
    timings: ["december"],
    strength: {
      ...ADULT_BLOCK,
      horror: "essential",
      alternative: "strong",
      adults: "strong",
      adults_no_children: "strong",
      kids_in_bed: "strong",
    },
  },
  {
    key: "black_christmas_1974",
    title: "Black Christmas",
    year: 1974,
    type: "film",
    minutes: 98,
    blurb: "The sorority house slasher that started the whole genre, set at Christmas.",
    christmas: "strong_setting",
    suitability: "adult",
    timings: ["december"],
    strength: {
      ...ADULT_BLOCK,
      horror: "essential",
      classic: "strong",
      alternative: "strong",
      adults: "strong",
      adults_no_children: "strong",
      kids_in_bed: "strong",
    },
  },
  {
    key: "christmas_bloody_christmas",
    title: "Christmas Bloody Christmas",
    year: 2022,
    type: "film",
    minutes: 87,
    blurb: "A robot Santa goes wrong in a toy shop. Loud, grimy, not for the family sofa.",
    christmas: "core",
    suitability: "adult",
    timings: ["december"],
    strength: {
      ...ADULT_BLOCK,
      horror: "strong",
      alternative: "strong",
      adults: "strong",
      adults_no_children: "strong",
      kids_in_bed: "strong",
    },
  },

  /* ================================================= British Christmas TV */
  {
    key: "blackadders_christmas_carol",
    title: "Blackadder's Christmas Carol",
    year: 1988,
    type: "tv_special",
    minutes: 43,
    blurb: "The Carol in reverse: the kindest man in England is talked into being vile.",
    christmas: "core",
    suitability: "12+",
    timings: ["december", "christmas_day"],
    strength: {
      ...TEEN_BLOCK,
      british: "essential",
      comedy: "essential",
      nostalgic: "strong",
      classic: "strong",
      adults: "strong",
      adult_children: "strong",
      teenagers: "strong",
      with_grown_up_children: "strong",
      christmas_day_afternoon: "strong",
    },
  },
  {
    key: "gavin_stacey_2008",
    title: "Gavin & Stacey Christmas Special",
    year: 2008,
    type: "episode",
    minutes: 30,
    blurb: "Barry and Billericay do Christmas, with Nessa on top form.",
    christmas: "core",
    suitability: "12+",
    timings: ["december", "christmas_day"],
    strength: {
      ...TEEN_BLOCK,
      british: "essential",
      comedy: "essential",
      cosy: "strong",
      adults: "strong",
      adult_children: "strong",
      with_grown_up_children: "strong",
    },
  },
  {
    key: "gavin_stacey_2019",
    title: "Gavin & Stacey Christmas Special",
    year: 2019,
    type: "episode",
    minutes: 60,
    blurb: "The comeback special, and that cliffhanger everyone argued about.",
    christmas: "core",
    suitability: "12+",
    timings: ["christmas_day", "december"],
    strength: {
      ...TEEN_BLOCK,
      british: "essential",
      comedy: "essential",
      cosy: "strong",
      adults: "strong",
      adult_children: "strong",
      with_grown_up_children: "strong",
      christmas_day_afternoon: "strong",
    },
  },
  {
    key: "gavin_stacey_finale_2024",
    title: "Gavin & Stacey: The Finale",
    year: 2024,
    type: "episode",
    minutes: 90,
    blurb: "The last one — a wedding, a reckoning and the whole nation watching.",
    christmas: "core",
    suitability: "12+",
    timings: ["christmas_day", "december"],
    strength: {
      ...TEEN_BLOCK,
      british: "essential",
      comedy: "essential",
      emotional: "strong",
      adults: "strong",
      adult_children: "strong",
      with_grown_up_children: "strong",
      christmas_day_afternoon: "strong",
    },
  },
  {
    key: "motherland_last_christmas",
    title: "Motherland: Last Christmas",
    year: 2022,
    type: "episode",
    minutes: 30,
    blurb: "School-gate parenting at its most brutal, with a Christmas fair to survive.",
    christmas: "core",
    suitability: "12+",
    timings: ["december"],
    strength: {
      ...TEEN_BLOCK,
      british: "essential",
      comedy: "essential",
      dark_comedy: "strong",
      adults: "strong",
      adults_no_children: "extra",
      kids_in_bed: "strong",
    },
  },
  {
    key: "dibley_christmas_lunch_incident",
    title: "The Vicar of Dibley: The Christmas Lunch Incident",
    year: 1996,
    type: "episode",
    minutes: 35,
    blurb: "Three Christmas dinners in one afternoon, all of them eaten.",
    christmas: "core",
    suitability: "12+",
    timings: ["december", "christmas_day"],
    strength: {
      british: "essential",
      comedy: "essential",
      nostalgic: "strong",
      cosy: "strong",
      adults: "strong",
      adult_children: "strong",
      multigenerational: "strong",
      christmas_day_afternoon: "strong",
    },
  },
  {
    key: "dibley_winter",
    title: "The Vicar of Dibley: Winter",
    year: 1999,
    type: "episode",
    minutes: 35,
    blurb: "Dibley in the snow, with the parish council in fine form.",
    christmas: "core",
    suitability: "12+",
    timings: ["december"],
    strength: {
      british: "strong",
      comedy: "strong",
      cosy: "strong",
      adults: "strong",
      multigenerational: "extra",
    },
  },
  {
    key: "dibley_merry_christmas",
    title: "The Vicar of Dibley: Merry Christmas",
    year: 2004,
    type: "episode",
    minutes: 30,
    blurb: "Geraldine faces another village Christmas and a very full diary.",
    christmas: "core",
    suitability: "12+",
    timings: ["december"],
    strength: {
      british: "strong",
      comedy: "strong",
      cosy: "strong",
      adults: "strong",
    },
  },
  {
    key: "dibley_handsome_stranger",
    title: "The Vicar of Dibley: The Handsome Stranger",
    year: 2006,
    type: "episode",
    minutes: 40,
    blurb: "A new arrival in the village and the beginning of Geraldine's happy ending.",
    christmas: "core",
    suitability: "12+",
    timings: ["december"],
    strength: {
      british: "strong",
      comedy: "strong",
      romance: "strong",
      cosy: "strong",
      adults: "strong",
    },
  },
  {
    key: "ofah_jolly_boys_outing",
    title: "Only Fools and Horses: The Jolly Boys' Outing",
    year: 1989,
    type: "episode",
    minutes: 75,
    blurb: "The Margate coach trip — a Christmas special with nothing festive in it.",
    christmas: "strong_setting",
    suitability: "12+",
    timings: ["december", "boxing_day"],
    strength: {
      british: "essential",
      comedy: "essential",
      nostalgic: "strong",
      classic: "strong",
      adults: "strong",
      adult_children: "strong",
      multigenerational: "strong",
    },
  },
  {
    key: "ofah_heroes_and_villains",
    title: "Only Fools and Horses: Heroes and Villains",
    year: 1996,
    type: "episode",
    minutes: 60,
    blurb: "Batman and Robin run down a Peckham street. Christmas television, perfected.",
    christmas: "strong_setting",
    suitability: "12+",
    timings: ["christmas_day", "december"],
    strength: {
      british: "essential",
      comedy: "essential",
      nostalgic: "essential",
      classic: "strong",
      adults: "strong",
      adult_children: "strong",
      multigenerational: "strong",
      christmas_day_afternoon: "strong",
    },
  },
  {
    key: "ofah_time_on_our_hands",
    title: "Only Fools and Horses: Time on Our Hands",
    year: 1996,
    type: "episode",
    minutes: 60,
    blurb: "The one where they finally become millionaires, and everybody cried.",
    christmas: "strong_setting",
    suitability: "12+",
    timings: ["christmas_day", "december"],
    strength: {
      british: "essential",
      comedy: "essential",
      emotional: "strong",
      nostalgic: "essential",
      adults: "strong",
      adult_children: "strong",
      multigenerational: "strong",
      christmas_day_afternoon: "strong",
    },
  },
  {
    key: "royle_family_new_sofa",
    title: "The Royle Family: The New Sofa",
    year: 2008,
    type: "episode",
    minutes: 60,
    blurb: "A whole Christmas spent on one settee, and somehow perfect.",
    christmas: "core",
    suitability: "12+",
    timings: ["christmas_day", "december"],
    strength: {
      ...TEEN_BLOCK,
      british: "essential",
      comedy: "essential",
      cosy: "strong",
      emotional: "strong",
      adults: "strong",
      adult_children: "strong",
      christmas_day_afternoon: "strong",
    },
  },
  {
    key: "royle_family_joes_crackers",
    title: "The Royle Family: Joe's Crackers",
    year: 2010,
    type: "episode",
    minutes: 60,
    blurb: "Christmas at Joe's, with all the usual complaining and real affection.",
    christmas: "core",
    suitability: "12+",
    timings: ["december", "christmas_day"],
    strength: {
      ...TEEN_BLOCK,
      british: "strong",
      comedy: "strong",
      cosy: "strong",
      adults: "strong",
      adult_children: "strong",
    },
  },
  {
    key: "the_office_christmas_part_1",
    title: "The Office Christmas Special — Part 1",
    year: 2003,
    type: "episode",
    minutes: 45,
    blurb: "Three years on, Brent is doing the club circuit and Tim is still waiting.",
    christmas: "core",
    suitability: "adult",
    timings: ["december"],
    strength: {
      ...ADULT_BLOCK,
      british: "essential",
      comedy: "essential",
      emotional: "strong",
      adults: "strong",
      kids_in_bed: "strong",
    },
  },
  {
    key: "the_office_christmas_part_2",
    title: "The Office Christmas Special — Part 2",
    year: 2003,
    type: "episode",
    minutes: 45,
    blurb: "The party, the card, and one of the best endings British comedy has managed.",
    christmas: "core",
    suitability: "adult",
    timings: ["december"],
    strength: {
      ...ADULT_BLOCK,
      british: "essential",
      comedy: "essential",
      emotional: "essential",
      adults: "strong",
      kids_in_bed: "strong",
    },
  },
  {
    key: "extras_christmas_special",
    title: "Extras Christmas Special",
    year: 2007,
    type: "episode",
    minutes: 85,
    blurb: "Fame, celebrity and a very bleak, very funny reckoning.",
    christmas: "core",
    suitability: "adult",
    timings: ["december"],
    strength: {
      ...ADULT_BLOCK,
      british: "strong",
      comedy: "strong",
      dark_comedy: "strong",
      emotional: "strong",
      adults: "strong",
      kids_in_bed: "strong",
    },
  },
  {
    key: "detectorists_christmas_special",
    title: "Detectorists Christmas Special",
    year: 2022,
    type: "episode",
    minutes: 75,
    blurb: "Two men, a field and the gentlest hour of television you will find.",
    christmas: "core",
    suitability: "12+",
    timings: ["december"],
    strength: {
      british: "strong",
      comedy: "strong",
      cosy: "essential",
      emotional: "strong",
      adults: "strong",
      cosy_night: "strong",
    },
  },
  {
    key: "ghosts_ghost_of_christmas",
    title: "Ghosts: The Ghost of Christmas",
    year: 2020,
    type: "episode",
    minutes: 30,
    blurb: "Button House at Christmas, with several centuries of opinions about it.",
    christmas: "core",
    suitability: "8+",
    timings: ["december"],
    strength: {
      british: "essential",
      comedy: "essential",
      family: "strong",
      older_children: "strong",
      teenagers: "strong",
      adults: "strong",
      mixed_ages: "strong",
      with_teenagers: "strong",
    },
  },
  {
    key: "ghosts_he_came",
    title: "Ghosts: He Came!",
    year: 2021,
    type: "episode",
    minutes: 30,
    blurb: "A ghostly Christmas Eve, and Robin's long wait for Father Christmas.",
    christmas: "core",
    suitability: "8+",
    timings: ["christmas_eve", "december"],
    strength: {
      british: "strong",
      comedy: "strong",
      family: "strong",
      older_children: "strong",
      teenagers: "strong",
      mixed_ages: "strong",
    },
  },
  {
    key: "ghosts_its_behind_you",
    title: "Ghosts: It's Behind You",
    year: 2022,
    type: "episode",
    minutes: 30,
    blurb: "The ghosts put on a pantomime, with predictable results.",
    christmas: "core",
    suitability: "8+",
    timings: ["december"],
    strength: {
      british: "strong",
      comedy: "strong",
      family: "strong",
      older_children: "strong",
      teenagers: "strong",
      mixed_ages: "strong",
    },
  },
  {
    key: "ghosts_a_christmas_gift",
    title: "Ghosts: A Christmas Gift",
    year: 2023,
    type: "episode",
    minutes: 30,
    blurb: "The final Christmas at Button House, and a proper send-off.",
    christmas: "core",
    suitability: "8+",
    timings: ["december"],
    strength: {
      british: "strong",
      comedy: "strong",
      emotional: "strong",
      family: "strong",
      older_children: "strong",
      teenagers: "strong",
      mixed_ages: "strong",
    },
  },
  {
    key: "outnumbered_christmas_2009",
    title: "Outnumbered Christmas Special",
    year: 2009,
    type: "episode",
    minutes: 30,
    blurb: "Christmas with the Brockmans — improvised, chaotic, uncomfortably accurate.",
    christmas: "core",
    suitability: "12+",
    timings: ["december"],
    strength: {
      british: "strong",
      comedy: "strong",
      adults: "strong",
      adult_children: "extra",
    },
  },
  {
    key: "outnumbered_christmas_2011",
    title: "Outnumbered Christmas Special",
    year: 2011,
    type: "episode",
    minutes: 30,
    blurb: "Another Brockman Christmas, another set of unanswerable questions.",
    christmas: "core",
    suitability: "12+",
    timings: ["december"],
    strength: {
      british: "strong",
      comedy: "strong",
      adults: "strong",
    },
  },
  {
    key: "outnumbered_christmas_2012",
    title: "Outnumbered Christmas Special",
    year: 2012,
    type: "episode",
    minutes: 30,
    blurb: "The children are older, the arguments are better organised.",
    christmas: "core",
    suitability: "12+",
    timings: ["december"],
    strength: {
      british: "strong",
      comedy: "strong",
      adults: "strong",
    },
  },
  {
    key: "outnumbered_christmas_2016",
    title: "Outnumbered Christmas Special",
    year: 2016,
    type: "episode",
    minutes: 45,
    blurb: "A grown-up Brockman Christmas, with teenagers instead of toddlers.",
    christmas: "core",
    suitability: "12+",
    timings: ["december"],
    strength: {
      british: "strong",
      comedy: "strong",
      teenagers: "strong",
      with_teenagers: "strong",
      adults: "strong",
    },
  },
  {
    key: "outnumbered_christmas_2024",
    title: "Outnumbered Christmas Special",
    year: 2024,
    type: "episode",
    minutes: 60,
    blurb: "The family reunites for Christmas with everyone fully grown.",
    christmas: "core",
    suitability: "12+",
    timings: ["december"],
    strength: {
      british: "strong",
      comedy: "strong",
      adult_children: "strong",
      with_grown_up_children: "strong",
      adults: "strong",
    },
  },

  /* --------------------------------------------------- Doctor Who at Christmas */
  {
    key: "doctor_who_christmas_invasion",
    title: "Doctor Who: The Christmas Invasion",
    year: 2005,
    type: "episode",
    minutes: 60,
    blurb: "A new Doctor, killer Christmas trees and a very bad day for London.",
    christmas: "strong_setting",
    suitability: "8+",
    timings: ["christmas_day", "december"],
    strength: {
      british: "strong",
      adventure: "strong",
      family: "strong",
      older_children: "strong",
      teenagers: "strong",
      mixed_ages: "strong",
      christmas_day_afternoon: "strong",
    },
  },
  {
    key: "doctor_who_runaway_bride",
    title: "Doctor Who: The Runaway Bride",
    year: 2006,
    type: "episode",
    minutes: 60,
    blurb: "Donna arrives mid-wedding, shouting, and the TARDIS never recovers.",
    christmas: "strong_setting",
    suitability: "8+",
    timings: ["christmas_day", "december"],
    strength: {
      british: "strong",
      adventure: "strong",
      comedy: "strong",
      family: "strong",
      older_children: "strong",
      teenagers: "strong",
      mixed_ages: "strong",
    },
  },
  {
    key: "doctor_who_voyage_of_the_damned",
    title: "Doctor Who: Voyage of the Damned",
    year: 2007,
    type: "episode",
    minutes: 72,
    blurb: "A starship Titanic, murderous angel robots and Kylie.",
    christmas: "strong_setting",
    suitability: "8+",
    timings: ["christmas_day", "december"],
    strength: {
      british: "strong",
      adventure: "strong",
      family: "strong",
      older_children: "strong",
      teenagers: "strong",
      mixed_ages: "strong",
    },
  },
  {
    key: "doctor_who_next_doctor",
    title: "Doctor Who: The Next Doctor",
    year: 2008,
    type: "episode",
    minutes: 60,
    blurb: "Victorian London, Cybermen and a man who thinks he is the Doctor.",
    christmas: "strong_setting",
    suitability: "8+",
    timings: ["christmas_day", "december"],
    strength: {
      british: "strong",
      adventure: "strong",
      family: "strong",
      older_children: "strong",
      mixed_ages: "strong",
    },
  },
  {
    key: "doctor_who_a_christmas_carol",
    title: "Doctor Who: A Christmas Carol",
    year: 2010,
    type: "episode",
    minutes: 62,
    blurb: "Dickens rewritten with a sky full of fish. The best of the Christmas run.",
    christmas: "core",
    suitability: "8+",
    timings: ["christmas_day", "december"],
    strength: {
      british: "strong",
      adventure: "strong",
      magical: "strong",
      emotional: "strong",
      family: "strong",
      older_children: "strong",
      teenagers: "strong",
      mixed_ages: "strong",
      christmas_day_afternoon: "strong",
    },
  },
  {
    key: "doctor_who_widow_and_wardrobe",
    title: "Doctor Who: The Doctor, the Widow and the Wardrobe",
    year: 2011,
    type: "episode",
    minutes: 60,
    blurb: "A wartime family step through a present into a forest of living trees.",
    christmas: "core",
    suitability: "8+",
    timings: ["christmas_day", "december"],
    strength: {
      british: "strong",
      magical: "strong",
      family: "strong",
      older_children: "strong",
      mixed_ages: "strong",
    },
  },
  {
    key: "doctor_who_the_snowmen",
    title: "Doctor Who: The Snowmen",
    year: 2012,
    type: "episode",
    minutes: 60,
    blurb: "Victorian snow that bites, and the first sight of Clara.",
    christmas: "strong_setting",
    suitability: "8+",
    timings: ["christmas_day", "december"],
    strength: {
      british: "strong",
      adventure: "strong",
      older_children: "strong",
      teenagers: "strong",
      family: "strong",
    },
  },
  {
    key: "doctor_who_last_christmas",
    title: "Doctor Who: Last Christmas",
    year: 2014,
    type: "episode",
    minutes: 60,
    blurb: "Dream crabs, a polar base and Santa Claus arguing about tangerines.",
    christmas: "core",
    suitability: "12+",
    timings: ["christmas_day", "december"],
    strength: {
      british: "strong",
      adventure: "strong",
      teenagers: "strong",
      adults: "strong",
      family: "extra",
      young_children: "unsuitable",
    },
  },
];

/** Every mood-namespace key a title is curated for, strongest first. */
export function titleMoodKeys(item: CatalogueTitle, moodKeys: readonly MoodKey[]): MoodKey[] {
  const order: Record<string, number> = { essential: 0, strong: 1, extra: 2 };
  return moodKeys
    .filter((m) => {
      const s = item.strength[m];
      return s !== undefined && s !== "unsuitable";
    })
    .sort((a, b) => order[item.strength[a] as string] - order[item.strength[b] as string]);
}
