/**
 * Curated Christmas viewing catalogue — reference content only.
 * Nothing here is stored per user. When someone taps "Add to my watchlist"
 * we create an ordinary row in the `watchlist_items` table from these fields.
 *
 * No AI, no external API, no copyrighted summaries or artwork: every title and
 * blurb is a factual, concise entry written for A Complete Christmas.
 */

export type Audience =
  | "young_children"
  | "older_children"
  | "teenagers"
  | "young_adults"
  | "couple"
  | "adults_no_children"
  | "mixed_ages"
  | "extended"
  | "alone";

export type Mood =
  | "classic"
  | "funny"
  | "romantic"
  | "cosy"
  | "magical"
  | "nostalgic"
  | "family"
  | "newer"
  | "easy"
  | "tearjerker"
  | "musical"
  | "animated"
  | "adventure"
  | "feel_good"
  | "surprise";

export type ContentType = "film" | "tv_special" | "episode" | "series" | "other";
export type AgeBand = "all" | "5+" | "8+" | "12+" | "adult";

export interface WatchlistIdea {
  key: string;
  title: string;
  year?: number;
  type: ContentType;
  /** One short, original sentence describing what makes it Christmassy. */
  blurb: string;
  audiences: Audience[];
  moods: Mood[];
  ageBand: AgeBand;
  timings: string[];
  minutes?: number;
  tags: string[];
}

const ALL: Audience[] = [
  "young_children",
  "older_children",
  "teenagers",
  "young_adults",
  "couple",
  "adults_no_children",
  "mixed_ages",
  "extended",
  "alone",
];

const FAMILY_MIX: Audience[] = [
  "young_children",
  "older_children",
  "teenagers",
  "mixed_ages",
  "extended",
];

const ADULT_CHILD: Audience[] = [
  "teenagers",
  "young_adults",
  "adults_no_children",
  "couple",
  "alone",
  "mixed_ages",
  "extended",
];

const ADULT_ONLY: Audience[] = ["young_adults", "adults_no_children", "couple", "alone"];

export const WATCHLIST_IDEAS: WatchlistIdea[] = [
  // ---- Classic films -------------------------------------------------------
  {
    key: "its_a_wonderful_life",
    title: "It's a Wonderful Life",
    year: 1946,
    type: "film",
    blurb: "A Christmas guardian angel shows one man how much his life has meant.",
    audiences: ADULT_ONLY,
    moods: ["classic", "tearjerker", "feel_good"],
    ageBand: "adult",
    timings: ["christmas_eve", "christmas_day"],
    minutes: 130,
    tags: ["Classic", "Feel-good"],
  },
  {
    key: "white_christmas",
    title: "White Christmas",
    year: 1954,
    type: "film",
    blurb: "Two song-and-dance men bring a winter show to a snowless Vermont inn.",
    audiences: ALL,
    moods: ["classic", "musical", "cosy"],
    ageBand: "all",
    timings: ["december", "christmas_day"],
    minutes: 120,
    tags: ["Musical", "Classic"],
  },
  {
    key: "miracle_on_34th_street",
    title: "Miracle on 34th Street",
    year: 1947,
    type: "film",
    blurb: "A department-store Santa claims to be the real thing, and a court must decide.",
    audiences: FAMILY_MIX,
    moods: ["classic", "magical", "family"],
    ageBand: "all",
    timings: ["christmas_eve", "christmas_day", "december"],
    minutes: 96,
    tags: ["Classic", "Magical"],
  },
  {
    key: "the_bishop_wife",
    title: "The Bishop's Wife",
    year: 1947,
    type: "film",
    blurb: "An angel arrives to help a troubled clergyman and his wife find Christmas again.",
    audiences: ADULT_ONLY,
    moods: ["classic", "romantic", "cosy"],
    ageBand: "adult",
    timings: ["christmas_eve"],
    minutes: 109,
    tags: ["Classic", "Romantic"],
  },
  {
    key: "holiday_inn",
    title: "Holiday Inn",
    year: 1942,
    type: "film",
    blurb: "A song-and-dance duo opens a holiday-themed inn, with Christmas as the finale.",
    audiences: ADULT_ONLY,
    moods: ["classic", "musical", "nostalgic"],
    ageBand: "adult",
    timings: ["december"],
    minutes: 100,
    tags: ["Musical", "Classic"],
  },
  {
    key: "a_christmas_carol_1951",
    title: "A Christmas Carol",
    year: 1951,
    type: "film",
    blurb: "A miserly businessman is visited by three spirits on Christmas Eve.",
    audiences: FAMILY_MIX,
    moods: ["classic", "nostalgic", "magical"],
    ageBand: "8+",
    timings: ["christmas_eve"],
    minutes: 86,
    tags: ["Classic", "Spirits"],
  },

  // ---- Family animation ------------------------------------------------------
  {
    key: "the_snowman",
    title: "The Snowman",
    year: 1982,
    type: "tv_special",
    blurb: "A little boy's snowman comes to life for a magical Christmas-night flight.",
    audiences: ALL,
    moods: ["animated", "magical", "nostalgic"],
    ageBand: "all",
    timings: ["christmas_eve", "christmas_morning"],
    minutes: 26,
    tags: ["Animated", "Short"],
  },
  {
    key: "snowman_and_snowdog",
    title: "The Snowman and the Snowdog",
    year: 2012,
    type: "tv_special",
    blurb: "A boy builds a snowdog to join the Snowman on another wordless adventure.",
    audiences: FAMILY_MIX,
    moods: ["animated", "magical", "family"],
    ageBand: "all",
    timings: ["christmas_eve", "christmas_morning"],
    minutes: 24,
    tags: ["Animated", "Short"],
  },
  {
    key: "the_grinch_2018",
    title: "The Grinch",
    year: 2018,
    type: "film",
    blurb: "A grumpy creature hatches a plan to steal Christmas from Whoville.",
    audiences: FAMILY_MIX,
    moods: ["animated", "funny", "family"],
    ageBand: "all",
    timings: ["christmas_eve", "december"],
    minutes: 85,
    tags: ["Animated", "Family"],
  },
  {
    key: "arthur_christmas",
    title: "Arthur Christmas",
    year: 2011,
    type: "film",
    blurb: "Santa's youngest son races to deliver a single forgotten present.",
    audiences: FAMILY_MIX,
    moods: ["animated", "funny", "magical"],
    ageBand: "all",
    timings: ["christmas_eve", "christmas_day"],
    minutes: 97,
    tags: ["Animated", "Adventure"],
  },
  {
    key: "frozen",
    title: "Frozen",
    year: 2013,
    type: "film",
    blurb: "Two sisters, a frozen kingdom, and a snowy adventure in eternal winter.",
    audiences: FAMILY_MIX,
    moods: ["animated", "musical", "magical"],
    ageBand: "all",
    timings: ["december", "christmas_day"],
    minutes: 102,
    tags: ["Musical", "Adventure"],
  },
  {
    key: "klaus",
    title: "Klaus",
    year: 2019,
    type: "film",
    blurb: "A reclusive toymaker and a reluctant postman accidentally create the legend of Santa.",
    audiences: FAMILY_MIX,
    moods: ["animated", "feel_good", "nostalgic"],
    ageBand: "all",
    timings: ["christmas_eve", "christmas_day"],
    minutes: 96,
    tags: ["Animated", "Origin"],
  },
  {
    key: "nightmare_before_christmas",
    title: "The Nightmare Before Christmas",
    year: 1993,
    type: "film",
    blurb: "The Pumpkin King discovers Christmas Town and tries to take over the holiday.",
    audiences: ["older_children", "teenagers", "young_adults", "mixed_ages", "couple"],
    moods: ["animated", "musical", "nostalgic"],
    ageBand: "8+",
    timings: ["christmas_eve", "december"],
    minutes: 76,
    tags: ["Animated", "Musical"],
  },
  {
    key: "polar_express",
    title: "The Polar Express",
    year: 2004,
    type: "film",
    blurb: "A magical train carries children to the North Pole on Christmas Eve.",
    audiences: FAMILY_MIX,
    moods: ["animated", "magical", "adventure"],
    ageBand: "all",
    timings: ["christmas_eve", "christmas_morning"],
    minutes: 100,
    tags: ["Animated", "Adventure"],
  },
  {
    key: "elf",
    title: "Elf",
    year: 2003,
    type: "film",
    blurb: "A human raised as an elf travels to New York to find his real father.",
    audiences: FAMILY_MIX,
    moods: ["funny", "family", "feel_good"],
    ageBand: "all",
    timings: ["christmas_eve", "christmas_day", "december"],
    minutes: 97,
    tags: ["Comedy", "Family"],
  },
  {
    key: "muppets_christmas_carol",
    title: "The Muppet Christmas Carol",
    year: 1992,
    type: "film",
    blurb: "Charles Dickens's tale retold with music, puppets, and a very small Bob Cratchit.",
    audiences: FAMILY_MIX,
    moods: ["musical", "funny", "family"],
    ageBand: "all",
    timings: ["christmas_eve", "christmas_day"],
    minutes: 86,
    tags: ["Musical", "Classic"],
  },
  {
    key: "home_alone",
    title: "Home Alone",
    year: 1990,
    type: "film",
    blurb: "A young boy defends his house from two bumbling burglars while his family is away.",
    audiences: FAMILY_MIX,
    moods: ["funny", "family", "adventure"],
    ageBand: "8+",
    timings: ["christmas_eve", "christmas_day"],
    minutes: 103,
    tags: ["Comedy", "Adventure"],
  },
  {
    key: "home_alone_2",
    title: "Home Alone 2: Lost in New York",
    year: 1992,
    type: "film",
    blurb: "The same resourceful boy is lost in Manhattan at Christmas, with the same burglars in pursuit.",
    audiences: FAMILY_MIX,
    moods: ["funny", "family", "adventure"],
    ageBand: "8+",
    timings: ["christmas_eve", "christmas_day"],
    minutes: 120,
    tags: ["Comedy", "Adventure"],
  },

  // ---- Modern family films ---------------------------------------------------
  {
    key: "love_actually",
    title: "Love Actually",
    year: 2003,
    type: "film",
    blurb: "Ten London love stories overlap in the weeks before Christmas.",
    audiences: ADULT_ONLY,
    moods: ["romantic", "funny", "feel_good"],
    ageBand: "adult",
    timings: ["december", "christmas_eve"],
    minutes: 135,
    tags: ["Romantic", "Comedy"],
  },
  {
    key: "last_holiday",
    title: "Last Holiday",
    year: 2006,
    type: "film",
    blurb: "A woman who thinks she has weeks to live splashes out on a luxury Christmas holiday.",
    audiences: ADULT_ONLY,
    moods: ["feel_good", "funny", "romantic"],
    ageBand: "adult",
    timings: ["christmas_day", "boxing_day"],
    minutes: 112,
    tags: ["Feel-good", "Comedy"],
  },
  {
    key: "the_holiday",
    title: "The Holiday",
    year: 2006,
    type: "film",
    blurb: "Two women swap homes over Christmas and each find unexpected romance.",
    audiences: ADULT_ONLY,
    moods: ["romantic", "cosy", "feel_good"],
    ageBand: "adult",
    timings: ["christmas_eve", "boxing_day", "december"],
    minutes: 138,
    tags: ["Romantic", "Cosy"],
  },
  {
    key: "bridget_jones_diary",
    title: "Bridget Jones's Diary",
    year: 2001,
    type: "film",
    blurb: "A year in the life of a single woman begins and ends around a Christmas party.",
    audiences: ADULT_ONLY,
    moods: ["funny", "romantic", "feel_good"],
    ageBand: "adult",
    timings: ["december", "christmas_eve"],
    minutes: 97,
    tags: ["Comedy", "Romantic"],
  },
  {
    key: "about_a_boy",
    title: "About a Boy",
    year: 2002,
    type: "film",
    blurb: "A selfish bachelor and a lonely boy become an unlikely family, with a Christmas talent show at the centre.",
    audiences: ["older_children", "teenagers", "adults_no_children", "couple", "mixed_ages"],
    moods: ["funny", "feel_good", "family"],
    ageBand: "12+",
    timings: ["december"],
    minutes: 101,
    tags: ["Comedy", "Feel-good"],
  },
  {
    key: "nativity",
    title: "Nativity!",
    year: 2009,
    type: "film",
    blurb: "A primary-school teacher fibs that Hollywood is coming, and the whole town gets involved.",
    audiences: FAMILY_MIX,
    moods: ["funny", "family", "musical"],
    ageBand: "all",
    timings: ["december"],
    minutes: 105,
    tags: ["Comedy", "Musical"],
  },
  {
    key: "nativity_2",
    title: "Nativity 2: Danger in the Manger!",
    year: 2012,
    type: "film",
    blurb: "Rival primary schools compete to stage the best Christmas nativity show.",
    audiences: FAMILY_MIX,
    moods: ["funny", "family", "musical"],
    ageBand: "all",
    timings: ["december"],
    minutes: 105,
    tags: ["Comedy", "Musical"],
  },
  {
    key: "jingle_all_the_way",
    title: "Jingle All the Way",
    year: 1996,
    type: "film",
    blurb: "Two fathers compete to find the last must-have Christmas toy in the city.",
    audiences: FAMILY_MIX,
    moods: ["funny", "family", "adventure"],
    ageBand: "all",
    timings: ["christmas_eve", "december"],
    minutes: 89,
    tags: ["Comedy", "Family"],
  },
  {
    key: "miracle_on_34th_street_1994",
    title: "Miracle on 34th Street",
    year: 1994,
    type: "film",
    blurb: "A modern retelling of the department-store Santa who may be the real thing.",
    audiences: FAMILY_MIX,
    moods: ["magical", "family", "classic"],
    ageBand: "all",
    timings: ["christmas_eve", "christmas_day", "december"],
    minutes: 114,
    tags: ["Magical", "Family"],
  },
  {
    key: "the_santa_clause",
    title: "The Santa Clause",
    year: 1994,
    type: "film",
    blurb: "A divorced dad accidentally becomes the new Santa Claus overnight.",
    audiences: FAMILY_MIX,
    moods: ["funny", "magical", "family"],
    ageBand: "all",
    timings: ["christmas_eve", "christmas_day"],
    minutes: 97,
    tags: ["Comedy", "Magical"],
  },
  {
    key: "santa_clause_2",
    title: "The Santa Clause 2",
    year: 2002,
    type: "film",
    blurb: "Santa must find a Mrs Claus before Christmas Eve or lose his magic.",
    audiences: FAMILY_MIX,
    moods: ["funny", "romantic", "family"],
    ageBand: "all",
    timings: ["christmas_eve"],
    minutes: 104,
    tags: ["Comedy", "Romantic"],
  },
  {
    key: "gremlins",
    title: "Gremlins",
    year: 1984,
    type: "film",
    blurb: "A small-town Christmas is overrun by mischievous, troublemaking creatures.",
    audiences: ["older_children", "teenagers", "young_adults", "mixed_ages"],
    moods: ["funny", "adventure", "nostalgic"],
    ageBand: "12+",
    timings: ["christmas_eve", "december"],
    minutes: 106,
    tags: ["Comedy", "Adventure"],
  },

  // ---- Teen / young adult viewing -------------------------------------------
  {
    key: "mean_girls",
    title: "Mean Girls",
    year: 2004,
    type: "film",
    blurb: "A teen newcomer navigates high-school cliques, including a Christmas talent-show showdown.",
    audiences: ["teenagers", "young_adults", "mixed_ages"],
    moods: ["funny", "newer", "feel_good"],
    ageBand: "12+",
    timings: ["december"],
    minutes: 97,
    tags: ["Comedy", "Teen"],
  },
  {
    key: "the_princess_switch",
    title: "The Princess Switch",
    year: 2018,
    type: "film",
    blurb: "A Chicago baker and a soon-to-be princess switch places before Christmas.",
    audiences: ["teenagers", "young_adults", "couple", "mixed_ages"],
    moods: ["romantic", "funny", "newer"],
    ageBand: "all",
    timings: ["december"],
    minutes: 101,
    tags: ["Romantic", "Comedy"],
  },
  {
    key: "princess_switch_switched",
    title: "The Princess Switch: Switched Again",
    year: 2020,
    type: "film",
    blurb: "A third lookalike joins the royal Christmastime swap.",
    audiences: ["teenagers", "young_adults", "couple", "mixed_ages"],
    moods: ["romantic", "funny", "newer"],
    ageBand: "all",
    timings: ["december"],
    minutes: 97,
    tags: ["Romantic", "Comedy"],
  },
  {
    key: "a_cinderella_story",
    title: "A Cinderella Story: Christmas Wish",
    year: 2019,
    type: "film",
    blurb: "A modern fairy-tale retelling set around a Christmas musical performance.",
    audiences: ["teenagers", "young_adults", "couple", "mixed_ages"],
    moods: ["romantic", "musical", "newer"],
    ageBand: "all",
    timings: ["december"],
    minutes: 93,
    tags: ["Musical", "Romantic"],
  },
  {
    key: "dash_lily",
    title: "Dash & Lily",
    year: 2020,
    type: "series",
    blurb: "Two teenagers swap a dare-filled notebook around New York City at Christmas.",
    audiences: ["teenagers", "young_adults", "couple"],
    moods: ["romantic", "funny", "newer"],
    ageBand: "12+",
    timings: ["december"],
    tags: ["Series", "Romantic"],
  },
  {
    key: "let_it_snow",
    title: "Let It Snow",
    year: 2019,
    type: "film",
    blurb: "A snowstorm strands a group of small-town teenagers on Christmas Eve.",
    audiences: ["teenagers", "young_adults", "couple"],
    moods: ["romantic", "funny", "newer"],
    ageBand: "12+",
    timings: ["christmas_eve"],
    minutes: 92,
    tags: ["Teen", "Romantic"],
  },
  {
    key: "noelle",
    title: "Noelle",
    year: 2019,
    type: "film",
    blurb: "Santa's daughter must bring her reluctant brother back to the North Pole.",
    audiences: FAMILY_MIX,
    moods: ["funny", "magical", "newer"],
    ageBand: "all",
    timings: ["christmas_eve", "christmas_day"],
    minutes: 100,
    tags: ["Comedy", "Magical"],
  },
  {
    key: "krampus",
    title: "Krampus",
    year: 2015,
    type: "film",
    blurb: "A family bickering at Christmas accidentally summons a dark winter spirit.",
    audiences: ["teenagers", "young_adults", "mixed_ages"],
    moods: ["adventure", "funny", "nostalgic"],
    ageBand: "12+",
    timings: ["christmas_eve"],
    minutes: 98,
    tags: ["Dark comedy", "Adventure"],
  },
  {
    key: "edward_scissorhands",
    title: "Edward Scissorhands",
    year: 1990,
    type: "film",
    blurb: "An unfinished man with scissors for hands is taken in by a suburban family at Christmas.",
    audiences: ["teenagers", "young_adults", "couple", "mixed_ages"],
    moods: ["romantic", "nostalgic", "magical"],
    ageBand: "12+",
    timings: ["december"],
    minutes: 105,
    tags: ["Fantasy", "Romantic"],
  },
  {
    key: "harry_potter_sorcerer_stone",
    title: "Harry Potter and the Philosopher's Stone",
    year: 2001,
    type: "film",
    blurb: "A young wizard's first year at Hogwarts includes a Christmas at the castle.",
    audiences: ["older_children", "teenagers", "young_adults", "mixed_ages", "extended"],
    moods: ["magical", "adventure", "family"],
    ageBand: "8+",
    timings: ["christmas_eve", "christmas_day", "december"],
    minutes: 152,
    tags: ["Magical", "Adventure"],
  },
  {
    key: "harry_potter_chamber_secrets",
    title: "Harry Potter and the Chamber of Secrets",
    year: 2002,
    type: "film",
    blurb: "The second year at Hogwarts includes a Christmas spent in the castle.",
    audiences: ["older_children", "teenagers", "young_adults", "mixed_ages"],
    moods: ["magical", "adventure", "family"],
    ageBand: "8+",
    timings: ["christmas_eve", "december"],
    minutes: 161,
    tags: ["Magical", "Adventure"],
  },
  {
    key: "chronicles_narnia",
    title: "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe",
    year: 2005,
    type: "film",
    blurb: "Four children step through a wardrobe into a snowy, magical land ruled by an evil queen.",
    audiences: ["older_children", "teenagers", "young_adults", "mixed_ages"],
    moods: ["adventure", "magical", "family"],
    ageBand: "8+",
    timings: ["christmas_day", "boxing_day"],
    minutes: 143,
    tags: ["Adventure", "Magical"],
  },

  // ---- Couple / cosy viewing ------------------------------------------------
  {
    key: "while_you_were_sleeping",
    title: "While You Were Sleeping",
    year: 1995,
    type: "film",
    blurb: "A subway token-booth attendant is mistaken for the fiancée of a man in a coma at Christmas.",
    audiences: ["couple", "adults_no_children", "alone"],
    moods: ["romantic", "cosy", "feel_good"],
    ageBand: "adult",
    timings: ["christmas_eve", "boxing_day"],
    minutes: 103,
    tags: ["Romantic", "Cosy"],
  },
  {
    key: "youve_got_mail",
    title: "You've Got Mail",
    year: 1998,
    type: "film",
    blurb: "Two bookshop rivals fall for each other online through the seasons, including Christmas in New York.",
    audiences: ["couple", "adults_no_children", "alone"],
    moods: ["romantic", "cosy", "nostalgic"],
    ageBand: "adult",
    timings: ["december"],
    minutes: 119,
    tags: ["Romantic", "Cosy"],
  },
  {
    key: "serendipity",
    title: "Serendipity",
    year: 2001,
    type: "film",
    blurb: "A couple who meet Christmas shopping leave their future to fate and a single glove.",
    audiences: ["couple", "adults_no_children", "alone"],
    moods: ["romantic", "magical", "feel_good"],
    ageBand: "adult",
    timings: ["christmas_eve", "december"],
    minutes: 90,
    tags: ["Romantic", "Magical"],
  },
  {
    key: "the_family_stone",
    title: "The Family Stone",
    year: 2005,
    type: "film",
    blurb: "A tight-knit family brings a girlfriend home for Christmas, and nothing goes to plan.",
    audiences: ["couple", "adults_no_children", "extended", "mixed_ages"],
    moods: ["romantic", "funny", "tearjerker"],
    ageBand: "adult",
    timings: ["christmas_eve", "christmas_day"],
    minutes: 103,
    tags: ["Romantic", "Family"],
  },
  {
    key: "last_christmas",
    title: "Last Christmas",
    year: 2019,
    type: "film",
    blurb: "A woman working as an elf in a Christmas shop tries to get her life back on track in London.",
    audiences: ["couple", "young_adults", "adults_no_children", "alone"],
    moods: ["romantic", "musical", "feel_good"],
    ageBand: "adult",
    timings: ["december", "christmas_day"],
    minutes: 103,
    tags: ["Romantic", "Musical"],
  },
  {
    key: "christmas_with_the_kranks",
    title: "Christmas with the Kranks",
    year: 2004,
    type: "film",
    blurb: "A couple decides to skip Christmas and go on a cruise, until their neighbours object.",
    audiences: ["couple", "adults_no_children", "extended", "mixed_ages"],
    moods: ["funny", "family", "feel_good"],
    ageBand: "all",
    timings: ["december", "christmas_eve"],
    minutes: 99,
    tags: ["Comedy", "Family"],
  },
  {
    key: "the_best_man_holiday",
    title: "The Best Man Holiday",
    year: 2013,
    type: "film",
    blurb: "College friends reunite for a Christmas weekend filled with old feelings and new truths.",
    audiences: ["adults_no_children", "couple", "young_adults"],
    moods: ["funny", "tearjerker", "feel_good"],
    ageBand: "adult",
    timings: ["christmas_day", "boxing_day"],
    minutes: 123,
    tags: ["Drama", "Comedy"],
  },
  {
    key: "meet_me_in_st_louis",
    title: "Meet Me in St. Louis",
    year: 1944,
    type: "film",
    blurb: "A family faces a move away from home in the year leading up to the 1904 World's Fair, with Christmas at the heart.",
    audiences: ["couple", "adults_no_children", "alone", "mixed_ages"],
    moods: ["classic", "musical", "nostalgic"],
    ageBand: "all",
    timings: ["christmas_eve", "december"],
    minutes: 113,
    tags: ["Musical", "Classic"],
  },
  {
    key: "scrooged",
    title: "Scrooged",
    year: 1988,
    type: "film",
    blurb: "A cynical TV executive is visited by three ghosts on the set of a live Christmas special.",
    audiences: ["adults_no_children", "couple", "young_adults"],
    moods: ["funny", "classic", "nostalgic"],
    ageBand: "adult",
    timings: ["christmas_eve", "december"],
    minutes: 101,
    tags: ["Comedy", "Classic"],
  },
  {
    key: "trading_places",
    title: "Trading Places",
    year: 1983,
    type: "film",
    blurb: "Two wealthy men swap the lives of a con artist and a stockbroker around the Christmas season.",
    audiences: ["adults_no_children", "couple", "young_adults"],
    moods: ["funny", "classic", "feel_good"],
    ageBand: "adult",
    timings: ["christmas_eve", "december"],
    minutes: 116,
    tags: ["Comedy", "Classic"],
  },
  {
    key: "when_harry_met_sally",
    title: "When Harry Met Sally...",
    year: 1989,
    type: "film",
    blurb: "Two friends cross the seasons of New York over twelve years, with a memorable Christmas scene.",
    audiences: ["couple", "adults_no_children", "alone"],
    moods: ["romantic", "funny", "classic"],
    ageBand: "adult",
    timings: ["december"],
    minutes: 96,
    tags: ["Romantic", "Classic"],
  },

  // ---- Children's young favourites ------------------------------------------
  {
    key: "peppa_pig_christmas",
    title: "Peppa Pig: Christmas",
    type: "episode",
    blurb: "Peppa and her family celebrate Christmas with presents, snow, and a very special visit.",
    audiences: ["young_children", "mixed_ages"],
    moods: ["animated", "family", "magical"],
    ageBand: "all",
    timings: ["christmas_morning", "december"],
    minutes: 25,
    tags: ["Animated", "Short"],
  },
  {
    key: "stick_man",
    title: "Stick Man",
    year: 2015,
    type: "tv_special",
    blurb: "A stick-shaped family man goes on a long adventure to get back home for Christmas.",
    audiences: ["young_children", "mixed_ages"],
    moods: ["animated", "adventure", "family"],
    ageBand: "all",
    timings: ["christmas_eve", "christmas_day"],
    minutes: 27,
    tags: ["Animated", "Short"],
  },
  {
    key: "room_on_the_broom",
    title: "Room on the Broom",
    year: 2012,
    type: "tv_special",
    blurb: "A kind witch and her cat make room on the broom for a Christmas-hued adventure.",
    audiences: ["young_children", "mixed_ages"],
    moods: ["animated", "magical", "family"],
    ageBand: "all",
    timings: ["christmas_eve", "december"],
    minutes: 25,
    tags: ["Animated", "Short"],
  },
  {
    key: "zog",
    title: "Zog",
    year: 2018,
    type: "tv_special",
    blurb: "A keen dragon at dragon school learns to fly with a little help from a princess.",
    audiences: ["young_children", "mixed_ages"],
    moods: ["animated", "funny", "family"],
    ageBand: "all",
    timings: ["christmas_eve", "december"],
    minutes: 25,
    tags: ["Animated", "Short"],
  },
  {
    key: "tabby_mctat",
    title: "Tabby McTat",
    year: 2023,
    type: "tv_special",
    blurb: "A busker cat and his friend are separated, then find their way back to each other.",
    audiences: ["young_children", "mixed_ages"],
    moods: ["animated", "musical", "family"],
    ageBand: "all",
    timings: ["christmas_eve", "december"],
    minutes: 30,
    tags: ["Animated", "Musical"],
  },
  {
    key: "father_christmas",
    title: "Father Christmas",
    year: 1991,
    type: "tv_special",
    blurb: "A day in the life of a very ordinary Santa Claus on his holiday off.",
    audiences: ["young_children", "mixed_ages"],
    moods: ["animated", "funny", "cosy"],
    ageBand: "all",
    timings: ["christmas_eve", "christmas_day"],
    minutes: 26,
    tags: ["Animated", "Short"],
  },
  {
    key: "paw_patrol_christmas",
    title: "PAW Patrol: A Very Merry Christmas",
    type: "episode",
    blurb: "The pups help save Santa's sleigh and deliver presents in Adventure Bay.",
    audiences: ["young_children", "mixed_ages"],
    moods: ["animated", "adventure", "magical"],
    ageBand: "all",
    timings: ["christmas_morning"],
    minutes: 24,
    tags: ["Animated", "Adventure"],
  },
  {
    key: "duggee_christmas",
    title: "Hey Duggee: Christmas",
    type: "episode",
    blurb: "The Squirrels earn their Christmas badges with Duggee's help.",
    audiences: ["young_children", "mixed_ages"],
    moods: ["animated", "funny", "family"],
    ageBand: "all",
    timings: ["christmas_morning", "december"],
    minutes: 7,
    tags: ["Animated", "Short"],
  },
  {
    key: "bing_christmas",
    title: "Bing: Christmas",
    type: "episode",
    blurb: "Bing experiences the small wonders of Christmas morning with his family.",
    audiences: ["young_children", "mixed_ages"],
    moods: ["animated", "family", "magical"],
    ageBand: "all",
    timings: ["christmas_morning"],
    minutes: 7,
    tags: ["Animated", "Short"],
  },
  {
    key: "shaun_the_sheep_christmas",
    title: "Shaun the Sheep: We Wish Ewe a Merry Christmas",
    type: "tv_special",
    blurb: "The flock gets in the way of the farmer's quiet Christmas plans.",
    audiences: ["young_children", "older_children", "mixed_ages"],
    moods: ["animated", "funny", "family"],
    ageBand: "all",
    timings: ["christmas_eve"],
    minutes: 30,
    tags: ["Animated", "Comedy"],
  },
  {
    key: "olaf_frozen_adventure",
    title: "Olaf's Frozen Adventure",
    year: 2017,
    type: "tv_special",
    blurb: "Olaf searches for the perfect holiday traditions for Anna and Elsa.",
    audiences: ["young_children", "older_children", "mixed_ages"],
    moods: ["animated", "musical", "family"],
    ageBand: "all",
    timings: ["christmas_eve"],
    minutes: 21,
    tags: ["Animated", "Musical"],
  },
  {
    key: "mickey_once_upon_a_christmas",
    title: "Mickey's Once Upon a Christmas",
    year: 1999,
    type: "film",
    blurb: "Three short Christmas stories with Mickey, Minnie and friends.",
    audiences: ["young_children", "older_children", "mixed_ages"],
    moods: ["animated", "family", "magical"],
    ageBand: "all",
    timings: ["christmas_morning"],
    minutes: 66,
    tags: ["Animated", "Short"],
  },
  {
    key: "winnie_pooh_christmas",
    title: "Winnie the Pooh: A Very Merry Pooh Year",
    year: 2002,
    type: "film",
    blurb: "Pooh and friends try to change their ways to keep Rabbit from leaving.",
    audiences: ["young_children", "mixed_ages"],
    moods: ["animated", "family", "cosy"],
    ageBand: "all",
    timings: ["christmas_morning"],
    minutes: 65,
    tags: ["Animated", "Cosy"],
  },

  // ---- TV specials and annual classics --------------------------------------
  {
    key: "love_actually_red_nose",
    title: "Love Actually: Comic Relief Special",
    year: 2017,
    type: "tv_special",
    blurb: "A short reunion catching up with some of the original characters for charity.",
    audiences: ["adults_no_children", "couple", "young_adults"],
    moods: ["funny", "romantic", "nostalgic"],
    ageBand: "adult",
    timings: ["december"],
    minutes: 15,
    tags: ["Comedy", "Short"],
  },
  {
    key: "gavin_stacey_christmas",
    title: "Gavin & Stacey: A Special Christmas",
    year: 2019,
    type: "tv_special",
    blurb: "The ship-to-shore family reunites for a Christmas back in Barry.",
    audiences: ["adults_no_children", "couple", "young_adults", "extended"],
    moods: ["funny", "nostalgic", "family"],
    ageBand: "adult",
    timings: ["christmas_day", "boxing_day"],
    minutes: 60,
    tags: ["Comedy", "TV"],
  },
  {
    key: "the_vicar_dibley_christmas",
    title: "The Vicar of Dibley: Christmas Specials",
    type: "episode",
    blurb: "Geraldine's Christmas lunches and village antics remain a firm favourite.",
    audiences: ["adults_no_children", "couple", "extended"],
    moods: ["funny", "classic", "cosy"],
    ageBand: "adult",
    timings: ["christmas_day", "boxing_day"],
    minutes: 60,
    tags: ["Comedy", "TV"],
  },
  {
    key: "the_office_christmas_specials",
    title: "The Office: Christmas Specials",
    year: 2003,
    type: "episode",
    blurb: "The documentary crew returns to see how life has changed for the Slough staff at Christmas.",
    audiences: ["adults_no_children", "couple", "young_adults"],
    moods: ["funny", "nostalgic", "feel_good"],
    ageBand: "adult",
    timings: ["christmas_eve", "christmas_day"],
    minutes: 60,
    tags: ["Comedy", "TV"],
  },
  {
    key: "only_fools_christmas",
    title: "Only Fools and Horses: Christmas Specials",
    type: "episode",
    blurb: "The Trotters' Christmas specials are some of the most watched episodes in British television.",
    audiences: ["adults_no_children", "couple", "extended", "mixed_ages"],
    moods: ["funny", "classic", "nostalgic"],
    ageBand: "adult",
    timings: ["christmas_day", "boxing_day"],
    minutes: 75,
    tags: ["Comedy", "TV"],
  },
  {
    key: "morecambe_wise_christmas",
    title: "The Morecambe & Wise Christmas Show",
    type: "tv_special",
    blurb: "Classic comedy sketches and musical guests from a Christmas variety institution.",
    audiences: ["adults_no_children", "couple", "extended", "mixed_ages"],
    moods: ["funny", "classic", "nostalgic"],
    ageBand: "all",
    timings: ["christmas_day", "boxing_day"],
    minutes: 60,
    tags: ["Comedy", "Classic"],
  },
  {
    key: "ab_fab_christmas",
    title: "Absolutely Fabulous: Christmas Specials",
    type: "episode",
    blurb: "Edina and Patsy navigate Christmas in their own chaotic fashion.",
    audiences: ["adults_no_children", "couple", "young_adults"],
    moods: ["funny", "nostalgic"],
    ageBand: "adult",
    timings: ["christmas_eve"],
    minutes: 60,
    tags: ["Comedy", "TV"],
  },
  {
    key: "blackadder_christmas",
    title: "Blackadder's Christmas Carol",
    year: 1988,
    type: "tv_special",
    blurb: "The nicest man in England is shown what his life would be like if he were less kind.",
    audiences: ["adults_no_children", "couple", "young_adults"],
    moods: ["funny", "classic", "nostalgic"],
    ageBand: "adult",
    timings: ["christmas_eve", "christmas_day"],
    minutes: 43,
    tags: ["Comedy", "Classic"],
  },
  {
    key: "the_snow_queen_bbc",
    title: "The Snow Queen",
    year: 2005,
    type: "tv_special",
    blurb: "A faithful television adaptation of the winter fairy tale.",
    audiences: ["older_children", "teenagers", "mixed_ages"],
    moods: ["magical", "adventure", "nostalgic"],
    ageBand: "8+",
    timings: ["christmas_eve", "december"],
    minutes: 90,
    tags: ["Fantasy", "TV"],
  },
  {
    key: "doctor_who_christmas",
    title: "Doctor Who: Christmas Specials",
    type: "episode",
    blurb: "The Doctor saves Christmas in a variety of times, places and regenerations.",
    audiences: ["older_children", "teenagers", "young_adults", "mixed_ages"],
    moods: ["adventure", "magical", "family"],
    ageBand: "8+",
    timings: ["christmas_day", "boxing_day"],
    minutes: 60,
    tags: ["Adventure", "TV"],
  },
  {
    key: "call_the_midwife_christmas",
    title: "Call the Midwife: Christmas Specials",
    type: "episode",
    blurb: "The midwives of Poplar deliver Christmas babies and community warmth in 1950s East London.",
    audiences: ["adults_no_children", "couple", "extended", "mixed_ages"],
    moods: ["tearjerker", "feel_good", "nostalgic"],
    ageBand: "12+",
    timings: ["christmas_day", "boxing_day"],
    minutes: 75,
    tags: ["Drama", "TV"],
  },
  {
    key: "downton_abbey_christmas",
    title: "Downton Abbey: Christmas Specials",
    type: "episode",
    blurb: "The Crawley family and staff mark the season in grand Edwardian style.",
    audiences: ["adults_no_children", "couple", "extended"],
    moods: ["classic", "nostalgic", "tearjerker"],
    ageBand: "adult",
    timings: ["christmas_day", "boxing_day"],
    minutes: 90,
    tags: ["Drama", "TV"],
  },
  {
    key: "the_chase_christmas",
    title: "The Chase: Celebrity Christmas Specials",
    type: "tv_special",
    blurb: "Famous faces face the Chaser for a Christmas charity prize.",
    audiences: ["adults_no_children", "couple", "extended", "mixed_ages"],
    moods: ["funny", "easy", "family"],
    ageBand: "all",
    timings: ["christmas_day", "boxing_day"],
    minutes: 60,
    tags: ["Quiz", "Easy"],
  },
  {
    key: "strictly_christmas",
    title: "Strictly Come Dancing: Christmas Special",
    type: "tv_special",
    blurb: "Past contestants return for a one-off Christmas ballroom competition.",
    audiences: ALL,
    moods: ["musical", "family", "easy"],
    ageBand: "all",
    timings: ["christmas_day", "boxing_day"],
    minutes: 75,
    tags: ["Musical", "TV"],
  },
  {
    key: "the_gruffalo_christmas",
    title: "The Gruffalo and the Gruffalo's Child",
    year: 2009,
    type: "tv_special",
    blurb: "A mouse meets a monster in the woods, and later a brave child explores a snowy forest.",
    audiences: ["young_children", "older_children", "mixed_ages"],
    moods: ["animated", "family", "magical"],
    ageBand: "all",
    timings: ["christmas_eve", "december"],
    minutes: 27,
    tags: ["Animated", "Short"],
  },
  {
    key: "julia_donaldson_christmas_collection",
    title: "Julia Donaldson Christmas Story Collection",
    type: "series",
    blurb: "A collection of animated adaptations of the best-known picture books.",
    audiences: ["young_children", "older_children", "mixed_ages"],
    moods: ["animated", "family", "musical"],
    ageBand: "all",
    timings: ["christmas_eve", "december"],
    tags: ["Animated", "Short"],
  },
  {
    key: "innocents_day",
    title: "The Innocents",
    year: 1961,
    type: "film",
    blurb: "A Gothic ghost story set in a country house at Christmas, based on Henry James.",
    audiences: ["adults_no_children", "couple", "alone"],
    moods: ["classic", "nostalgic", "cosy"],
    ageBand: "adult",
    timings: ["christmas_eve"],
    minutes: 100,
    tags: ["Classic", "Atmospheric"],
  },
  {
    key: "the_apartment",
    title: "The Apartment",
    year: 1960,
    type: "film",
    blurb: "An office worker lends his apartment to executives, leading to a Christmas Eve romance.",
    audiences: ["adults_no_children", "couple", "alone"],
    moods: ["classic", "romantic", "feel_good"],
    ageBand: "adult",
    timings: ["christmas_eve"],
    minutes: 125,
    tags: ["Classic", "Romantic"],
  },

  // ---- Background / easy / comfort viewing ----------------------------------
  {
    key: "mariah_carey_christmas",
    title: "Mariah Carey: Merry Christmas to All",
    year: 2022,
    type: "tv_special",
    blurb: "A concert of Christmas songs built around the modern holiday anthem.",
    audiences: ALL,
    moods: ["musical", "easy", "family"],
    ageBand: "all",
    timings: ["christmas_eve", "boxing_day", "december"],
    minutes: 90,
    tags: ["Musical", "Easy"],
  },
  {
    key: "carols_from_kings",
    title: "Carols from King's",
    type: "tv_special",
    blurb: "The famous Christmas Eve service of nine lessons and carols from King's College, Cambridge.",
    audiences: ["adults_no_children", "couple", "extended", "alone"],
    moods: ["musical", "classic", "cosy"],
    ageBand: "all",
    timings: ["christmas_eve"],
    minutes: 90,
    tags: ["Musical", "Traditional"],
  },
  {
    key: "queens_speech",
    title: "The King's Christmas Broadcast",
    type: "tv_special",
    blurb: "The annual Christmas Day message from the monarch.",
    audiences: ["adults_no_children", "extended", "alone"],
    moods: ["classic", "easy", "nostalgic"],
    ageBand: "all",
    timings: ["christmas_day"],
    minutes: 10,
    tags: ["Tradition", "Short"],
  },
  {
    key: "royal_variety_performance",
    title: "Royal Variety Performance",
    type: "tv_special",
    blurb: "An annual variety show held in the presence of royalty, usually in December.",
    audiences: ALL,
    moods: ["musical", "funny", "easy"],
    ageBand: "all",
    timings: ["december"],
    minutes: 120,
    tags: ["Variety", "Easy"],
  },
  {
    key: "blue_planet_christmas",
    title: "Blue Planet II: Festive viewing",
    type: "series",
    blurb: "A calm, beautiful nature series that works well as relaxed Christmas viewing.",
    audiences: ["older_children", "teenagers", "adults_no_children", "couple", "mixed_ages"],
    moods: ["easy", "feel_good", "family"],
    ageBand: "all",
    timings: ["boxing_day", "weekend"],
    tags: ["Nature", "Easy"],
  },
  {
    key: "bake_off_christmas",
    title: "The Great British Bake Off: Christmas Specials",
    type: "tv_special",
    blurb: "Past bakers return to compete in a festive tent, perfect for gentle viewing.",
    audiences: ALL,
    moods: ["easy", "feel_good", "family"],
    ageBand: "all",
    timings: ["christmas_day", "boxing_day", "december"],
    minutes: 75,
    tags: ["Baking", "Easy"],
  },
  {
    key: "kirsties_handmade_christmas",
    title: "Kirstie's Handmade Christmas",
    type: "series",
    blurb: "Crafting, decorating and festive competitions for easy daytime viewing.",
    audiences: ["adults_no_children", "couple", "alone", "extended"],
    moods: ["easy", "cosy", "feel_good"],
    ageBand: "all",
    timings: ["december", "weekend"],
    minutes: 60,
    tags: ["Crafts", "Easy"],
  },
  {
    key: "location_xmas_special",
    title: "Location, Location, Location: Christmas Specials",
    type: "tv_special",
    blurb: "Property-hunting wrapped up with a Christmas bow.",
    audiences: ["adults_no_children", "couple", "alone"],
    moods: ["easy", "cosy"],
    ageBand: "all",
    timings: ["december", "boxing_day"],
    minutes: 60,
    tags: ["Property", "Easy"],
  },

  // ---- Alone / comfort / indulgent ------------------------------------------
  {
    key: "christmas_in_connecticut",
    title: "Christmas in Connecticut",
    year: 1945,
    type: "film",
    blurb: "A food writer must pretend to be a perfect country wife over Christmas.",
    audiences: ["adults_no_children", "alone", "couple"],
    moods: ["classic", "romantic", "funny"],
    ageBand: "adult",
    timings: ["christmas_eve", "december"],
    minutes: 101,
    tags: ["Classic", "Romantic"],
  },
  {
    key: "the_shop_around_the_corner",
    title: "The Shop Around the Corner",
    year: 1940,
    type: "film",
    blurb: "Two shop clerks fall in love as anonymous pen pals, not knowing they work together.",
    audiences: ["adults_no_children", "alone", "couple"],
    moods: ["classic", "romantic", "nostalgic"],
    ageBand: "adult",
    timings: ["december", "christmas_eve"],
    minutes: 99,
    tags: ["Classic", "Romantic"],
  },
  {
    key: "an_american_in_paris",
    title: "An American in Paris",
    year: 1951,
    type: "film",
    blurb: "A painter in Paris dreams of love and success over a lush musical Christmas.",
    audiences: ["adults_no_children", "alone", "couple"],
    moods: ["musical", "classic", "romantic"],
    ageBand: "adult",
    timings: ["boxing_day", "weekend"],
    minutes: 113,
    tags: ["Musical", "Classic"],
  },
  {
    key: "sleepless_in_seattle",
    title: "Sleepless in Seattle",
    year: 1993,
    type: "film",
    blurb: "A lonely widower and a Baltimore reporter are drawn together around the Christmas season.",
    audiences: ["adults_no_children", "alone", "couple"],
    moods: ["romantic", "feel_good", "nostalgic"],
    ageBand: "adult",
    timings: ["christmas_eve", "december"],
    minutes: 105,
    tags: ["Romantic", "Feel-good"],
  },
  {
    key: "single_all_the_way",
    title: "Single All the Way",
    year: 2021,
    type: "film",
    blurb: "A man brings his best friend home as his fake boyfriend for Christmas.",
    audiences: ["adults_no_children", "alone", "couple", "young_adults"],
    moods: ["romantic", "funny", "newer"],
    ageBand: "adult",
    timings: ["christmas_eve", "december"],
    minutes: 99,
    tags: ["Romantic", "Newer"],
  },
  {
    key: "happiest_season",
    title: "Happiest Season",
    year: 2020,
    type: "film",
    blurb: "A woman brings her girlfriend home for Christmas, but her family doesn't know she is gay.",
    audiences: ["adults_no_children", "alone", "couple", "young_adults"],
    moods: ["romantic", "funny", "newer"],
    ageBand: "adult",
    timings: ["christmas_eve", "december"],
    minutes: 102,
    tags: ["Romantic", "Newer"],
  },
  {
    key: "carol",
    title: "Carol",
    year: 2015,
    type: "film",
    blurb: "A glamorous older woman and a young photographer fall in love in 1950s New York at Christmas.",
    audiences: ["adults_no_children", "alone", "couple"],
    moods: ["romantic", "tearjerker", "classic"],
    ageBand: "adult",
    timings: ["christmas_eve", "december"],
    minutes: 118,
    tags: ["Romantic", "Drama"],
  },
  {
    key: "its_a_wonderful_life_alone",
    title: "It's a Wonderful Life",
    year: 1946,
    type: "film",
    blurb: "A reminder that one life touches many others — ideal for a quiet Christmas evening alone.",
    audiences: ["alone", "adults_no_children", "couple"],
    moods: ["classic", "tearjerker", "feel_good"],
    ageBand: "adult",
    timings: ["christmas_eve"],
    minutes: 130,
    tags: ["Classic", "Comfort"],
  },
  {
    key: "all_creatures_christmas",
    title: "All Creatures Great and Small: Christmas Specials",
    type: "episode",
    blurb: "Gentle Yorkshire veterinary stories with a Christmas warmth.",
    audiences: ["adults_no_children", "alone", "couple", "extended"],
    moods: ["cosy", "easy", "nostalgic"],
    ageBand: "all",
    timings: ["christmas_day", "boxing_day"],
    minutes: 60,
    tags: ["Cosy", "TV"],
  },
  {
    key: "winter_sonata",
    title: "Winter Sonata",
    year: 2002,
    type: "series",
    blurb: "A Korean winter romance with snow, memory and a long love story.",
    audiences: ["adults_no_children", "alone", "couple"],
    moods: ["romantic", "tearjerker", "nostalgic"],
    ageBand: "adult",
    timings: ["december", "weekend"],
    tags: ["Romantic", "Series"],
  },
  {
    key: "queen_gambit",
    title: "The Queen's Gambit",
    year: 2020,
    type: "series",
    blurb: "A tense, stylish chess drama that became a perfect binge-watch over the winter holidays.",
    audiences: ["adults_no_children", "alone", "couple", "young_adults"],
    moods: ["newer", "tearjerker", "easy"],
    ageBand: "adult",
    timings: ["december", "weekend"],
    tags: ["Drama", "Series"],
  },

  // ---- More modern festive favourites ---------------------------------------
  {
    key: "the_holiday_calendar",
    title: "The Holiday Calendar",
    year: 2018,
    type: "film",
    blurb: "A photographer inherits an advent calendar that seems to predict the future.",
    audiences: ["couple", "young_adults", "adults_no_children"],
    moods: ["romantic", "magical", "newer"],
    ageBand: "all",
    timings: ["december"],
    minutes: 95,
    tags: ["Romantic", "Newer"],
  },
  {
    key: "christmas_inheritance",
    title: "Christmas Inheritance",
    year: 2017,
    type: "film",
    blurb: "A party girl must spend Christmas in her father's small hometown to inherit his business.",
    audiences: ["couple", "young_adults", "adults_no_children"],
    moods: ["romantic", "feel_good", "newer"],
    ageBand: "all",
    timings: ["december"],
    minutes: 104,
    tags: ["Romantic", "Newer"],
  },
  {
    key: "a_bad_moms_christmas",
    title: "A Bad Moms Christmas",
    year: 2017,
    type: "film",
    blurb: "Three mothers rebel against the perfect Christmas while their own mothers visit.",
    audiences: ["adults_no_children", "couple", "young_adults"],
    moods: ["funny", "newer", "easy"],
    ageBand: "adult",
    timings: ["december", "christmas_eve"],
    minutes: 104,
    tags: ["Comedy", "Newer"],
  },
  {
    key: "office_christmas_party",
    title: "Office Christmas Party",
    year: 2016,
    type: "film",
    blurb: "A branch manager throws a wild Christmas party to save the company from closure.",
    audiences: ["adults_no_children", "young_adults", "couple"],
    moods: ["funny", "newer", "easy"],
    ageBand: "adult",
    timings: ["december"],
    minutes: 105,
    tags: ["Comedy", "Newer"],
  },
  {
    key: "bad_santa",
    title: "Bad Santa",
    year: 2003,
    type: "film",
    blurb: "A con man poses as a department-store Santa to rob shopping malls.",
    audiences: ["adults_no_children", "young_adults", "alone"],
    moods: ["funny", "nostalgic", "newer"],
    ageBand: "adult",
    timings: ["december", "christmas_eve"],
    minutes: 91,
    tags: ["Dark comedy", "Newer"],
  },
  {
    key: "kringle_kringle",
    title: "Klaus",
    year: 2019,
    type: "film",
    blurb: "An origin story of Santa told through a friendship between a postman and a toymaker.",
    audiences: FAMILY_MIX,
    moods: ["animated", "feel_good", "newer"],
    ageBand: "all",
    timings: ["christmas_eve", "christmas_day"],
    minutes: 96,
    tags: ["Animated", "Newer"],
  },
  {
    key: "christmas_project",
    title: "The Christmas Project",
    year: 2016,
    type: "film",
    blurb: "A family of brothers is assigned to secretly befriend the school bullies at Christmas.",
    audiences: ["older_children", "teenagers", "mixed_ages", "young_children"],
    moods: ["family", "feel_good", "newer"],
    ageBand: "all",
    timings: ["december"],
    minutes: 92,
    tags: ["Family", "Newer"],
  },
  {
    key: "dolly_parton_christmas",
    title: "Dolly Parton's Christmas on the Square",
    year: 2020,
    type: "film",
    blurb: "A wealthy woman returns to sell her hometown, until Christmas spirits intervene.",
    audiences: ["adults_no_children", "couple", "extended", "mixed_ages"],
    moods: ["musical", "feel_good", "newer"],
    ageBand: "all",
    timings: ["december"],
    minutes: 98,
    tags: ["Musical", "Newer"],
  },
  {
    key: "jingle_jangle",
    title: "Jingle Jangle: A Christmas Journey",
    year: 2020,
    type: "film",
    blurb: "A toymaker's granddaughter brings magic back to his workshop at Christmas.",
    audiences: FAMILY_MIX,
    moods: ["musical", "magical", "newer"],
    ageBand: "all",
    timings: ["christmas_day", "christmas_eve"],
    minutes: 122,
    tags: ["Musical", "Newer"],
  },
  {
    key: "noelle_2",
    title: "Noelle",
    year: 2019,
    type: "film",
    blurb: "Santa's daughter must find her missing brother before Christmas Eve.",
    audiences: FAMILY_MIX,
    moods: ["magical", "funny", "newer"],
    ageBand: "all",
    timings: ["christmas_eve", "december"],
    minutes: 100,
    tags: ["Magical", "Newer"],
  },
  {
    key: "the_princess_switcharoo",
    title: "The Princess Switch: Romancing the Star",
    year: 2021,
    type: "film",
    blurb: "A stolen Christmas relic brings all three lookalikes together in one royal adventure.",
    audiences: ["teenagers", "young_adults", "couple", "mixed_ages"],
    moods: ["romantic", "funny", "newer"],
    ageBand: "all",
    timings: ["december"],
    minutes: 92,
    tags: ["Romantic", "Newer"],
  },
  {
    key: "christmas_chronicles",
    title: "The Christmas Chronicles",
    year: 2018,
    type: "film",
    blurb: "Two siblings try to catch Santa on camera and accidentally derail his Christmas Eve run.",
    audiences: FAMILY_MIX,
    moods: ["adventure", "magical", "newer"],
    ageBand: "all",
    timings: ["christmas_eve", "christmas_day"],
    minutes: 104,
    tags: ["Adventure", "Newer"],
  },
  {
    key: "christmas_chronicles_2",
    title: "The Christmas Chronicles 2",
    year: 2020,
    type: "film",
    blurb: "Kate Pierce returns to the North Pole to save Christmas from a fallen elf.",
    audiences: FAMILY_MIX,
    moods: ["adventure", "magical", "newer"],
    ageBand: "all",
    timings: ["christmas_eve", "christmas_day"],
    minutes: 112,
    tags: ["Adventure", "Newer"],
  },
  {
    key: "the_rescue_2019",
    title: "The Rescue",
    year: 2021,
    type: "film",
    blurb: "A documentary about the Tham Luang cave rescue, a gripping winter evening watch.",
    audiences: ["adults_no_children", "alone", "couple"],
    moods: ["tearjerker", "newer", "feel_good"],
    ageBand: "adult",
    timings: ["boxing_day", "weekend"],
    minutes: 107,
    tags: ["Documentary", "Newer"],
  },
];
