/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VipRouteImport } from './routes/vip'
import { Route as SaveRouteImport } from './routes/save'
import { Route as InspireRouteImport } from './routes/inspire'
import { Route as GiftFinderRouteImport } from './routes/gift-finder'
import { Route as FoodRouteImport } from './routes/food'
import { Route as EntertainmentRouteImport } from './routes/entertainment'
import { Route as DaysOutRouteImport } from './routes/days-out'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPlannerRouteImport } from './routes/_authenticated/planner'
import { Route as AuthenticatedPlannerIndexRouteImport } from './routes/_authenticated/planner.index'
import { Route as AuthenticatedPlannerTodosRouteImport } from './routes/_authenticated/planner.todos'
import { Route as AuthenticatedPlannerRemindersRouteImport } from './routes/_authenticated/planner.reminders'
import { Route as AuthenticatedPlannerGiftsRouteImport } from './routes/_authenticated/planner.gifts'
import { Route as AuthenticatedPlannerCardsRouteImport } from './routes/_authenticated/planner.cards'

const VipRoute = VipRouteImport.update({
  id: '/vip',
  path: '/vip',
  getParentRoute: () => rootRouteImport,
} as any)
const SaveRoute = SaveRouteImport.update({
  id: '/save',
  path: '/save',
  getParentRoute: () => rootRouteImport,
} as any)
const InspireRoute = InspireRouteImport.update({
  id: '/inspire',
  path: '/inspire',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftFinderRoute = GiftFinderRouteImport.update({
  id: '/gift-finder',
  path: '/gift-finder',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodRoute = FoodRouteImport.update({
  id: '/food',
  path: '/food',
  getParentRoute: () => rootRouteImport,
} as any)
const EntertainmentRoute = EntertainmentRouteImport.update({
  id: '/entertainment',
  path: '/entertainment',
  getParentRoute: () => rootRouteImport,
} as any)
const DaysOutRoute = DaysOutRouteImport.update({
  id: '/days-out',
  path: '/days-out',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPlannerRoute = AuthenticatedPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlannerIndexRoute =
  AuthenticatedPlannerIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPlannerRoute,
  } as any)
const AuthenticatedPlannerTodosRoute =
  AuthenticatedPlannerTodosRouteImport.update({
    id: '/todos',
    path: '/todos',
    getParentRoute: () => AuthenticatedPlannerRoute,
  } as any)
const AuthenticatedPlannerRemindersRoute =
  AuthenticatedPlannerRemindersRouteImport.update({
    id: '/reminders',
    path: '/reminders',
    getParentRoute: () => AuthenticatedPlannerRoute,
  } as any)
const AuthenticatedPlannerGiftsRoute =
  AuthenticatedPlannerGiftsRouteImport.update({
    id: '/gifts',
    path: '/gifts',
    getParentRoute: () => AuthenticatedPlannerRoute,
  } as any)
const AuthenticatedPlannerCardsRoute =
  AuthenticatedPlannerCardsRouteImport.update({
    id: '/cards',
    path: '/cards',
    getParentRoute: () => AuthenticatedPlannerRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/days-out': typeof DaysOutRoute
  '/entertainment': typeof EntertainmentRoute
  '/food': typeof FoodRoute
  '/gift-finder': typeof GiftFinderRoute
  '/inspire': typeof InspireRoute
  '/save': typeof SaveRoute
  '/vip': typeof VipRoute
  '/planner': typeof AuthenticatedPlannerRouteWithChildren
  '/planner/cards': typeof AuthenticatedPlannerCardsRoute
  '/planner/gifts': typeof AuthenticatedPlannerGiftsRoute
  '/planner/reminders': typeof AuthenticatedPlannerRemindersRoute
  '/planner/todos': typeof AuthenticatedPlannerTodosRoute
  '/planner/': typeof AuthenticatedPlannerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/days-out': typeof DaysOutRoute
  '/entertainment': typeof EntertainmentRoute
  '/food': typeof FoodRoute
  '/gift-finder': typeof GiftFinderRoute
  '/inspire': typeof InspireRoute
  '/save': typeof SaveRoute
  '/vip': typeof VipRoute
  '/planner/cards': typeof AuthenticatedPlannerCardsRoute
  '/planner/gifts': typeof AuthenticatedPlannerGiftsRoute
  '/planner/reminders': typeof AuthenticatedPlannerRemindersRoute
  '/planner/todos': typeof AuthenticatedPlannerTodosRoute
  '/planner': typeof AuthenticatedPlannerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/days-out': typeof DaysOutRoute
  '/entertainment': typeof EntertainmentRoute
  '/food': typeof FoodRoute
  '/gift-finder': typeof GiftFinderRoute
  '/inspire': typeof InspireRoute
  '/save': typeof SaveRoute
  '/vip': typeof VipRoute
  '/_authenticated/planner': typeof AuthenticatedPlannerRouteWithChildren
  '/_authenticated/planner/cards': typeof AuthenticatedPlannerCardsRoute
  '/_authenticated/planner/gifts': typeof AuthenticatedPlannerGiftsRoute
  '/_authenticated/planner/reminders': typeof AuthenticatedPlannerRemindersRoute
  '/_authenticated/planner/todos': typeof AuthenticatedPlannerTodosRoute
  '/_authenticated/planner/': typeof AuthenticatedPlannerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/auth'
    | '/days-out'
    | '/entertainment'
    | '/food'
    | '/gift-finder'
    | '/inspire'
    | '/save'
    | '/vip'
    | '/planner'
    | '/planner/cards'
    | '/planner/gifts'
    | '/planner/reminders'
    | '/planner/todos'
    | '/planner/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/auth'
    | '/days-out'
    | '/entertainment'
    | '/food'
    | '/gift-finder'
    | '/inspire'
    | '/save'
    | '/vip'
    | '/planner/cards'
    | '/planner/gifts'
    | '/planner/reminders'
    | '/planner/todos'
    | '/planner'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/assistant'
    | '/auth'
    | '/days-out'
    | '/entertainment'
    | '/food'
    | '/gift-finder'
    | '/inspire'
    | '/save'
    | '/vip'
    | '/_authenticated/planner'
    | '/_authenticated/planner/cards'
    | '/_authenticated/planner/gifts'
    | '/_authenticated/planner/reminders'
    | '/_authenticated/planner/todos'
    | '/_authenticated/planner/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AssistantRoute: typeof AssistantRoute
  AuthRoute: typeof AuthRoute
  DaysOutRoute: typeof DaysOutRoute
  EntertainmentRoute: typeof EntertainmentRoute
  FoodRoute: typeof FoodRoute
  GiftFinderRoute: typeof GiftFinderRoute
  InspireRoute: typeof InspireRoute
  SaveRoute: typeof SaveRoute
  VipRoute: typeof VipRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vip': {
      id: '/vip'
      path: '/vip'
      fullPath: '/vip'
      preLoaderRoute: typeof VipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/save': {
      id: '/save'
      path: '/save'
      fullPath: '/save'
      preLoaderRoute: typeof SaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspire': {
      id: '/inspire'
      path: '/inspire'
      fullPath: '/inspire'
      preLoaderRoute: typeof InspireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gift-finder': {
      id: '/gift-finder'
      path: '/gift-finder'
      fullPath: '/gift-finder'
      preLoaderRoute: typeof GiftFinderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food': {
      id: '/food'
      path: '/food'
      fullPath: '/food'
      preLoaderRoute: typeof FoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entertainment': {
      id: '/entertainment'
      path: '/entertainment'
      fullPath: '/entertainment'
      preLoaderRoute: typeof EntertainmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/days-out': {
      id: '/days-out'
      path: '/days-out'
      fullPath: '/days-out'
      preLoaderRoute: typeof DaysOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/planner': {
      id: '/_authenticated/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof AuthenticatedPlannerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planner/': {
      id: '/_authenticated/planner/'
      path: '/'
      fullPath: '/planner/'
      preLoaderRoute: typeof AuthenticatedPlannerIndexRouteImport
      parentRoute: typeof AuthenticatedPlannerRoute
    }
    '/_authenticated/planner/todos': {
      id: '/_authenticated/planner/todos'
      path: '/todos'
      fullPath: '/planner/todos'
      preLoaderRoute: typeof AuthenticatedPlannerTodosRouteImport
      parentRoute: typeof AuthenticatedPlannerRoute
    }
    '/_authenticated/planner/reminders': {
      id: '/_authenticated/planner/reminders'
      path: '/reminders'
      fullPath: '/planner/reminders'
      preLoaderRoute: typeof AuthenticatedPlannerRemindersRouteImport
      parentRoute: typeof AuthenticatedPlannerRoute
    }
    '/_authenticated/planner/gifts': {
      id: '/_authenticated/planner/gifts'
      path: '/gifts'
      fullPath: '/planner/gifts'
      preLoaderRoute: typeof AuthenticatedPlannerGiftsRouteImport
      parentRoute: typeof AuthenticatedPlannerRoute
    }
    '/_authenticated/planner/cards': {
      id: '/_authenticated/planner/cards'
      path: '/cards'
      fullPath: '/planner/cards'
      preLoaderRoute: typeof AuthenticatedPlannerCardsRouteImport
      parentRoute: typeof AuthenticatedPlannerRoute
    }
  }
}

interface AuthenticatedPlannerRouteChildren {
  AuthenticatedPlannerCardsRoute: typeof AuthenticatedPlannerCardsRoute
  AuthenticatedPlannerGiftsRoute: typeof AuthenticatedPlannerGiftsRoute
  AuthenticatedPlannerRemindersRoute: typeof AuthenticatedPlannerRemindersRoute
  AuthenticatedPlannerTodosRoute: typeof AuthenticatedPlannerTodosRoute
  AuthenticatedPlannerIndexRoute: typeof AuthenticatedPlannerIndexRoute
}

const AuthenticatedPlannerRouteChildren: AuthenticatedPlannerRouteChildren = {
  AuthenticatedPlannerCardsRoute: AuthenticatedPlannerCardsRoute,
  AuthenticatedPlannerGiftsRoute: AuthenticatedPlannerGiftsRoute,
  AuthenticatedPlannerRemindersRoute: AuthenticatedPlannerRemindersRoute,
  AuthenticatedPlannerTodosRoute: AuthenticatedPlannerTodosRoute,
  AuthenticatedPlannerIndexRoute: AuthenticatedPlannerIndexRoute,
}

const AuthenticatedPlannerRouteWithChildren =
  AuthenticatedPlannerRoute._addFileChildren(AuthenticatedPlannerRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPlannerRoute: typeof AuthenticatedPlannerRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPlannerRoute: AuthenticatedPlannerRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AssistantRoute: AssistantRoute,
  AuthRoute: AuthRoute,
  DaysOutRoute: DaysOutRoute,
  EntertainmentRoute: EntertainmentRoute,
  FoodRoute: FoodRoute,
  GiftFinderRoute: GiftFinderRoute,
  InspireRoute: InspireRoute,
  SaveRoute: SaveRoute,
  VipRoute: VipRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
