/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VipRouteImport } from './routes/vip'
import { Route as SaveRouteImport } from './routes/save'
import { Route as PetsRouteImport } from './routes/pets'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as InspireRouteImport } from './routes/inspire'
import { Route as GiftFinderRouteImport } from './routes/gift-finder'
import { Route as FoodRouteImport } from './routes/food'
import { Route as EntertainmentRouteImport } from './routes/entertainment'
import { Route as DaysOutRouteImport } from './routes/days-out'
import { Route as ComingSoonRouteImport } from './routes/coming-soon'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeachersIndexRouteImport } from './routes/teachers.index'
import { Route as TeachersGenerateRouteImport } from './routes/teachers.generate'
import { Route as TeachersCategoryRouteImport } from './routes/teachers.$category'
import { Route as AuthenticatedPlannerRouteImport } from './routes/_authenticated/planner'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedPlannerIndexRouteImport } from './routes/_authenticated/planner.index'
import { Route as AuthenticatedPlannerTodosRouteImport } from './routes/_authenticated/planner.todos'
import { Route as AuthenticatedPlannerTimelineRouteImport } from './routes/_authenticated/planner.timeline'
import { Route as AuthenticatedPlannerSetupRouteImport } from './routes/_authenticated/planner.setup'
import { Route as AuthenticatedPlannerRemindersRouteImport } from './routes/_authenticated/planner.reminders'
import { Route as AuthenticatedPlannerPeopleRouteImport } from './routes/_authenticated/planner.people'
import { Route as AuthenticatedPlannerListRouteImport } from './routes/_authenticated/planner.list'
import { Route as AuthenticatedPlannerHelperRouteImport } from './routes/_authenticated/planner.helper'
import { Route as AuthenticatedPlannerGiftsRouteImport } from './routes/_authenticated/planner.gifts'
import { Route as AuthenticatedPlannerCardsRouteImport } from './routes/_authenticated/planner.cards'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as AuthenticatedPlannerPeopleIndexRouteImport } from './routes/_authenticated/planner.people.index'
import { Route as AuthenticatedPlannerPeoplePersonIdRouteImport } from './routes/_authenticated/planner.people.$personId'

const VipRoute = VipRouteImport.update({
  id: '/vip',
  path: '/vip',
  getParentRoute: () => rootRouteImport,
} as any)
const SaveRoute = SaveRouteImport.update({
  id: '/save',
  path: '/save',
  getParentRoute: () => rootRouteImport,
} as any)
const PetsRoute = PetsRouteImport.update({
  id: '/pets',
  path: '/pets',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const InspireRoute = InspireRouteImport.update({
  id: '/inspire',
  path: '/inspire',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftFinderRoute = GiftFinderRouteImport.update({
  id: '/gift-finder',
  path: '/gift-finder',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodRoute = FoodRouteImport.update({
  id: '/food',
  path: '/food',
  getParentRoute: () => rootRouteImport,
} as any)
const EntertainmentRoute = EntertainmentRouteImport.update({
  id: '/entertainment',
  path: '/entertainment',
  getParentRoute: () => rootRouteImport,
} as any)
const DaysOutRoute = DaysOutRouteImport.update({
  id: '/days-out',
  path: '/days-out',
  getParentRoute: () => rootRouteImport,
} as any)
const ComingSoonRoute = ComingSoonRouteImport.update({
  id: '/coming-soon',
  path: '/coming-soon',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachersIndexRoute = TeachersIndexRouteImport.update({
  id: '/teachers/',
  path: '/teachers/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachersGenerateRoute = TeachersGenerateRouteImport.update({
  id: '/teachers/generate',
  path: '/teachers/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachersCategoryRoute = TeachersCategoryRouteImport.update({
  id: '/teachers/$category',
  path: '/teachers/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPlannerRoute = AuthenticatedPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedPlannerIndexRoute =
  AuthenticatedPlannerIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPlannerRoute,
  } as any)
const AuthenticatedPlannerTodosRoute =
  AuthenticatedPlannerTodosRouteImport.update({
    id: '/todos',
    path: '/todos',
    getParentRoute: () => AuthenticatedPlannerRoute,
  } as any)
const AuthenticatedPlannerTimelineRoute =
  AuthenticatedPlannerTimelineRouteImport.update({
    id: '/timeline',
    path: '/timeline',
    getParentRoute: () => AuthenticatedPlannerRoute,
  } as any)
const AuthenticatedPlannerSetupRoute =
  AuthenticatedPlannerSetupRouteImport.update({
    id: '/setup',
    path: '/setup',
    getParentRoute: () => AuthenticatedPlannerRoute,
  } as any)
const AuthenticatedPlannerRemindersRoute =
  AuthenticatedPlannerRemindersRouteImport.update({
    id: '/reminders',
    path: '/reminders',
    getParentRoute: () => AuthenticatedPlannerRoute,
  } as any)
const AuthenticatedPlannerPeopleRoute =
  AuthenticatedPlannerPeopleRouteImport.update({
    id: '/people',
    path: '/people',
    getParentRoute: () => AuthenticatedPlannerRoute,
  } as any)
const AuthenticatedPlannerListRoute =
  AuthenticatedPlannerListRouteImport.update({
    id: '/list',
    path: '/list',
    getParentRoute: () => AuthenticatedPlannerRoute,
  } as any)
const AuthenticatedPlannerHelperRoute =
  AuthenticatedPlannerHelperRouteImport.update({
    id: '/helper',
    path: '/helper',
    getParentRoute: () => AuthenticatedPlannerRoute,
  } as any)
const AuthenticatedPlannerGiftsRoute =
  AuthenticatedPlannerGiftsRouteImport.update({
    id: '/gifts',
    path: '/gifts',
    getParentRoute: () => AuthenticatedPlannerRoute,
  } as any)
const AuthenticatedPlannerCardsRoute =
  AuthenticatedPlannerCardsRouteImport.update({
    id: '/cards',
    path: '/cards',
    getParentRoute: () => AuthenticatedPlannerRoute,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPlannerPeopleIndexRoute =
  AuthenticatedPlannerPeopleIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPlannerPeopleRoute,
  } as any)
const AuthenticatedPlannerPeoplePersonIdRoute =
  AuthenticatedPlannerPeoplePersonIdRouteImport.update({
    id: '/$personId',
    path: '/$personId',
    getParentRoute: () => AuthenticatedPlannerPeopleRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/coming-soon': typeof ComingSoonRoute
  '/days-out': typeof DaysOutRoute
  '/entertainment': typeof EntertainmentRoute
  '/food': typeof FoodRoute
  '/gift-finder': typeof GiftFinderRoute
  '/inspire': typeof InspireRoute
  '/mcp': typeof McpRoute
  '/partners': typeof PartnersRoute
  '/pets': typeof PetsRoute
  '/save': typeof SaveRoute
  '/vip': typeof VipRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/planner': typeof AuthenticatedPlannerRouteWithChildren
  '/teachers/$category': typeof TeachersCategoryRoute
  '/teachers/generate': typeof TeachersGenerateRoute
  '/teachers/': typeof TeachersIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/planner/cards': typeof AuthenticatedPlannerCardsRoute
  '/planner/gifts': typeof AuthenticatedPlannerGiftsRoute
  '/planner/helper': typeof AuthenticatedPlannerHelperRoute
  '/planner/list': typeof AuthenticatedPlannerListRoute
  '/planner/people': typeof AuthenticatedPlannerPeopleRouteWithChildren
  '/planner/reminders': typeof AuthenticatedPlannerRemindersRoute
  '/planner/setup': typeof AuthenticatedPlannerSetupRoute
  '/planner/timeline': typeof AuthenticatedPlannerTimelineRoute
  '/planner/todos': typeof AuthenticatedPlannerTodosRoute
  '/planner/': typeof AuthenticatedPlannerIndexRoute
  '/planner/people/$personId': typeof AuthenticatedPlannerPeoplePersonIdRoute
  '/planner/people/': typeof AuthenticatedPlannerPeopleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/coming-soon': typeof ComingSoonRoute
  '/days-out': typeof DaysOutRoute
  '/entertainment': typeof EntertainmentRoute
  '/food': typeof FoodRoute
  '/gift-finder': typeof GiftFinderRoute
  '/inspire': typeof InspireRoute
  '/mcp': typeof McpRoute
  '/partners': typeof PartnersRoute
  '/pets': typeof PetsRoute
  '/save': typeof SaveRoute
  '/vip': typeof VipRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/teachers/$category': typeof TeachersCategoryRoute
  '/teachers/generate': typeof TeachersGenerateRoute
  '/teachers': typeof TeachersIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/planner/cards': typeof AuthenticatedPlannerCardsRoute
  '/planner/gifts': typeof AuthenticatedPlannerGiftsRoute
  '/planner/helper': typeof AuthenticatedPlannerHelperRoute
  '/planner/list': typeof AuthenticatedPlannerListRoute
  '/planner/reminders': typeof AuthenticatedPlannerRemindersRoute
  '/planner/setup': typeof AuthenticatedPlannerSetupRoute
  '/planner/timeline': typeof AuthenticatedPlannerTimelineRoute
  '/planner/todos': typeof AuthenticatedPlannerTodosRoute
  '/planner': typeof AuthenticatedPlannerIndexRoute
  '/planner/people/$personId': typeof AuthenticatedPlannerPeoplePersonIdRoute
  '/planner/people': typeof AuthenticatedPlannerPeopleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/coming-soon': typeof ComingSoonRoute
  '/days-out': typeof DaysOutRoute
  '/entertainment': typeof EntertainmentRoute
  '/food': typeof FoodRoute
  '/gift-finder': typeof GiftFinderRoute
  '/inspire': typeof InspireRoute
  '/mcp': typeof McpRoute
  '/partners': typeof PartnersRoute
  '/pets': typeof PetsRoute
  '/save': typeof SaveRoute
  '/vip': typeof VipRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/planner': typeof AuthenticatedPlannerRouteWithChildren
  '/teachers/$category': typeof TeachersCategoryRoute
  '/teachers/generate': typeof TeachersGenerateRoute
  '/teachers/': typeof TeachersIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/planner/cards': typeof AuthenticatedPlannerCardsRoute
  '/_authenticated/planner/gifts': typeof AuthenticatedPlannerGiftsRoute
  '/_authenticated/planner/helper': typeof AuthenticatedPlannerHelperRoute
  '/_authenticated/planner/list': typeof AuthenticatedPlannerListRoute
  '/_authenticated/planner/people': typeof AuthenticatedPlannerPeopleRouteWithChildren
  '/_authenticated/planner/reminders': typeof AuthenticatedPlannerRemindersRoute
  '/_authenticated/planner/setup': typeof AuthenticatedPlannerSetupRoute
  '/_authenticated/planner/timeline': typeof AuthenticatedPlannerTimelineRoute
  '/_authenticated/planner/todos': typeof AuthenticatedPlannerTodosRoute
  '/_authenticated/planner/': typeof AuthenticatedPlannerIndexRoute
  '/_authenticated/planner/people/$personId': typeof AuthenticatedPlannerPeoplePersonIdRoute
  '/_authenticated/planner/people/': typeof AuthenticatedPlannerPeopleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/auth'
    | '/coming-soon'
    | '/days-out'
    | '/entertainment'
    | '/food'
    | '/gift-finder'
    | '/inspire'
    | '/mcp'
    | '/partners'
    | '/pets'
    | '/save'
    | '/vip'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/planner'
    | '/teachers/$category'
    | '/teachers/generate'
    | '/teachers/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/planner/cards'
    | '/planner/gifts'
    | '/planner/helper'
    | '/planner/list'
    | '/planner/people'
    | '/planner/reminders'
    | '/planner/setup'
    | '/planner/timeline'
    | '/planner/todos'
    | '/planner/'
    | '/planner/people/$personId'
    | '/planner/people/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/auth'
    | '/coming-soon'
    | '/days-out'
    | '/entertainment'
    | '/food'
    | '/gift-finder'
    | '/inspire'
    | '/mcp'
    | '/partners'
    | '/pets'
    | '/save'
    | '/vip'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/teachers/$category'
    | '/teachers/generate'
    | '/teachers'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/planner/cards'
    | '/planner/gifts'
    | '/planner/helper'
    | '/planner/list'
    | '/planner/reminders'
    | '/planner/setup'
    | '/planner/timeline'
    | '/planner/todos'
    | '/planner'
    | '/planner/people/$personId'
    | '/planner/people'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/assistant'
    | '/auth'
    | '/coming-soon'
    | '/days-out'
    | '/entertainment'
    | '/food'
    | '/gift-finder'
    | '/inspire'
    | '/mcp'
    | '/partners'
    | '/pets'
    | '/save'
    | '/vip'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/planner'
    | '/teachers/$category'
    | '/teachers/generate'
    | '/teachers/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/planner/cards'
    | '/_authenticated/planner/gifts'
    | '/_authenticated/planner/helper'
    | '/_authenticated/planner/list'
    | '/_authenticated/planner/people'
    | '/_authenticated/planner/reminders'
    | '/_authenticated/planner/setup'
    | '/_authenticated/planner/timeline'
    | '/_authenticated/planner/todos'
    | '/_authenticated/planner/'
    | '/_authenticated/planner/people/$personId'
    | '/_authenticated/planner/people/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AssistantRoute: typeof AssistantRoute
  AuthRoute: typeof AuthRoute
  ComingSoonRoute: typeof ComingSoonRoute
  DaysOutRoute: typeof DaysOutRoute
  EntertainmentRoute: typeof EntertainmentRoute
  FoodRoute: typeof FoodRoute
  GiftFinderRoute: typeof GiftFinderRoute
  InspireRoute: typeof InspireRoute
  McpRoute: typeof McpRoute
  PartnersRoute: typeof PartnersRoute
  PetsRoute: typeof PetsRoute
  SaveRoute: typeof SaveRoute
  VipRoute: typeof VipRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  TeachersCategoryRoute: typeof TeachersCategoryRoute
  TeachersGenerateRoute: typeof TeachersGenerateRoute
  TeachersIndexRoute: typeof TeachersIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vip': {
      id: '/vip'
      path: '/vip'
      fullPath: '/vip'
      preLoaderRoute: typeof VipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/save': {
      id: '/save'
      path: '/save'
      fullPath: '/save'
      preLoaderRoute: typeof SaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pets': {
      id: '/pets'
      path: '/pets'
      fullPath: '/pets'
      preLoaderRoute: typeof PetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspire': {
      id: '/inspire'
      path: '/inspire'
      fullPath: '/inspire'
      preLoaderRoute: typeof InspireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gift-finder': {
      id: '/gift-finder'
      path: '/gift-finder'
      fullPath: '/gift-finder'
      preLoaderRoute: typeof GiftFinderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food': {
      id: '/food'
      path: '/food'
      fullPath: '/food'
      preLoaderRoute: typeof FoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entertainment': {
      id: '/entertainment'
      path: '/entertainment'
      fullPath: '/entertainment'
      preLoaderRoute: typeof EntertainmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/days-out': {
      id: '/days-out'
      path: '/days-out'
      fullPath: '/days-out'
      preLoaderRoute: typeof DaysOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coming-soon': {
      id: '/coming-soon'
      path: '/coming-soon'
      fullPath: '/coming-soon'
      preLoaderRoute: typeof ComingSoonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachers/': {
      id: '/teachers/'
      path: '/teachers'
      fullPath: '/teachers/'
      preLoaderRoute: typeof TeachersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachers/generate': {
      id: '/teachers/generate'
      path: '/teachers/generate'
      fullPath: '/teachers/generate'
      preLoaderRoute: typeof TeachersGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachers/$category': {
      id: '/teachers/$category'
      path: '/teachers/$category'
      fullPath: '/teachers/$category'
      preLoaderRoute: typeof TeachersCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/planner': {
      id: '/_authenticated/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof AuthenticatedPlannerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/planner/': {
      id: '/_authenticated/planner/'
      path: '/'
      fullPath: '/planner/'
      preLoaderRoute: typeof AuthenticatedPlannerIndexRouteImport
      parentRoute: typeof AuthenticatedPlannerRoute
    }
    '/_authenticated/planner/todos': {
      id: '/_authenticated/planner/todos'
      path: '/todos'
      fullPath: '/planner/todos'
      preLoaderRoute: typeof AuthenticatedPlannerTodosRouteImport
      parentRoute: typeof AuthenticatedPlannerRoute
    }
    '/_authenticated/planner/timeline': {
      id: '/_authenticated/planner/timeline'
      path: '/timeline'
      fullPath: '/planner/timeline'
      preLoaderRoute: typeof AuthenticatedPlannerTimelineRouteImport
      parentRoute: typeof AuthenticatedPlannerRoute
    }
    '/_authenticated/planner/setup': {
      id: '/_authenticated/planner/setup'
      path: '/setup'
      fullPath: '/planner/setup'
      preLoaderRoute: typeof AuthenticatedPlannerSetupRouteImport
      parentRoute: typeof AuthenticatedPlannerRoute
    }
    '/_authenticated/planner/reminders': {
      id: '/_authenticated/planner/reminders'
      path: '/reminders'
      fullPath: '/planner/reminders'
      preLoaderRoute: typeof AuthenticatedPlannerRemindersRouteImport
      parentRoute: typeof AuthenticatedPlannerRoute
    }
    '/_authenticated/planner/people': {
      id: '/_authenticated/planner/people'
      path: '/people'
      fullPath: '/planner/people'
      preLoaderRoute: typeof AuthenticatedPlannerPeopleRouteImport
      parentRoute: typeof AuthenticatedPlannerRoute
    }
    '/_authenticated/planner/list': {
      id: '/_authenticated/planner/list'
      path: '/list'
      fullPath: '/planner/list'
      preLoaderRoute: typeof AuthenticatedPlannerListRouteImport
      parentRoute: typeof AuthenticatedPlannerRoute
    }
    '/_authenticated/planner/helper': {
      id: '/_authenticated/planner/helper'
      path: '/helper'
      fullPath: '/planner/helper'
      preLoaderRoute: typeof AuthenticatedPlannerHelperRouteImport
      parentRoute: typeof AuthenticatedPlannerRoute
    }
    '/_authenticated/planner/gifts': {
      id: '/_authenticated/planner/gifts'
      path: '/gifts'
      fullPath: '/planner/gifts'
      preLoaderRoute: typeof AuthenticatedPlannerGiftsRouteImport
      parentRoute: typeof AuthenticatedPlannerRoute
    }
    '/_authenticated/planner/cards': {
      id: '/_authenticated/planner/cards'
      path: '/cards'
      fullPath: '/planner/cards'
      preLoaderRoute: typeof AuthenticatedPlannerCardsRouteImport
      parentRoute: typeof AuthenticatedPlannerRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/planner/people/': {
      id: '/_authenticated/planner/people/'
      path: '/'
      fullPath: '/planner/people/'
      preLoaderRoute: typeof AuthenticatedPlannerPeopleIndexRouteImport
      parentRoute: typeof AuthenticatedPlannerPeopleRoute
    }
    '/_authenticated/planner/people/$personId': {
      id: '/_authenticated/planner/people/$personId'
      path: '/$personId'
      fullPath: '/planner/people/$personId'
      preLoaderRoute: typeof AuthenticatedPlannerPeoplePersonIdRouteImport
      parentRoute: typeof AuthenticatedPlannerPeopleRoute
    }
  }
}

interface AuthenticatedPlannerPeopleRouteChildren {
  AuthenticatedPlannerPeoplePersonIdRoute: typeof AuthenticatedPlannerPeoplePersonIdRoute
  AuthenticatedPlannerPeopleIndexRoute: typeof AuthenticatedPlannerPeopleIndexRoute
}

const AuthenticatedPlannerPeopleRouteChildren: AuthenticatedPlannerPeopleRouteChildren =
  {
    AuthenticatedPlannerPeoplePersonIdRoute:
      AuthenticatedPlannerPeoplePersonIdRoute,
    AuthenticatedPlannerPeopleIndexRoute: AuthenticatedPlannerPeopleIndexRoute,
  }

const AuthenticatedPlannerPeopleRouteWithChildren =
  AuthenticatedPlannerPeopleRoute._addFileChildren(
    AuthenticatedPlannerPeopleRouteChildren,
  )

interface AuthenticatedPlannerRouteChildren {
  AuthenticatedPlannerCardsRoute: typeof AuthenticatedPlannerCardsRoute
  AuthenticatedPlannerGiftsRoute: typeof AuthenticatedPlannerGiftsRoute
  AuthenticatedPlannerHelperRoute: typeof AuthenticatedPlannerHelperRoute
  AuthenticatedPlannerListRoute: typeof AuthenticatedPlannerListRoute
  AuthenticatedPlannerPeopleRoute: typeof AuthenticatedPlannerPeopleRouteWithChildren
  AuthenticatedPlannerRemindersRoute: typeof AuthenticatedPlannerRemindersRoute
  AuthenticatedPlannerSetupRoute: typeof AuthenticatedPlannerSetupRoute
  AuthenticatedPlannerTimelineRoute: typeof AuthenticatedPlannerTimelineRoute
  AuthenticatedPlannerTodosRoute: typeof AuthenticatedPlannerTodosRoute
  AuthenticatedPlannerIndexRoute: typeof AuthenticatedPlannerIndexRoute
}

const AuthenticatedPlannerRouteChildren: AuthenticatedPlannerRouteChildren = {
  AuthenticatedPlannerCardsRoute: AuthenticatedPlannerCardsRoute,
  AuthenticatedPlannerGiftsRoute: AuthenticatedPlannerGiftsRoute,
  AuthenticatedPlannerHelperRoute: AuthenticatedPlannerHelperRoute,
  AuthenticatedPlannerListRoute: AuthenticatedPlannerListRoute,
  AuthenticatedPlannerPeopleRoute: AuthenticatedPlannerPeopleRouteWithChildren,
  AuthenticatedPlannerRemindersRoute: AuthenticatedPlannerRemindersRoute,
  AuthenticatedPlannerSetupRoute: AuthenticatedPlannerSetupRoute,
  AuthenticatedPlannerTimelineRoute: AuthenticatedPlannerTimelineRoute,
  AuthenticatedPlannerTodosRoute: AuthenticatedPlannerTodosRoute,
  AuthenticatedPlannerIndexRoute: AuthenticatedPlannerIndexRoute,
}

const AuthenticatedPlannerRouteWithChildren =
  AuthenticatedPlannerRoute._addFileChildren(AuthenticatedPlannerRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPlannerRoute: typeof AuthenticatedPlannerRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPlannerRoute: AuthenticatedPlannerRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AssistantRoute: AssistantRoute,
  AuthRoute: AuthRoute,
  ComingSoonRoute: ComingSoonRoute,
  DaysOutRoute: DaysOutRoute,
  EntertainmentRoute: EntertainmentRoute,
  FoodRoute: FoodRoute,
  GiftFinderRoute: GiftFinderRoute,
  InspireRoute: InspireRoute,
  McpRoute: McpRoute,
  PartnersRoute: PartnersRoute,
  PetsRoute: PetsRoute,
  SaveRoute: SaveRoute,
  VipRoute: VipRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  TeachersCategoryRoute: TeachersCategoryRoute,
  TeachersGenerateRoute: TeachersGenerateRoute,
  TeachersIndexRoute: TeachersIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
