import type { MealKey } from "./constants";

/**
 * Curated Christmas food suggestions. Dish names and metadata only — no
 * recipes, no links, no prices. Accepting a suggestion writes an ordinary
 * food_items row, so there is only ever one food plan.
 */
export interface MenuStyle {
  key: string;
  label: string;
  blurb: string;
}

export interface Suggestion {
  key: string;
  name: string;
  meal: MealKey;
  course: string;
  /** Which curated styles this dish can appear in. */
  styles: string[];
  /** Default occasion keys this dish suits. Omit = any occasion. */
  occasions?: string[];
  /** Dietary tags this dish is intended to accommodate (e.g. vegetarian). */
  dietary_tags?: string[];
  /** Major allergens or ingredients to avoid (meat, fish, gluten, dairy, nuts). */
  contains?: string[];
  /** Good for children to eat. */
  childFriendly?: boolean;
  /** Not suitable for a family-friendly context (e.g. alcohol-heavy). */
  adultOnly?: boolean;
  /** 1 = value, 2 = mid, 3 = premium. */
  budget?: 1 | 2 | 3;
  /** 1 = easy, 2 = mid, 3 = involved. */
  effort?: 1 | 2 | 3;
  /** When the dish can be prepared. */
  makeAhead?: "make_ahead" | "day_before" | "on_the_day";
  /** Works well scaled up for a crowd. */
  scales?: boolean;
  note?: string;
}

export const MENU_STYLES: MenuStyle[] = [
  { key: "traditional", label: "Traditional Christmas", blurb: "The full works, done properly." },
  { key: "easy", label: "Easy / low stress", blurb: "Make-ahead and forgiving." },
  { key: "budget", label: "Budget friendly", blurb: "Generous without the big spend." },
  { key: "luxury", label: "Luxury / special", blurb: "A few showstoppers." },
  { key: "vegetarian", label: "Vegetarian", blurb: "Meat-free and still festive." },
  { key: "buffet", label: "Buffet / picky bits", blurb: "Grazing all afternoon." },
  { key: "family", label: "Family friendly", blurb: "Things children actually eat." },
  { key: "different", label: "Something different", blurb: "A break from tradition." },
];

export type MenuStyleKey = (typeof MENU_STYLES)[number]["key"];

/** One flat, metadata-carrying pool of curated dishes. */
export const SUGGESTIONS: Suggestion[] = [
  /* ----------------------------- Traditional ----------------------------- */
  {
    key: "trad-smoked-salmon",
    name: "Smoked salmon with lemon",
    meal: "dinner",
    course: "Starters",
    styles: ["traditional", "luxury"],
    contains: ["fish"],
    childFriendly: false,
    budget: 3,
    effort: 2,
    makeAhead: "day_before",
    scales: true,
  },
  {
    key: "trad-prawn-cocktail",
    name: "Prawn cocktail",
    meal: "dinner",
    course: "Starters",
    styles: ["traditional", "budget"],
    contains: ["fish"],
    childFriendly: false,
    budget: 2,
    effort: 1,
    makeAhead: "day_before",
    scales: true,
  },
  {
    key: "trad-turkey",
    name: "Roast turkey with all the trimmings",
    meal: "dinner",
    course: "Main",
    styles: ["traditional", "family"],
    contains: ["meat"],
    childFriendly: true,
    budget: 2,
    effort: 3,
    makeAhead: "on_the_day",
    scales: true,
  },
  {
    key: "trad-pigs",
    name: "Pigs in blankets",
    meal: "dinner",
    course: "Sides",
    styles: ["traditional", "budget", "family"],
    contains: ["meat"],
    childFriendly: true,
    budget: 1,
    effort: 2,
    makeAhead: "day_before",
    scales: true,
  },
  {
    key: "trad-roasties",
    name: "Roast potatoes",
    meal: "dinner",
    course: "Sides",
    styles: ["traditional", "easy", "budget", "family", "vegetarian"],
    dietary_tags: ["vegan", "gluten_free"],
    childFriendly: true,
    budget: 1,
    effort: 2,
    makeAhead: "day_before",
    scales: true,
  },
  {
    key: "trad-sprouts",
    name: "Sprouts with bacon",
    meal: "dinner",
    course: "Sides",
    styles: ["traditional"],
    contains: ["meat"],
    childFriendly: false,
    budget: 1,
    effort: 2,
    makeAhead: "day_before",
    scales: true,
  },
  {
    key: "trad-stuffing",
    name: "Sage & onion stuffing",
    meal: "dinner",
    course: "Sides",
    styles: ["traditional", "family"],
    contains: ["meat"],
    childFriendly: true,
    budget: 1,
    effort: 2,
    makeAhead: "day_before",
    scales: true,
  },
  {
    key: "trad-bread-sauce",
    name: "Bread sauce",
    meal: "dinner",
    course: "Sides",
    styles: ["traditional"],
    contains: ["gluten", "dairy"],
    childFriendly: true,
    budget: 1,
    effort: 2,
    makeAhead: "day_before",
    scales: true,
  },
  {
    key: "trad-pudding",
    name: "Christmas pudding & brandy butter",
    meal: "desserts",
    course: "Desserts",
    styles: ["traditional"],
    contains: ["gluten", "dairy"],
    childFriendly: false,
    budget: 2,
    effort: 3,
    makeAhead: "make_ahead",
    scales: true,
  },
  {
    key: "trad-trifle",
    name: "Sherry trifle",
    meal: "desserts",
    course: "Desserts",
    styles: ["traditional"],
    contains: ["gluten", "dairy"],
    childFriendly: false,
    budget: 2,
    effort: 2,
    makeAhead: "day_before",
    scales: true,
  },
  {
    key: "trad-mulled",
    name: "Mulled wine",
    meal: "drinks",
    course: "Drinks",
    styles: ["traditional", "luxury"],
    adultOnly: true,
    budget: 2,
    effort: 1,
    makeAhead: "make_ahead",
    scales: true,
  },
  {
    key: "trad-fizz",
    name: "Something fizzy for the toast",
    meal: "drinks",
    course: "Drinks",
    styles: ["traditional", "budget", "family"],
    childFriendly: true,
    budget: 1,
    effort: 1,
    makeAhead: "on_the_day",
    scales: true,
  },

  /* ---------------------------------- Easy --------------------------------- */
  {
    key: "easy-soup",
    name: "Make-ahead spiced parsnip soup",
    meal: "dinner",
    course: "Starters",
    styles: ["easy", "vegetarian"],
    dietary_tags: ["vegan", "gluten_free"],
    childFriendly: false,
    budget: 1,
    effort: 1,
    makeAhead: "make_ahead",
    scales: true,
    note: "Freezes well",
  },
  {
    key: "easy-crown",
    name: "Turkey crown (quicker to cook)",
    meal: "dinner",
    course: "Main",
    styles: ["easy", "family"],
    contains: ["meat"],
    childFriendly: true,
    budget: 2,
    effort: 1,
    makeAhead: "on_the_day",
    scales: false,
  },
  {
    key: "easy-gammon",
    name: "Slow-cooker gammon",
    meal: "dinner",
    course: "Main",
    styles: ["easy", "budget", "family"],
    contains: ["meat"],
    childFriendly: true,
    budget: 2,
    effort: 1,
    makeAhead: "make_ahead",
    scales: true,
  },
  {
    key: "easy-frozen-roasties",
    name: "Good frozen roast potatoes",
    meal: "dinner",
    course: "Sides",
    styles: ["easy", "budget", "family"],
    dietary_tags: ["vegan", "gluten_free"],
    childFriendly: true,
    budget: 1,
    effort: 1,
    makeAhead: "on_the_day",
    scales: true,
  },
  {
    key: "easy-traybake-veg",
    name: "One-tray honey roast vegetables",
    meal: "dinner",
    course: "Sides",
    styles: ["easy", "vegetarian", "budget", "family"],
    dietary_tags: ["vegan", "gluten_free"],
    childFriendly: true,
    budget: 1,
    effort: 1,
    makeAhead: "on_the_day",
    scales: true,
  },
  {
    key: "easy-red-cabbage",
    name: "Braised red cabbage (make 2 days ahead)",
    meal: "dinner",
    course: "Sides",
    styles: ["easy", "vegetarian", "budget"],
    dietary_tags: ["vegan", "gluten_free"],
    childFriendly: true,
    budget: 1,
    effort: 1,
    makeAhead: "make_ahead",
    scales: true,
  },
  {
    key: "easy-cheesecake",
    name: "No-bake Baileys cheesecake",
    meal: "desserts",
    course: "Desserts",
    styles: ["easy"],
    contains: ["dairy"],
    adultOnly: true,
    budget: 2,
    effort: 1,
    makeAhead: "day_before",
    scales: true,
  },
  {
    key: "easy-icecream",
    name: "Ice cream with warm mince pies",
    meal: "desserts",
    course: "Desserts",
    styles: ["easy", "family", "budget"],
    contains: ["gluten", "dairy"],
    childFriendly: true,
    budget: 1,
    effort: 1,
    makeAhead: "on_the_day",
    scales: true,
  },
  {
    key: "easy-batch-cocktail",
    name: "Batch-made Christmas punch",
    meal: "drinks",
    course: "Drinks",
    styles: ["easy", "budget", "family"],
    childFriendly: true,
    budget: 1,
    effort: 1,
    makeAhead: "make_ahead",
    scales: true,
  },

  /* -------------------------------- Budget --------------------------------- */
  {
    key: "bud-soup",
    name: "Homemade tomato & basil soup",
    meal: "dinner",
    course: "Starters",
    styles: ["budget", "vegetarian", "family"],
    dietary_tags: ["vegan", "gluten_free"],
    childFriendly: true,
    budget: 1,
    effort: 1,
    makeAhead: "make_ahead",
    scales: true,
  },
  {
    key: "bud-chicken",
    name: "Roast chicken with lemon & thyme",
    meal: "dinner",
    course: "Main",
    styles: ["budget", "family", "easy"],
    contains: ["meat"],
    childFriendly: true,
    budget: 1,
    effort: 2,
    makeAhead: "on_the_day",
    scales: true,
  },
  {
    key: "bud-pork",
    name: "Slow-roast pork shoulder",
    meal: "dinner",
    course: "Main",
    styles: ["budget", "family"],
    contains: ["meat"],
    childFriendly: true,
    budget: 1,
    effort: 2,
    makeAhead: "day_before",
    scales: true,
  },
  {
    key: "bud-roasties",
    name: "Roast potatoes in goose fat",
    meal: "dinner",
    course: "Sides",
    styles: ["budget", "traditional", "family"],
    dietary_tags: ["vegetarian", "gluten_free"],
    childFriendly: true,
    budget: 1,
    effort: 2,
    makeAhead: "day_before",
    scales: true,
  },
  {
    key: "bud-carrots",
    name: "Honey roast carrots & parsnips",
    meal: "dinner",
    course: "Sides",
    styles: ["budget", "easy", "family", "vegetarian"],
    dietary_tags: ["vegan", "gluten_free"],
    childFriendly: true,
    budget: 1,
    effort: 1,
    makeAhead: "on_the_day",
    scales: true,
  },
  {
    key: "bud-yorkshires",
    name: "Yorkshire puddings",
    meal: "dinner",
    course: "Sides",
    styles: ["budget", "traditional", "family"],
    contains: ["gluten", "dairy"],
    childFriendly: true,
    budget: 1,
    effort: 2,
    makeAhead: "day_before",
    scales: true,
  },
  {
    key: "bud-crumble",
    name: "Apple & blackberry crumble",
    meal: "desserts",
    course: "Desserts",
    styles: ["budget", "family", "vegetarian"],
    contains: ["gluten", "dairy"],
    childFriendly: true,
    budget: 1,
    effort: 1,
    makeAhead: "day_before",
    scales: true,
  },
  {
    key: "bud-mince-pies",
    name: "Mince pies with cream",
    meal: "desserts",
    course: "Desserts",
    styles: ["budget", "traditional", "family"],
    contains: ["gluten", "dairy"],
    childFriendly: true,
    budget: 1,
    effort: 2,
    makeAhead: "make_ahead",
    scales: true,
  },
  {
    key: "bud-squash",
    name: "Homemade lemonade & squash for the children",
    meal: "drinks",
    course: "Drinks",
    styles: ["budget", "family"],
    childFriendly: true,
    budget: 1,
    effort: 1,
    makeAhead: "make_ahead",
    scales: true,
  },

  /* ------------------------------- Luxury --------------------------------- */
  {
    key: "lux-oysters",
    name: "Oysters with shallot vinegar",
    meal: "dinner",
    course: "Starters",
    styles: ["luxury"],
    contains: ["fish"],
    adultOnly: true,
    childFriendly: false,
    budget: 3,
    effort: 1,
    makeAhead: "on_the_day",
    scales: false,
  },
  {
    key: "lux-scallops",
    name: "Seared scallops with black pudding",
    meal: "dinner",
    course: "Starters",
    styles: ["luxury"],
    contains: ["fish", "meat"],
    adultOnly: true,
    childFriendly: false,
    budget: 3,
    effort: 2,
    makeAhead: "on_the_day",
    scales: false,
  },
  {
    key: "lux-beef",
    name: "Rib of beef with red wine gravy",
    meal: "dinner",
    course: "Main",
    styles: ["luxury", "different"],
    contains: ["meat"],
    childFriendly: true,
    budget: 3,
    effort: 3,
    makeAhead: "on_the_day",
    scales: true,
  },
  {
    key: "lux-goose",
    name: "Roast goose with spiced apples",
    meal: "dinner",
    course: "Main",
    styles: ["luxury", "traditional"],
    contains: ["meat"],
    childFriendly: true,
    budget: 3,
    effort: 3,
    makeAhead: "on_the_day",
    scales: true,
  },
  {
    key: "lux-dauphinoise",
    name: "Potato dauphinoise",
    meal: "dinner",
    course: "Sides",
    styles: ["luxury"],
    dietary_tags: ["vegetarian"],
    contains: ["dairy"],
    childFriendly: true,
    budget: 2,
    effort: 2,
    makeAhead: "day_before",
    scales: true,
  },
  {
    key: "lux-truffle-sprouts",
    name: "Sprouts with chestnuts & truffle oil",
    meal: "dinner",
    course: "Sides",
    styles: ["luxury", "vegetarian"],
    dietary_tags: ["vegetarian"],
    contains: ["nuts"],
    childFriendly: false,
    budget: 3,
    effort: 2,
    makeAhead: "day_before",
    scales: true,
  },
  {
    key: "lux-bombe",
    name: "Chocolate & clementine bombe",
    meal: "desserts",
    course: "Desserts",
    styles: ["luxury"],
    dietary_tags: ["vegetarian"],
    contains: ["dairy"],
    childFriendly: true,
    budget: 3,
    effort: 3,
    makeAhead: "day_before",
    scales: true,
  },
  {
    key: "lux-cheese",
    name: "Cheeseboard with quince & port",
    meal: "desserts",
    course: "Cheese",
    styles: ["luxury"],
    contains: ["dairy"],
    adultOnly: true,
    childFriendly: false,
    budget: 3,
    effort: 1,
    makeAhead: "make_ahead",
    scales: true,
  },
  {
    key: "lux-champagne",
    name: "Champagne",
    meal: "drinks",
    course: "Drinks",
    styles: ["luxury"],
    adultOnly: true,
    budget: 3,
    effort: 1,
    makeAhead: "on_the_day",
    scales: true,
  },

  /* ------------------------------ Vegetarian ------------------------------ */
  {
    key: "veg-soup",
    name: "Chestnut & mushroom soup",
    meal: "dinner",
    course: "Starters",
    styles: ["vegetarian"],
    dietary_tags: ["vegetarian", "vegan"],
    contains: ["nuts"],
    childFriendly: false,
    budget: 2,
    effort: 2,
    makeAhead: "day_before",
    scales: true,
  },
  {
    key: "veg-wellington",
    name: "Mushroom & chestnut wellington",
    meal: "dinner",
    course: "Main",
    styles: ["vegetarian"],
    dietary_tags: ["vegetarian", "vegan"],
    contains: ["nuts"],
    childFriendly: true,
    budget: 2,
    effort: 3,
    makeAhead: "day_before",
    scales: true,
  },
  {
    key: "veg-nutroast",
    name: "Cranberry & walnut nut roast",
    meal: "dinner",
    course: "Main",
    styles: ["vegetarian"],
    dietary_tags: ["vegetarian", "vegan"],
    contains: ["nuts"],
    childFriendly: true,
    budget: 2,
    effort: 3,
    makeAhead: "day_before",
    scales: true,
  },
  {
    key: "veg-squash",
    name: "Stuffed butternut squash",
    meal: "dinner",
    course: "Main",
    styles: ["vegetarian", "easy", "budget"],
    dietary_tags: ["vegan", "gluten_free"],
    childFriendly: true,
    budget: 2,
    effort: 2,
    makeAhead: "on_the_day",
    scales: true,
  },
  {
    key: "veg-roasties",
    name: "Roast potatoes in olive oil",
    meal: "dinner",
    course: "Sides",
    styles: ["vegetarian", "easy", "budget"],
    dietary_tags: ["vegan", "gluten_free"],
    childFriendly: true,
    budget: 1,
    effort: 2,
    makeAhead: "day_before",
    scales: true,
  },
  {
    key: "veg-cauli",
    name: "Cauliflower cheese",
    meal: "dinner",
    course: "Sides",
    styles: ["vegetarian", "family", "budget"],
    dietary_tags: ["vegetarian"],
    contains: ["dairy"],
    childFriendly: true,
    budget: 2,
    effort: 2,
    makeAhead: "day_before",
    scales: true,
  },
  {
    key: "veg-greens",
    name: "Garlic greens with almonds",
    meal: "dinner",
    course: "Sides",
    styles: ["vegetarian", "luxury"],
    dietary_tags: ["vegetarian", "vegan"],
    contains: ["nuts"],
    childFriendly: true,
    budget: 2,
    effort: 1,
    makeAhead: "on_the_day",
    scales: true,
  },
  {
    key: "veg-pavlova",
    name: "Winter berry pavlova",
    meal: "desserts",
    course: "Desserts",
    styles: ["vegetarian", "family"],
    dietary_tags: ["vegetarian", "gluten_free"],
    contains: ["dairy"],
    childFriendly: true,
    budget: 2,
    effort: 2,
    makeAhead: "day_before",
    scales: true,
  },
  {
    key: "veg-choc-pots",
    name: "Dark chocolate pots",
    meal: "desserts",
    course: "Desserts",
    styles: ["vegetarian", "vegan", "easy"],
    dietary_tags: ["vegan", "gluten_free"],
    childFriendly: true,
    budget: 2,
    effort: 1,
    makeAhead: "day_before",
    scales: true,
  },

  /* -------------------------------- Buffet --------------------------------- */
  {
    key: "buf-sandwiches",
    name: "Turkey & cranberry sandwiches",
    meal: "buffet",
    course: "Cold",
    styles: ["buffet", "budget", "family"],
    contains: ["meat", "gluten", "dairy"],
    childFriendly: true,
    budget: 1,
    effort: 1,
    makeAhead: "day_before",
    scales: true,
  },
  {
    key: "buf-quiche",
    name: "Quiche slices",
    meal: "buffet",
    course: "Cold",
    styles: ["buffet", "vegetarian", "budget"],
    dietary_tags: ["vegetarian"],
    contains: ["gluten", "dairy"],
    childFriendly: true,
    budget: 1,
    effort: 2,
    makeAhead: "day_before",
    scales: true,
  },
  {
    key: "buf-salads",
    name: "Two big salads",
    meal: "buffet",
    course: "Cold",
    styles: ["buffet", "vegetarian", "easy", "budget"],
    dietary_tags: ["vegan", "gluten_free"],
    childFriendly: true,
    budget: 1,
    effort: 1,
    makeAhead: "on_the_day",
    scales: true,
  },
  {
    key: "buf-sausage-rolls",
    name: "Sausage rolls",
    meal: "buffet",
    course: "Hot",
    styles: ["buffet", "budget", "family"],
    contains: ["meat", "gluten"],
    childFriendly: true,
    budget: 1,
    effort: 2,
    makeAhead: "day_before",
    scales: true,
  },
  {
    key: "buf-wings",
    name: "Sticky glazed chicken wings",
    meal: "buffet",
    course: "Hot",
    styles: ["buffet", "family"],
    contains: ["meat"],
    childFriendly: true,
    budget: 2,
    effort: 2,
    makeAhead: "day_before",
    scales: true,
  },
  {
    key: "buf-baked-camembert",
    name: "Baked camembert with bread",
    meal: "buffet",
    course: "Hot",
    styles: ["buffet", "vegetarian"],
    dietary_tags: ["vegetarian"],
    contains: ["dairy", "gluten"],
    childFriendly: true,
    budget: 2,
    effort: 1,
    makeAhead: "on_the_day",
    scales: true,
  },
  {
    key: "buf-cheese",
    name: "Cheeseboard with crackers & chutney",
    meal: "buffet",
    course: "Cheese",
    styles: ["buffet", "family", "vegetarian"],
    dietary_tags: ["vegetarian"],
    contains: ["dairy", "gluten"],
    childFriendly: true,
    budget: 2,
    effort: 1,
    makeAhead: "make_ahead",
    scales: true,
  },
  {
    key: "buf-brownies",
    name: "Chocolate brownies",
    meal: "desserts",
    course: "Desserts",
    styles: ["buffet", "family", "budget"],
    dietary_tags: ["vegetarian"],
    contains: ["gluten", "dairy"],
    childFriendly: true,
    budget: 1,
    effort: 2,
    makeAhead: "day_before",
    scales: true,
  },
  {
    key: "buf-fruit",
    name: "Fruit platter",
    meal: "desserts",
    course: "Desserts",
    styles: ["buffet", "family", "vegetarian", "vegan"],
    dietary_tags: ["vegan", "gluten_free"],
    childFriendly: true,
    budget: 1,
    effort: 1,
    makeAhead: "on_the_day",
    scales: true,
  },
  {
    key: "buf-punch",
    name: "Non-alcoholic Christmas punch",
    meal: "drinks",
    course: "Drinks",
    styles: ["buffet", "family", "budget"],
    childFriendly: true,
    budget: 1,
    effort: 1,
    makeAhead: "make_ahead",
    scales: true,
  },

  /* -------------------------------- Family --------------------------------- */
  {
    key: "fam-dippers",
    name: "Bread & dips to keep everyone going",
    meal: "snacks",
    course: "Starters",
    styles: ["family", "buffet"],
    dietary_tags: ["vegetarian"],
    contains: ["gluten"],
    childFriendly: true,
    budget: 1,
    effort: 1,
    makeAhead: "on_the_day",
    scales: true,
  },
  {
    key: "fam-chicken",
    name: "Roast chicken (an easy sell with children)",
    meal: "dinner",
    course: "Main",
    styles: ["family", "budget", "easy"],
    contains: ["meat"],
    childFriendly: true,
    budget: 1,
    effort: 2,
    makeAhead: "on_the_day",
    scales: true,
  },
  {
    key: "fam-pigs",
    name: "Pigs in blankets",
    meal: "dinner",
    course: "Sides",
    styles: ["family", "budget", "traditional"],
    contains: ["meat"],
    childFriendly: true,
    budget: 1,
    effort: 2,
    makeAhead: "day_before",
    scales: true,
  },
  {
    key: "fam-mash",
    name: "Buttery mashed potato",
    meal: "dinner",
    course: "Sides",
    styles: ["family", "budget", "easy"],
    dietary_tags: ["vegetarian"],
    contains: ["dairy"],
    childFriendly: true,
    budget: 1,
    effort: 1,
    makeAhead: "day_before",
    scales: true,
  },
  {
    key: "fam-sweetcorn",
    name: "Sweetcorn & peas",
    meal: "dinner",
    course: "Sides",
    styles: ["family", "budget", "easy"],
    dietary_tags: ["vegan", "gluten_free"],
    childFriendly: true,
    budget: 1,
    effort: 1,
    makeAhead: "on_the_day",
    scales: true,
  },
  {
    key: "fam-yule",
    name: "Chocolate yule log",
    meal: "desserts",
    course: "Desserts",
    styles: ["family", "budget"],
    dietary_tags: ["vegetarian"],
    contains: ["gluten", "dairy"],
    childFriendly: true,
    budget: 1,
    effort: 2,
    makeAhead: "day_before",
    scales: true,
  },
  {
    key: "fam-jelly",
    name: "Jelly & ice cream",
    meal: "desserts",
    course: "Desserts",
    styles: ["family", "budget"],
    dietary_tags: ["vegetarian"],
    contains: ["dairy"],
    childFriendly: true,
    budget: 1,
    effort: 1,
    makeAhead: "day_before",
    scales: true,
  },
  {
    key: "fam-hotchoc",
    name: "Hot chocolate with marshmallows",
    meal: "drinks",
    course: "Drinks",
    styles: ["family", "budget"],
    dietary_tags: ["vegetarian"],
    contains: ["dairy"],
    childFriendly: true,
    budget: 1,
    effort: 1,
    makeAhead: "on_the_day",
    scales: true,
  },
  {
    key: "fam-breakfast",
    name: "Christmas morning pastries",
    meal: "breakfast",
    course: "Breakfast",
    styles: ["family", "budget"],
    dietary_tags: ["vegetarian"],
    contains: ["gluten", "dairy"],
    childFriendly: true,
    budget: 1,
    effort: 1,
    makeAhead: "on_the_day",
    scales: true,
  },

  /* ------------------------------- Different ------------------------------- */
  {
    key: "dif-seafood",
    name: "Seafood sharing platter",
    meal: "dinner",
    course: "Starters",
    styles: ["different", "luxury"],
    contains: ["fish"],
    childFriendly: false,
    budget: 3,
    effort: 1,
    makeAhead: "on_the_day",
    scales: true,
  },
  {
    key: "dif-curry",
    name: "Christmas curry feast",
    meal: "dinner",
    course: "Main",
    styles: ["different", "family", "easy"],
    childFriendly: true,
    budget: 2,
    effort: 2,
    makeAhead: "day_before",
    scales: true,
  },
  {
    key: "dif-fondue",
    name: "Cheese fondue night",
    meal: "dinner",
    course: "Main",
    styles: ["different", "vegetarian"],
    dietary_tags: ["vegetarian"],
    contains: ["dairy", "gluten"],
    childFriendly: true,
    budget: 2,
    effort: 2,
    makeAhead: "on_the_day",
    scales: true,
  },
  {
    key: "dif-tapas",
    name: "Festive tapas spread",
    meal: "buffet",
    course: "Sides",
    styles: ["different", "buffet", "family"],
    childFriendly: true,
    budget: 2,
    effort: 2,
    makeAhead: "on_the_day",
    scales: true,
  },
  {
    key: "dif-porchetta",
    name: "Porchetta with fennel",
    meal: "dinner",
    course: "Main",
    styles: ["different", "luxury"],
    contains: ["meat"],
    childFriendly: true,
    budget: 3,
    effort: 3,
    makeAhead: "on_the_day",
    scales: true,
  },
  {
    key: "dif-tiramisu",
    name: "Clementine tiramisu",
    meal: "desserts",
    course: "Desserts",
    styles: ["different"],
    dietary_tags: ["vegetarian"],
    contains: ["gluten", "dairy"],
    adultOnly: true,
    childFriendly: false,
    budget: 2,
    effort: 2,
    makeAhead: "day_before",
    scales: true,
  },
  {
    key: "dif-churros",
    name: "Churros with chocolate",
    meal: "desserts",
    course: "Desserts",
    styles: ["different", "family", "budget"],
    dietary_tags: ["vegetarian"],
    contains: ["gluten", "dairy"],
    childFriendly: true,
    budget: 1,
    effort: 2,
    makeAhead: "on_the_day",
    scales: true,
  },
  {
    key: "dif-negroni",
    name: "Batch negronis",
    meal: "drinks",
    course: "Drinks",
    styles: ["different", "luxury"],
    adultOnly: true,
    budget: 2,
    effort: 1,
    makeAhead: "make_ahead",
    scales: true,
  },

  /* ------------------------ Extra dietary options -------------------------- */
  {
    key: "extra-vegan-main",
    name: "Lentil & mushroom cottage pie",
    meal: "dinner",
    course: "Main",
    styles: ["vegetarian", "easy", "budget", "family"],
    dietary_tags: ["vegan", "gluten_free"],
    childFriendly: true,
    budget: 1,
    effort: 1,
    makeAhead: "day_before",
    scales: true,
  },
  {
    key: "extra-gf-dessert",
    name: "Flourless orange & almond cake",
    meal: "desserts",
    course: "Desserts",
    styles: ["vegetarian", "easy", "budget"],
    dietary_tags: ["gluten_free"],
    contains: ["nuts", "dairy"],
    childFriendly: true,
    budget: 2,
    effort: 2,
    makeAhead: "day_before",
    scales: true,
  },
  {
    key: "extra-df-side",
    name: "Herb-roasted new potatoes",
    meal: "dinner",
    course: "Sides",
    styles: ["vegetarian", "easy", "budget", "family"],
    dietary_tags: ["vegan", "gluten_free", "dairy_free"],
    childFriendly: true,
    budget: 1,
    effort: 1,
    makeAhead: "day_before",
    scales: true,
  },
  {
    key: "extra-nutfree-main",
    name: "Roasted vegetable & quinoa stuffed peppers",
    meal: "dinner",
    course: "Main",
    styles: ["vegetarian", "easy", "budget"],
    dietary_tags: ["vegan", "gluten_free"],
    childFriendly: true,
    budget: 1,
    effort: 2,
    makeAhead: "on_the_day",
    scales: true,
  },
];

export function suggestionsFor(style: MenuStyleKey): Suggestion[] {
  return SUGGESTIONS.filter((s) => s.styles.includes(style));
}

/** Course order used to group the suggested menu on screen. */
export const COURSE_ORDER = ["Breakfast", "Starters", "Main", "Cold", "Hot", "Sides", "Cheese", "Desserts", "Drinks"];
